### ISSUE TITLE
Autoload stores only the last edited preset in `~/.config/input-remapper-2/config.json`

### ISSUE THREAD

**Issue by noyannus** [sezanzeb/input-remapper#1009]
How to replicate:

0) Start input-remapper as user
1) Set or edit a preset and activate it: click [Stop] - [Autoload ON] - [Apply]
2) Check the config: `cat ~/.config/input-remapper-2/config.json` and note the line with the just edited device and its preset
3) Repeat 1) with a _different_ preset
4) Repeat 2) and compare the now set device/preset line with the one from 2).

Result: only the last edited preset appears in `"autoload": {  <preset> }`

Seen with 
input-remapper "version": "2.0.1"
on 
Operating System: openSUSE Tumbleweed-Slowroll 20241103
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.6-2-default (64-bit)
Graphics Platform: X11

**Comment by sezanzeb** [comment]
input-remapper can only run one preset for a device at a time. If you set autoload on a different preset, the old autoload entry will be overwritten.

If you switch to a different device, it will add it to the config, like this:

Toggle Autoload on "new preset 2"

```
{
    "version": "2.0.1",
    "autoload": {
        "Logitech USB Keyboard": "new preset 2"
    }
}
```

go to "new preset" and toggle Autoload

```
{
    "version": "2.0.1",
    "autoload": {
        "Logitech USB Keyboard": "new preset"
    }
}
```

Select the mouse and use the Autoload toggle on a preset there:

```
{
    "version": "2.0.1",
    "autoload": {
        "Logitech USB Keyboard": "new preset",
        "USB Optical Mouse": "new preset"
    }
}
```

**Comment by noyannus** [comment]
Ah, I see. Thank you for the explanation.

On a different note an idea. If there will never be more than one preset per device, the functions of the "Presets" pane could be merged into the "Devices" pane. Underneath each device's name could go a few buttons, like [Start] [Stop] [Edit]. Maybe also [Autoload], because its function involves starting, it could be placed on the same UI element as [Start].
OTOH, if you plan to add several presets for any device that idea is moot.
