### ISSUE TITLE
Tartarus Pro wheel sending both wheel up and down events and remapping

### ISSUE THREAD

**Issue by jeisom** [sezanzeb/input-remapper#1011]
I am trying to remap the wheel on my Tartarus Pro and I can't get it to just send the remapping.  It sends both the wheel event and the remapped output.  I successfully remapped the middle click and it doesn't seem to do this .  Using the latest main branch(2024-12-05) on Plasma wayland 6.2.4.

debug log attached

[debug-input-remapper.txt](https://github.com/user-attachments/files/18031772/debug-input-remapper.txt)

**Comment by sezanzeb** [comment]
Check the section "Wheels" in https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#wheels out, does that help?

**Comment by jeisom** [comment]
Thanks, that fixed it.  Maybe a future version could display an info warning about that when wheel is being mapped.
