### ISSUE TITLE
wont start anymore

### ISSUE THREAD

**Issue by Rosenblack** [sezanzeb/input-remapper#1014]
Ive been at this for 3 hours, it use to work, then i turn my pc back on and it loads for a second, its in the panel then closes immediately, idk what to give you, just tell me things to try, im on endeavouros using the newest version of this program

**Comment by Rosenblack** [comment]
fixed, had to downgrade glib, didnt know how, now i do

**Comment by maxiixam** [comment]
Can confirm after updating just now that it once again is working on Arch. I restarted the service for good measure, but it applied my preset and works on my tartarus pro.

**Comment by WyvernDotRed** [comment]
@Rosenblack since this issue seems to have been resolved, can you update your system and confirm?
If so you can close this issue too, since the software works again after an Arch Linux update and system restart.
