### ISSUE TITLE
No longer able to move mouse cursor

### ISSUE THREAD

**Issue by hanggrian** [sezanzeb/input-remapper#1017]
I recently distro-hopped from Arch to EndeavourOS. Knowing there is no hardware change, I restored the `input-remapper2/presets` directory in `$HOME/.config`. Most macros work fine, but mouse events with movement `REL_X`/`REL_Y` will throw an error. In the example below, I have this macro to press left 4 times after clicking the furthest window of my secondary monitor:

```
event(EV_REL, REL_X, 2000)
.event(EV_REL, REL_X, 1)
.event(EV_REL, REL_X, 2000)
.event(EV_REL, REL_Y, -2000)
.event(EV_REL, REL_X, -100)
.key(BTN_LEFT)
.repeat(4, key(KEY_LEFT))
```

But it stops at the first line with the error:

```
14:50:07.698706 7081 service ERROR macro_handler.py:73: Macro "event(EV_REL,REL_X,2000).event(EV_REL,REL_X,1).event(EV_REL,REL_X,2000).event(EV_REL,REL_Y,-2000).event(EV_REL,REL_X,-100).key(BTN_LEFT).repeat(4,key(KEY_LEFT))" failed with <class 'inputremapper.configs.validation_errors.MacroError'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/inputremapper/injection/mapping_handlers/macro_handler.py", line 71, in run_macro
    await self._macro.run(handler)
  File "/usr/lib/python3.12/site-packages/inputremapper/injection/macros/macro.py", line 97, in run
    await coroutine
  File "/usr/lib/python3.12/site-packages/inputremapper/injection/macros/tasks/event.py", line 61, in run
    self.get_argument("code").assert_is_symbol(code)
  File "/usr/lib/python3.12/site-packages/inputremapper/injection/macros/argument.py", line 193, in assert_is_symbol
    raise MacroError(msg=f'Unknown key "{symbol}"')
inputremapper.configs.validation_errors.MacroError: Unknown key "REL_X"
```

The full output of `sudo pkill -f input-remapper && input-remapper-gtk -d` can be found [here](https://gist.github.com/hanggrian/f2b892c477f57e13a5b74f216b6e8e7f). Please help me find the root cause of this issue, I need this type of macro to skip YouTube display and native ads.

**Comment by sezanzeb** [comment]
Thanks for reporting, fix is on main.

**Comment by hanggrian** [comment]
Thank you for such an amazing tool and your hard work!
