### ISSUE TITLE
Macro editor

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#109]
- [x] show a multiline editor featuring a monospace font and line-numbers
- [x] figure out if the current syntax offers everything that is needed for a clean way to put this stuff into multiple lines
- [x] offer human-readable function names because now there is enough space for that
- [x] syntax highlighting
- [x] how is the editor opened? Is there a button in each line or is it mandatory to open the popup to configure anything?
- [x] comment support for macros
- [x] autocomplete for functions and keys

In the future the macro editor might get multiple tabs if plugins are to be configured for a certain button, becoming an advanced-editor instead.

**Comment by sezanzeb** [comment]
examples of how the syntax can be broken into multiple lines:

```
hold(
    repeat(
        k(a).
        w(100).
        k(b)
    ).
    k(c)
)
```

```
hold(
    repeat(k(a).w(100).k(b)).
    k(c)
)
```

**Comment by sezanzeb** [comment]
If anyone wants to contribute, this is the feature I would like to see the most

**Comment by sezanzeb** [comment]
An alternative view that offers more space for each mapping. Possibly by using a GtkStack

![image](https://user-images.githubusercontent.com/28510156/135754776-7d041c56-a917-403d-b165-fb6e111759fa.png)

![image](https://user-images.githubusercontent.com/28510156/135754872-fab2f84e-35fc-40c1-b228-774faec3101e.png)

**Comment by sezanzeb** [comment]
![image](https://user-images.githubusercontent.com/28510156/147417217-fa709768-9bdd-4479-80e0-64f126e2f446.png)

**Comment by sezanzeb** [comment]
@jonasBoss no tests are written yet. Before I do that, can you please test it real quick? It's on the `macro-editor` branch

**Comment by jonasBoss** [comment]
there is a new dependency, which is not satisfied by `python-gobject`
```
input-remapper-gtk -d
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 36, in <module>
    gi.require_version('GtkSource', '4')
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace GtkSource not available for version 4
```

**Comment by sezanzeb** [comment]
Yeah, I still need to add it to the deb file. Which distro are you using?

https://archlinux.org/packages/extra/x86_64/gtksourceview4/

https://packages.ubuntu.com/hirsute/libgtksourceview-4-0

https://packages.fedoraproject.org/pkgs/gtksourceview4/gtksourceview4/

**Comment by jonasBoss** [comment]
so far the editor looks good. There is one major design decision I would have made different:
### Is it a "advanced mode", or a macro editor? 
 - I don't think we should create a replacement for the normal interface, only as an extension. 
 - I think it should only be a macro editor. 
 - your sketches in https://github.com/sezanzeb/input-remapper/issues/109#issuecomment-932947522 go very much in this direction and I like them. They communicate very well that this is only a more convenient way to edit macros, and not a replacement to the whole interface.
 - we don't need to implement new features twice: for the normal and the advanced mode.
 - Users don't need to lean two different interfaces. There is only the normal mode, and a small button maybe inside the "mapping" field which brings up a macro editor for this particular mapping field.
 - Ideas how we could communicate that this is only a macro editor:
   - remove the "change key" and "delete" button
   - grey out the "new entry" row
   - give the macro editor a close button

### not so major things:
 - the "show advanced editor" always brings up the editor for the first row. I think it should bring up the editor for currently active row
 - ![image](https://user-images.githubusercontent.com/31804124/147988632-44daf677-c52a-4dd2-bddd-ba820d3bb571.png)
 - maybe give the completion dropdown a border or a different background color
 - Why are there numbers 1-5?

**Comment by sezanzeb** [comment]
How about

![image](https://user-images.githubusercontent.com/28510156/148131378-fa411c43-4e49-4126-a6e8-19ad98ac0782.png)

The branch is "popover-menu"

**Comment by sezanzeb** [comment]
for the autocompletion, there should probably be a custom solution and I don't think it will be hard to make one. I think I'll try in the evening

**Comment by jonasBoss** [comment]
what about this: 
![image](https://user-images.githubusercontent.com/31804124/148242741-147ad3f1-e41b-47b1-971d-a5b1a7901402.png)
![image](https://user-images.githubusercontent.com/31804124/148242871-a792cac4-7b02-4562-b10b-55bf05172e56.png)
https://github.com/jonasBoss/key-mapper/tree/macro_editor
the branch is not really working. 
Instead of bringing up the popover menu we switch to the new view which shows the code editor and `mapping_list_small`. 
The `mapping_list` and `mapping_list_small` show always the same except that the small one does not show the mapping.
This can be archived by managing all the mappings in a `Gio.ListModel` and binding it to both mapping lists.
The buttons confirm and abort will switch the UI back to the normal view.

**Comment by sezanzeb** [comment]
Would the key list be greyed out until Abort/Confirm is clicked?

I'm fine with extending the original editor instead of using two different editors.

But in this case I'd prefer any sort of popup instead of something that switches the user interface.

![image](https://user-images.githubusercontent.com/28510156/148254760-3cd39e23-4154-4b14-9f19-3632ddc192e2.png)

This or the popover are my favorites so far then

**Comment by sezanzeb** [comment]
I think I'd favor the popover because it is the least overwhelming way of editing things.

But if we need more space for extra menus we can switch to a popup like in my previous mockup.

**Comment by sezanzeb** [comment]
I also thought of only providing the "advanced editor" and replacing the old one completely. Then there is no switching around anymore (except when selecting a different key that is)

**Comment by sezanzeb** [comment]
@jose1711, I hope you don't mind that I'm pinging you sometimes.

Do you have an opinion about the proposed solutions?

**Comment by sezanzeb** [comment]
It won't really be possible to add autocompletion to the popover. So the popover could contain a button that leads to a bigger window, containing all sorts of fancy extra settings

![image](https://user-images.githubusercontent.com/28510156/148263270-4814bb4d-2c20-4e44-997b-17bbe5650609.png)

clicking advanced leads to https://github.com/sezanzeb/input-remapper/issues/109#issuecomment-1005888070

which would have lots of space for autocompletion

**Comment by jonasBoss** [comment]
> I also thought of only providing the "advanced editor" and replacing the old one completely. 

I think that is the best Solution. If we use a GtkNotebook we also have a good visual representation:
![image](https://user-images.githubusercontent.com/31804124/148277145-3074dd46-7e47-40b8-972f-b5c0db77966a.png)
And we don't nee to implement any logic for switching to different mappings GtkNotebook takes care of that

**Comment by sezanzeb** [comment]
This is how autocompletion could be made instead:

![image](https://user-images.githubusercontent.com/28510156/148288752-5ab4bdfb-8ddc-4b79-b3c8-deece61caee3.png)

**Comment by sezanzeb** [comment]
please try the `only-the-advanced-editor` branch

**Comment by jonasBoss** [comment]
My thoughts on the `only-the-advanced-editor` branch:
 - I think we should keep the highlighting as it is useful and kind of is the whole purpose of the macro editor.
 - I don't like the new "completion" dropdown it looks better, but it does not do anything. In the old one I could select an entry with the arrow keys and press return to have it complete my word. I used this feature a lot and I think it is more important than the look.
 - maybe when selecting the "new entry" row we can automatically start recording the new key

**Comment by sezanzeb** [comment]
You can click on the autocompletion entry. I'll add arrow and enter key support

**Comment by sezanzeb** [comment]
It is now possible to navigate in the autocompletion with arrow keys, select an entry via enter and close it with esc

**Comment by jose1711** [comment]
> @jose1711, I hope you don't mind that I'm pinging you sometimes.

No, I don't mind that at all. Sadly, my schedule is tight so I sometimes don't react in a reasonable amount of time.

> Do you have an opinion about the proposed solutions?

I checked out `only-the-advanced-editor` branch and overall I like the idea of multi-line editor (that's the main idea anyway, right? make code more readable and easier to change). If it opens right away or there's a click needed - I don't really care as long as it's there. Perhaps less experienced users might feel intimidated though if there's a big white area where they're supposed to write some.. code (?). But I am not an UX expert so..

Line numbering and comments suport - great idea, autocompletion - OK but what I would really welcome is to see the names of the functions available right above/below the text area. Maybe even put them into a tree menu (keyboard, mouse, conditionals, variables..) to make them more accessible. Also if the autocompletion gives me a hint about the arguments (like e. g. MS Excel does for its functions) it would absolutely rock - but perhaps this is not possible with GTK.

Also it would be nice as the code is being checked for syntax as-you-type. This assumes that the number of characters in the text area is limited though.

Not sure what your plans about (not)wrapping lines is but at this moment when the text exceeds right margin there is no scroll bar.

**Comment by sezanzeb** [comment]
Great, thank!

> but perhaps this is not possible with GTK.

At this point this is not an issue with GTK anymore. The custom Autocompletion class we have now can easily be extend with whatever we want

**Comment by sezanzeb** [comment]
> Perhaps less experienced users might feel intimidated though if there's a big white area where they're supposed to write some.. code (?)

It starts small now and adds line numbers once it gets multiline

![image](https://user-images.githubusercontent.com/28510156/148430012-746a4f2f-9fb5-43c5-a10c-8f9e055c6660.png)

![image](https://user-images.githubusercontent.com/28510156/148430060-de58fdf7-7e57-49f1-a79c-86e42865ec9f.png)

**Comment by sezanzeb** [comment]
If there is no objection anymore I'll start writing tests now

**Comment by jonasBoss** [comment]
I just had a look at the `only-the-advanced-editor` branch it looks very good so so far.
Only a few minor thins:
![image](https://user-images.githubusercontent.com/31804124/148595674-d66931ec-6044-45d8-8e0f-304e4df017f4.png)

No syntax highlighting?
![image](https://user-images.githubusercontent.com/31804124/148595779-d5fadd10-ec4b-47a5-809f-124f17b480fc.png)

**Comment by sezanzeb** [comment]
thanks

the syntax highlighting is off because there is no highlighting mode that works really well for the syntax. It used python, but it does put highlights at the wrong places.

I removed the border to be consistent with the other buttons on the left half of the UI. Maybe I should also remove it for "Change Key".

The `Gtk.TextView` (and `Gtk.SourceView` that uses it under the hood) don't support default text.

**Comment by jonasBoss** [comment]
I like it so far, I am not sure about having no borders for all the buttons, but as long as it is consistent, I don't mind it.
What do you think about about a header for the mapping list?: 
![image](https://user-images.githubusercontent.com/31804124/148681403-e664e1d8-bbf1-4a07-a19a-02776e9328fa.png)

**Comment by sezanzeb** [comment]
I'd rather have it without the heading tbh

I finished adjusting all old tests, added a few new tests and would be ready to push it to main now

Before that I'll make a release that contains the renames from last week
