### ISSUE TITLE
Rename to "keycode-mapper"?

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#218]
This title would be more accurate

existing build configurations from the AUR and .deb files can be configured to replace "key-mapper" with "keycode-mapper".

**Comment by sezanzeb** [comment]
apparently this wouldn't cause too much trouble: https://github.blog/2013-05-16-repository-redirects-are-here/

**Comment by KristerV** [comment]
Supporting this.

I'm looking into remapping for the first time and I had no idea key-mapper-git was not the same thing as key-mapper, only found this much later.

**Comment by sezanzeb** [comment]
`key-mapper-git` would be the AUR entry for this project

**Comment by KristerV** [comment]
I'll elaborate my confusion. So searching for packages the top has this

![image](https://user-images.githubusercontent.com/2750622/145966115-4205b8a0-6a31-4cae-b484-59864283d419.png)

so [keymapper](https://github.com/houmain/keymapper) is the wayland incompatible package and key-mapper-git is this repo. Would be great if they actually had different names so at a glance it's understood that they are in fact different repos completely.

**Comment by sezanzeb** [comment]
ah without a dash. Makes sense. Thanks for your input

**Comment by sezanzeb** [comment]
@skitt would there be downsides for the debian package if this is renamed?

**Comment by skitt** [comment]
> @skitt would there be downsides for the debian package if this is renamed?

None that I can think of — and if the module is renamed too, that would address [the conflict with the `keymapper` package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995165)!

**Comment by sezanzeb** [comment]
Thank you so much for the very fast response. Sounds like there are only benefits so far

**Comment by jonasBoss** [comment]
Looking at the example @KristerV  provided it looks like a good idea to rename the project. But I think there is more to consider:
- Visibility: currently all search results for "keymapper/key-mapper/key mapper linux" will all point to this project or an article about it.
- "keycode-mapper" is accurate and descriptive but rather technical I would not search for the term keycode-mapper if I wanted a tool to remap some buttons. In fact it took me very long to find this project because I was always searching for remapping or a remapper.
- considering future developments: if we manage to implement the features described here: https://github.com/sezanzeb/key-mapper/discussions/227 we should consider something more general like "Input Remapper"

**Comment by jose1711** [comment]
> * "keycode-mapper" is accurate and descriptive

Hmm.. not sure if it's accurate in all cases as you may still use it to remap just mouse buttons which do not produce any keycodes (but X events).

**Comment by sezanzeb** [comment]
> currently all search results for "keymapper/key-mapper/key mapper linux" will all point to this project or an article about it.

https://github.com/sezanzeb/key-mapper/ will redirect to https://github.com/sezanzeb/keycode-mapper/ (or whatever I'll rename it to), is this still problematic?

> "Input Remapper"

Sounds good as well.

> Hmm.. not sure if it's accurate in all cases as you may still use it to remap just mouse buttons which do not produce any keycodes (but X events).

mouse buttons are also key events that arrive with an identifying unique code, but good point. We can already map joysticks to keys, and keys to mouse movements. `Input Remapper` would work in that context probably. "Input" could refer to arbitrary input events, which seems accurate.

**Comment by sezanzeb** [comment]
If everyone thinks that `Input Remapper` would work better than `Keycode Mapper` (and `Key Mapper`)

**Comment by jonasBoss** [comment]
yes I think `Input Remapper` is the better option.

**Comment by KristerV** [comment]
`Input Remapper` makes most sense to me. Remapper is the keyword i was searching for when i needed this, because whatever forum suggested "any key remapper". But overall `Input Remapper` gives most clarity in my opinion considering what it does and what already exists out there.

**Comment by mattzab** [comment]
I'm using this exclusively to remap a mouse button to a script (or another key combination that I've mapped with Gnome Keyboard Shortcut settings)
I prefer Input Remapper. That coincides with the logo already, as well.

**Comment by sezanzeb** [comment]
See https://github.com/sezanzeb/key-mapper/pull/239

**Comment by sezanzeb** [comment]
I'll do the rename on Friday to "Input Remapper", deadline for interventions

**Comment by sezanzeb** [comment]
@skitt the python package is renamed as well. I don't think there will be a conflict in the ubuntu repo for the new name anymore

**Comment by skitt** [comment]
> @skitt the python package is renamed as well. I don't think there will be a conflict in the ubuntu repo for the new name anymore

I saw that, thanks @sezanzeb! I’m looking forward to the next release ;-).

**Comment by sezanzeb** [comment]
@skitt it is released as 1.3.0.

There are quite some more changes coming up that will be put into 1.4.0 by the way, the overhaul of the user interface is already on main but not yet in included a release
