### ISSUE TITLE
Python sources for key-mapper deleted during Fedora upgrade 34 -> 35

### ISSUE THREAD

**Issue by byron-hawkins** [sezanzeb/input-remapper#225]
After upgrading my Fedora from 34 to 35 using the standard `dnf` procedure, all the python files for `key-mapper` have been deleted. I've used `locate` and `find` all over the system and cannot find them anywhere. My configuration fortunately has not been deleted. What's the easiest workaround here, without losing my configuration?

**Comment by sezanzeb** [comment]
The config will survive installing key-mapper again. Empty files are only created if they are missing completely

I'm installing it all the time after tiny changes and it never got lost

**Comment by byron-hawkins** [comment]
Thanks, that works. However, the autoload feature is never working on this machine, though it works on other Fedora machines in my network. When I open `key-mapper-gtk`, the autoload preset is always there, but if I don't click on the `apply` button then it doesn't get enabled. Any suggestions what I might look for, to find where the autoload is getting dropped during service start?

**Comment by sezanzeb** [comment]
does `key-mapper-control --command autoload` enable your preset?

**Comment by sezanzeb** [comment]
I'll close this due to the old age of the issue. if you are still facing issues, feel free to create a new one
