### ISSUE TITLE
Key-Mapper

### ISSUE THREAD

**Issue by DarkMustang** [sezanzeb/input-remapper#268]
I have the Key-Mapper 1.2.1 10700db which allows me to remap a keyboard key to the right mouse button. This is what I need on my laptop, since there is no right button on the mouse pad, but I only could download the 1.3.0 5cd015f version, and I can't figure out how to make a remap a keyboard key to the right mouse button. I also like the way the earlier version gave you a selection to pick from.
So with this version, how do I map a keyboard key to use the right mouse button?

My email is dark_-moon@outlook.com

Thanks

**Comment by jonasBoss** [comment]
Input-remapper now has predefined devices to which keys can map. For mapping mouse buttons select the "mouse" device in the drop-down menu. 

There is still the selection, but it is filtered depending on the selected device
![image](https://user-images.githubusercontent.com/31804124/150036583-69729416-c2d6-4b5b-b19e-86073d7436b8.png)

**Comment by DarkMustang** [comment]
Okay, thanks. That woked.
________________________________
