### ISSUE TITLE
Add python3-devel requirement to installation instructions for pip

### ISSUE THREAD

**Issue by hanscje** [sezanzeb/input-remapper#269]
I followed the pip installation instructions, but it did not install until I installed python3-devel. Installing on new install of fedora35. Was a bit hassle figuring out the issue, so would be nice if you could add python3-devel as req for pip installation (and pip for the new to linux people). Great software though! Thanks for making it! makes my gaming keyboard and pad usable :+1:

**Comment by sezanzeb** [comment]
have added it to the readme, thanks
