### ISSUE TITLE
keys get stuck when profile is changed while being held

### ISSUE THREAD

**Issue by DreadPirateLynx** [sezanzeb/input-remapper#296]
After getting my input-remapper-manager working, I quickly ran into a problem: anything making use of h() or m() never completes if the profile changes while the key is being held down. This is causing keys to get stuck and devices to act unpredictably.

**Comment by jonasBoss** [comment]
yeah should I will note it in my Todo

**Comment by sezanzeb** [comment]
nice. I'll avoid doing those fixes on main for the old system redundantly then. Looking forward to the end result!

**Comment by jonasBoss** [comment]
fixed by the reset method in mapping handlers
