### ISSUE TITLE
Disable/Grey-out buttons that can (currently) not be used

### ISSUE THREAD

**Issue by hoijui** [sezanzeb/input-remapper#297]
Please install the newest version from source to see if the problem has already been solved.

```
input-remapper 1.4.0 abbbefc7a22653c65a31344144352afc2d3744a7 https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
```

It seems that adding new mappings is not possible as long as the injection is active. it would be nice if there was a GUI indication of this, preferable, the buttons/fields related to it would be greyed out, with a tool-tip/pop-up saying, that mappings can not be changes as long as the injection is active.
being able to click on a button that does nothing in turn, is confusing.

thank you for this tool! it is functionally very nice! :-)

**Comment by sezanzeb** [comment]
Yes, you are right. Thanks for pointing it out!
