### ISSUE TITLE
Control L + Left as Home not working

### ISSUE THREAD

**Issue by sasaandonov** [sezanzeb/input-remapper#303]
When i set Control L(left ctrl) + Left(Left Arrow) as Home, i actually get Control L + Home, so in text editor(gedit on ubuntu 20.04 or vscode) when I press Control L + Left, cursor jump on beginning of the file instead of beginning of the line. Its look like Control L did not released and Home come together with it.
https://prnt.sc/26xubtm

**Comment by sezanzeb** [comment]
See https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#combinations

A macro to circumvent the issue is on the todo list

related to https://github.com/sezanzeb/input-remapper/issues/299
