### ISSUE TITLE
Feature: Compatability with Karabiner-Elements?

### ISSUE THREAD

**Issue by im-AMS** [sezanzeb/input-remapper#307]
[Karabiner Elements](https://karabiner-elements.pqrs.org/) is the best software out there to map all sorts of key combinations. Unfortunately its Mac exclusive.

Thanks to you there is a simpler app on linux.

But is there a way that this project can use the syntax(JSON Configs of Karabiner)?
If its possible, then all the plugins(key maps from community, which is quite a lot) is available for linux too.

**Comment by jonasBoss** [comment]
From looking through the the [Karabiner Configuration Reference Manual](https://karabiner-elements.pqrs.org/docs/json/) I am pretty certain that no, we can not support their syntax in the configuration files. 

Inputremapper has implicit configurations which are informed by internal workings of Inputremapper. While Karabiner is very explicit in the config files, which either means they do a lot of internal processing to make the config that explicit or they have a fundamentally different architecture.

**Comment by sezanzeb** [comment]
A lot of the stuff in karabiner is done with macros in input-remapper, and correctly converting all the possible configuration properties to our macro code would be very difficult
