### ISSUE TITLE
Quotation Marks

### ISSUE THREAD

**Issue by MatheusFerreiraL** [sezanzeb/input-remapper#308]
Hey, first off all I get say, this remapper is saving me, thanks a lot for it! 
So, I'm having a problem with the quotation marks <"> because I could not find it! Is it available and I just missed it or its really not there? It's one of the important keys for me, if you could help me (more) with this I'll be really grateful!

**Comment by jonasBoss** [comment]
If you press a combination on your keyboard to get `"`, you want to also make Inputremapper press that combination: `Shift_L+2` would be the correct mapping on a German keyboard it depends on the keyboard-layout your system expects.

**Comment by MatheusFerreiraL** [comment]
My keyboard layout is ABNT2, the common in Brazil, so there is a key specially for the `"` , witch is making it difficult to set. Is it possible to use the code on ascii (code 34, [Ascii table](https://web.fe.up.pt/~ee96100/projecto/Tabela%20ascii.htm)) for the quotation mark? (As you can see on the image, the `"`  is located on the upper left side). I tried to config `Shift_L + apostrophe` but got as response `^`.

![ABNT Keyboard](https://user-images.githubusercontent.com/95404404/154850606-d9d83d55-2a95-4157-9b5a-dc59a95b3fdc.png)

**Comment by jonasBoss** [comment]
you can run `$ sudo evtest`, select your keyboard, and than press the `"` key.
You should see something like this:
```
Event: time 1645371848.138784, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70007
Event: time 1645371848.138784, type 1 (EV_KEY), code 32 (KEY_D), value 1
Event: time 1645371848.138784, -------------- SYN_REPORT ------------
Event: time 1645371848.197765, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70007
Event: time 1645371848.197765, type 1 (EV_KEY), code 32 (KEY_D), value 0
Event: time 1645371848.197765, -------------- SYN_REPORT ------------
```

That tells you exactly which events your keyboard generated. In my case I pressed `d` which generated the `type 1 (EV_KEY), code 32 (KEY_D), value 1` event. The `EV_MSC` events are usually safe to ignore.

Inputremapper uses the names from [linux/input_event_codes.h](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h)

**Comment by MatheusFerreiraL** [comment]
Thats just perfect, thanks a lot man !
