### ISSUE TITLE
Complex remaps with capslock key?

### ISSUE THREAD

**Issue by AMS-2000** [sezanzeb/input-remapper#309]
How can I map these combinations?

I have looked at the other comments of similar, cant quite figure this out.

- just Capslock pressed and released = Escape
- Holding Capslock key = holding Shift+Control+Meta+Alt  aka Hyper

The idea behind that is, I would like to map Hyper+T for terminal(On gnome) or Hyper+F for Firefox etc

**Comment by sezanzeb** [comment]
maybe something like

```py
if_tap(
  key(KEY_ESC),  # just capslock pressed and released
  modify(  # holding it for longer than 300 ms
    KEY_LEFTSHIFT,
    modify(
      KEY_LEFTCTRL,
      modify(
        ...,
        hold()
      )
    )
  ),
  300
)
```

**Comment by AMS-2000** [comment]
May be I should have told about my whole mapping.

- just Capslock pressed and released = Escape
- Holding Capslock key = holding Shift+Control+Meta+Alt aka Hyper
- Capslock + j = down arrow (if i hold Capslock+j, it needs to keep pressing down arrow)
- Capslock + k = down up, similarly for h and k
-  Capslock + Left = Control + Left
- Capslock + Right = Control + Right

The issue with the above is, I cannot just hold the other combination of keys to keep repeating until release. In the above snippet, I need to release the capslock key and press it again to key repeat.

Here is what I tried.
The other mappings work, but Capslock as Esc and Hyper if held, dosent work, its behaving as regular capslock.
I also tried replacing `if_tap` with `if_single`, no luck.
```
if_tap(
  key(KEY_ESC),
  modify(
    KEY_LEFTSHIFT,
    modify(
      KEY_LEFTCTRL,
      modify(
        KEY_LEFTMETA
        # hold()
      )
    )
  )
)
```

**Comment by sezanzeb** [comment]
why does it say `# hold()`?

**Comment by AMS-2000** [comment]
My bad, it was a comment, i forgot to remove it before I pasted it here. nevertheless I tried it with and without hold(), it still dosent work.

**Comment by sezanzeb** [comment]
If I hold caps and press j it goes down a line. But holding it won't repeat it and repeated presses don't work. This is your problem, right?

Make a new preset and only map `caps + j` to `KEY_DOWN`

Now press `caps`, `j`, hold it and then press `control` and `alt`. The cursor stops going down, and releasing `control` and `alt` will not make it continue going down.

`control` and `alt` are injected because of your `if_single` macro, wich triggers when pressing `j`.

**Comment by sezanzeb** [comment]
there is currently no way exclude `j` from the detection of `if_single`, except with variables. But it will get a lot more complicated:

caps + j maps to:

```py
set(ignore_if_single, 1).
hold(KEY_DOWN).
set(ignore_if_single, 0)
```

caps maps to:

```py
set(ignore_if_single, 0).
if_single(
  key(KEY_ESC),
  wait(10).  # wait to make sure caps + j has set it to 1 if needed
  if_eq(
    $ignore_if_single,
    0,
    key(a).modify(
      KEY_LEFTSHIFT,
      modify(
        KEY_LEFTCTRL,
        modify(
          KEY_LEFTMETA,
          hold(KEY_LEFTALT)
        )
      )
    )
  )
)
```

**Comment by sezanzeb** [comment]
and install from the latest main please, there was an issue that needed fixing that will prevent the above from working
