### ISSUE TITLE
Can't remap PS/2 to USB adapted keyboard. 

### ISSUE THREAD

**Issue by jlnxr** [sezanzeb/input-remapper#311]
I recently picked up an old retro keyboard (IBM Model M) that requires a PS/2 to USB adapter to connect to my computer. Debian recognizes the keyboard and it works just fine. However, input-remapper, which has been my go to for remapping things, sees the keyboard ("AT Translated Set 2 keyboard") but doesn't allow anything to be remapped. The keyboard/mouse/gamepad drop down is greyed out as is the "Set the key first" text box. Running via terminal does not yield any helpful error messages or any explanation why I can't remap the keyboard even though the OS is using it just fine (typing on it right now). input-remapper itself is also working just fine at remapping my mouse buttons, and the buttons on my other (modern USB) keyboard, but not this one. 

OS: Debian Bullseye amd64, Gnome 3.38 on X
input-remapper: 1.4 
Device: IBM Model M keyboard with PS/2 to USB converter

**Comment by jonasBoss** [comment]
If you press the "Change Key" button and then press a key, does the "new entry" in the middle change to whatever key you pressed?

**Comment by jlnxr** [comment]
Negative, when I hit "change key" and then hit a key. nothing at all changes, including the "new entry". It's as if the board didn't work at all, only it works everywhere else....

**Comment by jlnxr** [comment]
Problem solved, I noticed a "barcode reader" also appeared in my list of inputs, and apparent that is actually the keyboard :|
