### ISSUE TITLE
Unable to work with input-remapper-control when a preset has Auto Load

### ISSUE THREAD

**Issue by Zorrototo** [sezanzeb/input-remapper#322]
I was trying to make bash scripts to load different preset for my mouse, but it wasn't working, for example I have two presets for my mouse G400S, one called Default, the other one called Games, and when I was doing that

```
sudo /usr/bin/input-remapper-control --command stop --device "Logitech G400s Optical Gaming Mouse"
sudo /usr/bin/input-remapper-control --command start --device "Logitech G400s Optical Gaming Mouse" --preset "Games"
```

It wasn't applying the preset. After hours of trying to troubleshoot, I figured it was loading the Default preset instead of the Games presets.

I disabled Auto Load for the Default preset in the GUI, and now the commands work as intended from terminal.

Maybe it is the intended behavior but I wouldn't think so as I specifically try to load another preset than the one with Auto Load enabled from the GUI

**Comment by sezanzeb** [comment]
> Maybe it is the intended behavior

certainly not, thanks for reporting!

**Comment by Zorrototo** [comment]
>  thanks for reporting!

Thanks for making this amazing tool, I was using a combination of `evrouter` and `imwheel` for years to basically achieve the same thing, and after bothering people on the Manjaro forum to help me have `evrouter` build again (it is unmaintained for MANY years now) I found this tool to help someone else for another unrelated issue xD. 

Also, a little bit off-topic but I don't know how to ask otherwise, this tool is said to be "Formerly Key Mapper", but I see Key Mapper is still under development and from another developer. Can you give me more info about the history of this project?

**Comment by sezanzeb** [comment]
> but I see Key Mapper is still under development and from another developer

might be a fork or an entirely different project.

It was just the name that changed, because there was a conflict with a python package of the same name and because I was told that input-remapper is a better name. Some more info is available here: https://github.com/sezanzeb/input-remapper/issues/248

That's basically it, there isn't much more history other than a history of added features and changed architectures.

**Comment by sezanzeb** [comment]
Ah interesting. This is something slightly different

should be fixed now

**Comment by Zorrototo** [comment]
Thanks :+1:
