### ISSUE TITLE
Auto load conflicts and profiles not being applied consistently

### ISSUE THREAD

**Issue by lucidph3nx** [sezanzeb/input-remapper#338]
I've been trying to use bash scripts to run before and after launching a game. I found that profiles were not being applied or were being applied inconsistently, sometimes the autoload profile would be applied instead and sometimes no profile would be applied.

After some time troubleshooting, I found that disabling autoload profiles solved some of my issues. as mentioned in the now closed issue here #322 
In addition to this, I found that often commands wouldn't finish before the next one would be processed, leading to profiles not being correctly applied, my solution was to add a hacky `sleep 1` into the bash script as you can see below:
```
input-remapper-control --command stop --device "Razer Basilisk Ultimate"
sleep 1
input-remapper-control --command start --device "Razer Basilisk Ultimate" --preset "apex-legends"
```
This allowed the previous profile to be fully unloaded before the next was applied and works much more consistently.
I'm pretty unfamiliar with bash scripts (and Linux, my background is in webdev) and as such, I'm not sure quite what is going on, but hopefully this points you in the right direction to solve the issue and provides insight to anyone else trying to do the same as me.

**Comment by sezanzeb** [comment]
The first command will cause the service to send a command to the injection via a pipe in a "fire and forget" kind of way. So it is plausible that the injection is not stopped right after running the command. It should be possible to make the function in the service wait for the result.

As for the problem with autoload. Have you installed the .deb file or from the latest source?

**Comment by lucidph3nx** [comment]
Ah good point, I've installed from the .deb release, I assumed this was up to date, I'll install from source and retest. Apologies and thanks.

I get that it seems to apply asynchronously without waiting and for most cases this is probably a good thing. Some kind of `--wait` flag would probably suffice or some kind of wait behaviour for the terminal command.
Probably a more ideal solution though would be for applying a new profile to stop and replace the previous for that device? That's certainly what I expected when I started to script this stuff. Is there some reason two commands might be necessary?

**Comment by sezanzeb** [comment]
> Probably a more ideal solution though would be for applying a new profile to stop and replace the previous for that device? That's certainly what I expected when I started to script this stuff. Is there some reason two commands might be necessary?

This is is supposed to happen already: https://github.com/sezanzeb/input-remapper/blob/main/inputremapper/daemon.py#L451

If not, then it is a bug

**Comment by lucidph3nx** [comment]
Might be a bug, my original script was just to apply the profile but this was not working (or at least not consistently) so I found it necessary to stop first.

I'll retest when I get back to my machine and let you know. I'll also take a look at the code, I didn't realise when I first posted that it was mostly Python so hopefully I can get my head around what it's doing. Thanks again 🙂

**Comment by lucidph3nx** [comment]
I've done some testing with the latest version from source. The issues with auto load is gone and I haven't been able to replicate the issues I was having with profiles needing to be stopped before starting a new one, My problems must have been related to the auto load issue and I didn't separate the two problems in my mind before applying my workaround.

Sorry to waste your time, recommend you release a new .deb version since this is a fairly huge usability upgrade.

I'll close the issue now 🙂

Before I go though, I just want to thank you for this fantastic piece of software, I've recently switched from a dual boot system to full time Linux and this software has massively helped my transition and replaced a lot of bloated crappy Razer software that's plagued my windows install for as long as I can remember. Keep up the good work!

**Comment by sezanzeb** [comment]
you are welcome! I'll make a new release soon
