### ISSUE TITLE
Trigger an action if the key is PRESSED only

### ISSUE THREAD

**Issue by JeffersonTeixeira** [sezanzeb/input-remapper#348]
I would like to type the letter 'f' if my mouse button RIGHT is press for 500ms+

if I'm pressed this key, then an input would type multiples f: fffffffffffffffffffffffffffff...

**Comment by sezanzeb** [comment]
```
if_tap(
  else=key(f),
  timeout=500
)

**Comment by JeffersonTeixeira** [comment]
I'm trying to use it in a game, when I need to keep F pressed to select an item and click in somewhere in the screen.
When I keep the right button pressed, it works perfectly (f being pressed) but when I click with left button it stops. Is there a way to keep it pressed and only stop when I release the right button? 
P.S: I must work while i'm pressed, if I stop, it should stop, because I use the right button click to another things

**Comment by JeffersonTeixeira** [comment]
> This should do the trick:
> 
> ```cs
> if_tap(
>   else=key(f),
>   timeout=500
> )
> ```

I'm trying to use it in a game, when I need to keep F pressed to select an item and click in somewhere in the screen.
When I keep the right button pressed, it works perfectly (f being pressed) but when I click with left button it stops. Is there a way to keep it pressed and only stop when I release the right button? 
P.S: I must work while i'm pressed, if I stop, it should stop, because I use the right button click to another things

**Comment by sezanzeb** [comment]
```
if_tap(
  else=hold(f),
  timeout=500
)
```
