### ISSUE TITLE
Backtick, dead acute, gravis - with a single hit

### ISSUE THREAD

**Issue by KoljaL** [sezanzeb/input-remapper#353]
For writing markdown the backtick `` ` `` is very important.
To insert it (on Linux Mint, german Keyboard), i have to press: `` ctr +  ` `` and then `space`.

I tried to map it on a single `` ` ``-hit:
Key: `dead acute` (works with other mappings)
Mapping: `Control_L + dead acute, space`

But it does not work at all.
What is the correct way?

**Comment by jonasBoss** [comment]
are you sure it is not `Shift_L`? Try this:
```
modify(Shift_L, key(dead_acute)).key(KEY_SPACE)
```

**Comment by sezanzeb** [comment]
Also, you can't write a comma there. You can only use `+`

**Comment by KoljaL** [comment]
Of course `Shift_L` and thanks a lot, your mapping works :-)
