### ISSUE TITLE
Binding mouse left click gives "This would disable your click button"

### ISSUE THREAD

**Issue by git-iso** [sezanzeb/input-remapper#357]
I want to make a macro such that, when the left mouse button is held down, the mouse moves left and right repeatedly. However when I try to make the macro I get the error message "This would disable your click button". Is there a way to keep the normal single mouse click while still using the hold macro?

**Comment by sezanzeb** [comment]
If your mouse has more buttons, I'd recommend mapping BTN_LEFT to any of them to make sure you have access to it if your macro goes wrong.

If you map your left mouse button and you can't click anymore, you might have a difficult time gaining control over your computer. In any case, unplugging the mouse and plugging it back in should stop the injection though.

As for your exact use-case, I'm too busy so I can't give you detailed advice about what kind of macro you should use for what you are trying to do.

**Comment by sezanzeb** [comment]
clicking "Apply" a second time should overwrite the warning message and force-apply the preset

**Comment by jonasBoss** [comment]
you probably want to use the [if_tap](https://github.com/sezanzeb/input-remapper/blob/main/readme/macros.md#if_tap) macro with a timeout:
`if_tap(then=BTN_LEFT, else=<the mouse movement macro>)`
I am not sure how you would go about the mouse macro.

**Comment by git-iso** [comment]
Thank you guys for the assistance! I made the macro as
`if_tap(then=key(BTN_LEFT), else=
hold(
e(EV_REL, REL_X, 100).
e(EV_REL, REL_X, -100)),
timeout=100)`
and it seems to work fine. I didn't know you could force past the apply screen by clicking it again.
