### ISSUE TITLE
Allow mapping mouse drag lock

### ISSUE THREAD

**Issue by thiagoa** [sezanzeb/input-remapper#383]
It looks like there's no way to map a drag lock function. This is especially useful on trackballs; in my case, it would be perfect if I could map the top two buttons to the drag lock function. Are there plans to implement this feature?

**Comment by jonasBoss** [comment]
I am not sure what the "drag lock function" is. What is the behavior you try to archive?
Am I guessing correctly that you want to grab a file or item with a push of a button than drag it somewhere, and drop it there by pressing the button again?

there is a feature request for this: #378

**Comment by sezanzeb** [comment]
I guess you mean to inject a key-down event on the first press, and a key-up event on the second press?

In that case

```
if_eq(
    $a,
    1,
    event(EV_KEY, BTN_LEFT, 0).set(a, 0),
    event(EV_KEY, BTN_LEFT, 1).set(a, 1)
)
```

**Comment by thiagoa** [comment]
@sezanzeb That's exactly what I needed!

Thank you so much folks, I'm closing this issue.
