### ISSUE TITLE
create "beta" AUR package

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#389]

**Comment by sezanzeb** [comment]
@jonasBoss https://aur.archlinux.org/packages/input-remapper-beta-git

**Comment by sezanzeb** [comment]
added to readme: https://github.com/sezanzeb/input-remapper#beta

**Comment by jonasBoss** [comment]
It might be sensible to change the Upstream URL for the AUR to https://github.com/sezanzeb/input-remapper/tree/beta
