### ISSUE TITLE
Github Actions not installing data correctly

### ISSUE THREAD

**Issue by jonasBoss** [sezanzeb/input-remapper#404]
I had a few CI runs fail with `exit code 10: Could not find the application data` (`data.get_data_path()`).

The workflow seems to install all the data files to `/usr/local/lib/python3.8/dist-packages/usr/share/input-remapper/` as you can see [here](https://github.com/sezanzeb/input-remapper/runs/6469098312) at the end of the "install dependencies" section. 

This probably effects all branches but we had previously no tests which needed the data files.

I have currently implemented a workaround: https://github.com/sezanzeb/input-remapper/pull/375/commits/0c2f59b713c1e2ac843a24b3e6b7b993d6e19780

**Comment by jonasBoss** [comment]
`test.yml` line 23 seems to cause the trouble.
If I run `sudo pip install .` inside my local git repo on my system it installs stuff to `/usr/lib/python3.10/site-packages/usr/share/input-remapper/`

Possibly a problem with the https://github.com/sezanzeb/input-remapper#manual installation.

**Comment by jonasBoss** [comment]
using `sudo pip install --no-binary :all: .` resolves this issue.

**Comment by sezanzeb** [comment]
yeah, this is somewhat of a known problem, see https://stackoverflow.com/questions/40588634/how-to-install-data-files-to-absolute-path/46087545#46087545
