### ISSUE TITLE
when installed on Librem5(PureOS) pulseaudio does not load

### ISSUE THREAD

**Issue by chri2** [sezanzeb/input-remapper#410]
PureOS is basically a Debian without blobs.

When 99-input-remapper.rules is active the pulseaudio server of the default user 'purism' cannot be loaded, because it doesn't find any soundcards.

The Librem5 got the following two soundcards:

```
root@pureos:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: L5 [Librem 5], device 0: 308b0000.sai-wm8962 wm8962-0 [308b0000.sai-wm8962 wm8962-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Modem [Modem], device 0: 30030000.sai-bm818 bm818-0 [30030000.sai-bm818 bm818-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Attached you can find a list of all the inputs available (including an external keyboard/mouse via usb attached).

[l5-inputs.txt](https://github.com/sezanzeb/input-remapper/files/8773716/l5-inputs.txt)

```input-remapper-control --list-devices ``` shows:

```
root@pureos:~# input-remapper-control --list-devices
Starting logging to "/var/log/input-remapper-control"
Wireless Keyboard/Mouse
EP0700M09
30370000.snvs:snvs-powerkey
gpio-keys
```

**Comment by sezanzeb** [comment]
wow, that's weird. Maybe we can add `ID_TYPE=="hid"` to the evdev rule. But I first need to try out a few more devices to see if they all have this `ID_TYPE`. I'll do that later.

**Comment by sezanzeb** [comment]
Here with the xbox 360 controller and a wacom tablet:

[inputs.txt](https://github.com/sezanzeb/input-remapper/files/8791243/inputs.txt)

The controller has `ID_TYPE=generic` unfortunately.

Maybe using `ID_PATH!="platform-sound"` in the rule does the trick already. I'll try that soon on my computer if stuff still works.

```
ACTION=="add", SUBSYSTEM=="input", ID_PATH!="platform-sound", RUN+="/bin/input-remapper-control --command autoload --device $env{DEVNAME}"
```

**Comment by sezanzeb** [comment]
Please try out the `pulseaudio-broken` branch:

```bash
git clone https://github.com/sezanzeb/input-remapper.git
cd input-remapper
git checkout pulseaudio-broken
./scripts/build.sh
sudo apt install ./dist/input-remapper-1.4.2.deb
```

If that works I'll push it to main and also make a new release
