### ISSUE TITLE
Leaking REL_WHEEL_HI_RES events

### ISSUE THREAD

**Issue by pviscone** [sezanzeb/input-remapper#411]
I'm used to mapping the side button + wheel to the global shortcuts of VLC to go forward/backward.

The problem is that the wheel continues to work also if the side button of the mouse is held.
This is very uncomfortable because, depending on where the cursor is, it starts scrolling.

Is there a way to disable the mouse when a key combination is executed?

**Comment by 2xlink** [comment]
I have this issue as well. My system information:

```
➜  ~ input-remapper-control --version
input-remapper 1.4.0  https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
```
```
➜  ~ echo $XDG_SESSION_TYPE
x11
```
```
➜  ~ cat ~/.config/input-remapper/config.json
{
    "autoload": {
        "Logitech Advanced Corded Mouse M500s": "Kova"
    },
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "none",
            "right_purpose": "none",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5
        }
    },
    "version": "1.4.0"
}⏎                                                                                             
```
```
➜  ~ plasmashell --version
plasmashell 5.24.4
```

Maybe this is an issue with KDE plasma?

**Comment by 2xlink** [comment]
I did some testing with `evtest`. It seems that scroll wheel inputs (as well as combinations with the scroll wheel) are incorrectly sent by the forwarded device.

**Comment by sezanzeb** [comment]
Please post your preset configs, located in `~/.config/input-remapper/presets/`

**Comment by pviscone** [comment]
I am also running KDE on X11

***

`
cat ~/.config/input-remapper/presets/Logitech Gaming Mouse G502/new\ preset\ 2.json
`


```json                                  
{
    "mapping": {
        "1,275,1+1,274,1": [
            "Control_L+period",
            "keyboard"
        ],
        "1,275,1+2,6,1": [
            "Control_R+Prior",
            "keyboard"
        ],
        "1,275,1+2,6,-1": [
            "Control_R+Next",
            "keyboard"
        ],
        "1,275,1+2,8,1": [
            "Control_R+minus",
            "keyboard"
        ],
        "1,275,1+2,8,-1": [
            "Control_R+comma",
            "keyboard"
        ]
    }
}
```

***

`
➜  ~ cat ~/.config/input-remapper/config.json
`
```json
{
    "version": "1.4.2",
    "autoload": {},
    "macros": {
        "keystroke_sleep_ms": 10
    },
    "gamepad": {
        "joystick": {
            "non_linearity": 4,
            "pointer_speed": 80,
            "left_purpose": "none",
            "right_purpose": "none",
            "x_scroll_speed": 2,
            "y_scroll_speed": 0.5
        }
    }
}
```

**Comment by sezanzeb** [comment]
This is my configuration:

```
{
    "mapping": {
        "1,276,1+2,8,1": [
            "a",
            "keyboard"
        ],
        "1,276,1+2,8,-1": [
            "b",
            "keyboard"
        ]
    }
}
```

Which behaves in the following way for me:
- using the scroll wheel: scrolls
- pressing "extra" and scrolling up: a (no scrolling happens)
- pressing "extra" and scrolling down: b (no scrolling happens)
- just pressing "extra": nothing happens

So this is different for you?

**Comment by sezanzeb** [comment]
> I did some testing with `evtest`. It seems that scroll wheel inputs (as well as combinations with the scroll wheel) are incorrectly sent by the forwarded device.

I just checked evtest as well and the "forwarded" device is sending `REL_WHEEL_HI_RES` events. This is broken

**Comment by jonasBoss** [comment]
seems to be related to this: https://github.com/sezanzeb/input-remapper/issues/354 just the other way around. In this case we try to map the wheel to a button and not a button to a wheel.

**Comment by sezanzeb** [comment]
I'm thinking of adding a config parameter that just blocks HI_RES events. Right now I'm looking at the beta branch if we can do something more sophisticated there. If REL_WHEEL is mapped, then REL_WHEEL_HI_RES should not be forwarded.

**Comment by jonasBoss** [comment]
I was thinking something like this as well.
The simplest solution would be to add a mapping which disables the REL_WHEEL or REL_WEEHL_HI_RES. 

On the beta branch this should work:
```json
{
    "1,275,1+1,274,1": {
        "target_uinput": "keyboard",
        "output_symbol": "Control_L+period"
    },
    "1,275,1+2,6,1": {
        "target_uinput": "keyboard",
        "output_symbol": "Control_R+Prior"
    },
    "1,275,1+2,6,-1": {
        "target_uinput": "keyboard",
        "output_symbol": "Control_R+Next"
    },
    "1,275,1+2,8,1": {
        "target_uinput": "keyboard",
        "output_symbol": "Control_R+minus"
    },
    "1,275,1+2,8,-1": {
        "target_uinput": "keyboard",
        "output_symbol": "Control_R+comma"
    },
    
    "1,275,1+2,12,1": {
        "target_uinput": "keyboard",
        "output_symbol": "disable"
    },
    "1,275,1+2,12,-1": {
        "target_uinput": "keyboard",
        "output_symbol": "disable"
    },
    "1,275,1+2,11,1": {
        "target_uinput": "keyboard",
        "output_symbol": "disable"
    },
    "1,275,1+2,11,-1": {
        "target_uinput": "keyboard",
        "output_symbol": "disable"
    }
}
```

**Comment by pviscone** [comment]
It solves the wheel problem but now when the combination (side button + wheel) is executed the release of the side button is forwarded to the mouse 

This is the output of evtest for the input-remapper Mouse forwarded
```
###SIDE button is pressed and held
Event: time 1654443834.189111, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1654443834.189111, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1654443834.189111, -------------- SYN_REPORT ------------

### Wheel up
Event: time 1654443834.665740, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1654443834.665740, -------------- SYN_REPORT ------------

### Side button released
Event: time 1654443835.210525, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1654443835.210525, -------------- SYN_REPORT ------------

```

**Comment by jonasBoss** [comment]
there is the mapping parameter `release_combination_keys` for this.  More info about the mapping here: https://github.com/sezanzeb/input-remapper/blob/beta/readme/usage.md#mapping

**Comment by pviscone** [comment]
Work for all the combinations except for the ones with the wheel because its event can't be held. I just changed combinations avoiding using the wheel and everything works fine

**Comment by sezanzeb** [comment]
> because its event can't be held

what does that mean?

**Comment by pviscone** [comment]
release_combination_keys doesn't work on "side button + scroll the wheel" because the event "scroll the wheel" is transient.

You should release the side button really fast to trigger the action of release_combination_keys otherwise the release of the side button is forwarded to the device

**Comment by jonasBoss** [comment]
You are right, the scroll wheel will only send transient (or relative) events. But we take this into account: Inputremapper will internally generate a "key-release" event after some time (see: [`release_timeout`](https://github.com/sezanzeb/input-remapper/blob/beta/readme/usage.md#mapping)). If you set a higher value this will make it more natural to release the side-button before the wheel is "released".

So the wheel should behave exactly like a key. Pressed as long as it is moving, and released when it stops moving for more then `release_timeout`.

I am not exactly sure what behavior you are observing. 
you should observe the following:

 * press side-button
   * side-button forwarded
 * start scrolling
   * forwarded side-button is released (depending on `release_combination_keys`)
   * mapping is triggered
 * stop scrolling
 * after `release_timeout`
   * mapping stops
 * release side-button
   * release forwarded (because the combination is of button + wheel is not active) evtest might not report this because duplicate events are ignored.

And this should not be any different if you use a key instead of the wheel.

As long as `release_combination_keys=false` the behavior will be different depending on the order in which the keys are released. Because as soon as the first key of a combination is released the mapping is released and all subsequent key releases will be forwarded. This is technically also the case when `release_combination_keys=true` linux will ignore duplicate key-events.
