### ISSUE TITLE
KEY_QUESTION not being mapped to Control L + Slash( hyper X alloy origins 60%)

### ISSUE THREAD

**Issue by juanlet** [sezanzeb/input-remapper#412]
This is the layout
https://http2.mlstatic.com/D_NQ_NP_810187-MLA46272689323_062021-O.webp

![image](https://user-images.githubusercontent.com/12257699/171469800-18b52321-6267-4cdc-9101-e833a6d4c1e0.png)

I'm on ubuntu 20.04. Whenever I press that combination nothing comes up. It works with other keys, but the KEY_QUESTION string doesn't seem to be working

**Comment by sezanzeb** [comment]
I'll close this for now since it is probably a known old problem
