### ISSUE TITLE
Can anyone give me wheel code example?

### ISSUE THREAD

**Issue by lodexx0** [sezanzeb/input-remapper#413]
i want an example of wheel code. It seems wheel(up,1) but it doesn't working.
Who can help me?

**Comment by sezanzeb** [comment]
Have you set the dropdown to "mouse"?

![image](https://user-images.githubusercontent.com/28510156/172042670-0e93d3ca-a3cc-4920-b0ea-234ac71e2881.png)

**Comment by sezanzeb** [comment]
I'll close this for now. If you are still facing issues let me know
