### ISSUE TITLE
[NewUser] Combine CapsLock with another key

### ISSUE THREAD

**Issue by MatheusFerreiraL** [sezanzeb/input-remapper#416]
This is not something that's compromising my experience with the Remapper, but if I could change would be awesome.

I have a 60% keyboard (Husky Blizzard) so I have to remap the Arrows (up, right, down, left) to the combination:
Up: `Caps_Lock + i = key_up`, Right: `Caps_Lock + l = key_right` and the same for the rest (I use, as arrows, ijkl), but when I finish using the remapped keys my Caps stays "on". So I'm trying to (unsuccessfully unitl now) find a way to use this keys without the Caps staying "pressed" at the end.

**Comment by sezanzeb** [comment]
try `key(KEY_UP).key(KEY_CAPSLOCK)` and `key(KEY_RIGHT).key(KEY_CAPSLOCK)`

**Comment by sezanzeb** [comment]
I'll close this as it works for me. If you are still facing issues feel free to write another comment.
