### ISSUE TITLE
Input Remapper fails to open

### ISSUE THREAD

**Issue by supertriodo** [sezanzeb/input-remapper#419]
After my last system update on opensuse I receive the next console output when running input-remapper-gtk

```
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 28, in <module>
    from inputremapper.gui.gettext import _, LOCALE_DIR
ModuleNotFoundError: No module named 'inputremapper'
```

**Comment by KayTaneJupiter** [comment]
+1

```
systemd[1]: Starting Service to inject keycodes without the GUI application...
input-remapper-service[1284]: Traceback (most recent call last):
input-remapper-service[1284]:   File "/usr/bin/input-remapper-service", line 28, in <module>
input-remapper-service[1284]:     from inputremapper.logger import update_verbosity, log_info, add_filehandler
input-remapper-service[1284]: ModuleNotFoundError: No module named 'inputremapper'
systemd[1]: input-remapper.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: input-remapper.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Service to inject keycodes without the GUI application.
```

**Comment by KayTaneJupiter** [comment]
Solution appears to be to manually add / install evdev package from OpenSUSE.

**Comment by sezanzeb** [comment]
I'll close this for now due to inactivity.

You can check out `python3 -c "import sys; print(sys.path)"`, input-remapper should be installed to one of those paths. Reinstalling the package will probably help.

**Comment by supertriodo** [comment]
Reinstalling using the manual steps worked.

`sudo pip install evdev -U  # If newest version not in distros repo
sudo pip uninstall key-mapper  # In case the old package is still installed
sudo pip install --no-binary :all: git+https://github.com/sezanzeb/input-remapper.git
sudo systemctl enable input-remapper
sudo systemctl restart input-remapper`

Sorry for the delay and thanks!
