### ISSUE TITLE
Install doesn't work in Ubuntu 18.04 bionic due to 2 unsatisfyable dependencies - libgtksourceview-4-dev, python3-pydantic

### ISSUE THREAD

**Issue by sglajchEG** [sezanzeb/input-remapper#420]
Install doesn't work in Ubuntu 18.04 bionic due to 2 unsatisfyable dependencies - libgtksourceview-4-dev, python3-pydantic
It looks like the building of the deb package works but these 2 deps are not available in 18.04.

```
>>> The following packages have unmet dependencies:
 input-remapper : Depends: libgtksourceview-4-dev but it is not installable
                  Depends: python3-pydantic but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by sezanzeb** [comment]
Seems like you'll need Ubuntu 20.04 at least https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libgtksourceview-4-dev&searchon=names

**Comment by Eliza-and-black** [comment]
> Seems like you'll need Ubuntu 20.04 at least https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libgtksourceview-4-dev&searchon=names

Do you have plan to support Ubuntu18.04? My work computer use 18.04,and many projects rely on it, I can't change the system.Tks in advance.

**Comment by sezanzeb** [comment]
> Do you have plan to support Ubuntu18.04

No plans on my side
