### ISSUE TITLE
Mouse to joystick

### ISSUE THREAD

**Issue by Abalthazarr** [sezanzeb/input-remapper#433]
Good morning to everyone, can i use it to remap the mouse movement to the joystick?
i have a xbox controller here but its very bad for flight simulation because it have a lot of deadzone and i can be a lot more precise with mouse movement, theres a way to me to do this?

**Comment by jonasBoss** [comment]
Not yet. I have a similar issue, so I will work on this. Hopefully within the next two months.

It would be super helpful if you can describe how you would like to use this feature. A gamepad or joystick has a center position a mouse has not. So we need to come up with some translation between mouse and joystick. The simple solution would be to translate the mouse speed directly (mouse stationary -> center position; mouse "fast" -> full deflection) but this might not be the best user experience. I am open for suggestions regarding this.

**Comment by jonasBoss** [comment]
I just implemented this feature on [this branch](https://github.com/jonasBoss/key-mapper/tree/rel_to_abs). If you are willing to test it out I am happy about any feedback.

**Comment by jonasBoss** [comment]
Implemented on the beta branch
