### ISSUE TITLE
Trying to remap right control to middle click

### ISSUE THREAD

**Issue by AVDambeck** [sezanzeb/input-remapper#436]
My laptop doesn't have a middle mouse button which is really annoying for copy pasting out of terminals. Trying to remap my right control to a middle click. I'm able to remap it to other keys without issue but i can't find the symbol name for middle mouse click

Share some logs please:

1. `input-remapper-control --version`

> input-remapper 1.5.0 d7f15d15249314c73b29f0a502733ad231bb09b8 https://github.com/sezanzeb/input-remapper
> python-evdev 1.5.0

2. If a button on your device doesn't show up in the GUI, verify that the button is reporting an event via `sudo evtest`. If not, input-remapper won't be able to map that button.

i ran it then pressed left control [https://pastebin.com/yHEiRGZu](https://pastebin.com/yHEiRGZu) 

3. If yes, please run `input-remapper-gtk -d`, reproduce the problem and then share the logs.

not sure how to do this for this situation

**Comment by jonasBoss** [comment]
The middle mouse button is `BTN_MIDDLE`. Make sure to select `mouse` as the target in the dropdown for your mapping

**Comment by AVDambeck** [comment]
ah, it worked! It was the mouse as the target selection. thank you
