### ISSUE TITLE
pkexec command not found

### ISSUE THREAD

**Issue by KayTaneJupiter** [sezanzeb/input-remapper#450]
Just documenting this issue for others to find if they search.

pkexec was removed to a separate install item in my distro (OpenSUSE Tumbleweed) probably due to the security concerns with it. Input-Remapper would fail with "sh: line 1: pkexec: command not found"

Solution was to manually re-install pkexec.

Might be a good idea for dev to find an alternate to pkexec if distros are going to be dropping it.

**Comment by sezanzeb** [comment]
Thanks for reporting this.

I can't find information about distros dropping pkexec though. gnome-disks is still using polkit as well.
