### ISSUE TITLE
cant remap scroll

### ISSUE THREAD

**Issue by NiiightmareXD** [sezanzeb/input-remapper#462]
Please install the newest version from source to see if the problem has already been solved.

Share some logs please:

1. `input-remapper-control --version` input-remapper 1.5.0 0b885df73c7058158df7483aa542b065c7efa7d0
2. which linux distro (ubuntu 20.04, manjaro, etc.) fedora
3. `echo $XDG_SESSION_TYPE` x11
4. which desktop environment (gnome, plasma, xfce4, etc.) gnome
5. `sudo ls -l /proc/1/exe` lrwxrwxrwx. 1 root root 0 Aug 26  2022 /proc/1/exe -> /usr/lib/systemd/systemd
6. paste the affected preset .json file from ~/.config/input-remapper/presets
```json
{
    "mapping": {
        "1,274,1": [
            "KEY_F8",
            "keyboard"
        ],
        "2,8,-1": [
            "BTN_FORWARD",
            "mouse"
        ]
    }
}
```
the second one is scroll and when I scroll it presses BTN_FORWARD but it also scrolls how do I make it to just press BTN_FORWARD
thanks for helping

**Comment by jonasBoss** [comment]
You have probably the same issue as #411

**Comment by sezanzeb** [comment]
I'll close this since this is fixed on beta (https://github.com/sezanzeb/input-remapper/issues/411#issuecomment-1146818278)
