### ISSUE TITLE
Unclear Error Messages (Beta)

### ISSUE THREAD

**Issue by jonasBoss** [sezanzeb/input-remapper#468]
"Remove the Analog Output Axis when specifying an macro or key output"

![image](https://user-images.githubusercontent.com/28510156/188273954-00878463-248f-440e-a488-f45451683f73.png)

Is this error message related to this PR? I don't know what to do there

_Originally posted by @sezanzeb in https://github.com/sezanzeb/input-remapper/issues/442#issuecomment-1236126627_

**Comment by jonasBoss** [comment]
> ah, I had to switch to "Key or Macro" and clear the text input. Can we say that in the error message?
> 
> Now it shows a different error:
> 
> `__root__ missing macro or key: the combination = <EventCombination (2, 1, -1)> specifies a key input, but no output macro or key is programmed (type=value_error)`
> 
> ![image](https://user-images.githubusercontent.com/28510156/188273987-8c9a1e6e-c6c8-4bd7-8216-4d31e7ffeef7.png)

**Comment by jonasBoss** [comment]
"ctrl, alt and shift may not combine properly"

This needs a hint to the `Advanced Input Configuration` and the `Release Input` setting

**Comment by jonasBoss** [comment]
![image](https://user-images.githubusercontent.com/31804124/192789657-4131d363-6de4-42bf-8351-89160ed1f265.png)
This shows up when the text field `output_symbol` is a empty string and not `None`

**Comment by sezanzeb** [comment]
some ideas: https://github.com/sezanzeb/input-remapper/issues/530#issuecomment-1306044153

**Comment by sezanzeb** [comment]
![image](https://user-images.githubusercontent.com/28510156/204224797-00008046-2395-47b8-87e3-c14318269fc0.png)

I would use the classes __name__ instead and remove everything but the first error, like:

`"Expected parameter 2 for repeat to be one of [Macro], but got "dead_acute"`
