### ISSUE TITLE
usage.md is missing the section on key mappings

### ISSUE THREAD

**Issue by generous-turd** [sezanzeb/input-remapper#471]
Line 17 of usage.md should link to a heading called "3key-names-and-macros", but that heading doesn't seem to be present in the file. 

Please fix this as soon as you can as I can't seem to find a list containing the mappings I can use with this program anywhere else.

**Comment by jonasBoss** [comment]
I think you are looking for this: [key-names](https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#key-names) 
We have a examples [here](https://github.com/sezanzeb/input-remapper/blob/main/readme/examples.md), and If you want to make more advanced mappings you can checkout [macros.md](https://github.com/sezanzeb/input-remapper/blob/main/readme/macros.md)

**Comment by sezanzeb** [comment]
Thanks for reporting, I updated usage.md
