### ISSUE TITLE
Unable to remap 'r' to '-'

### ISSUE THREAD

**Issue by pcallycat** [sezanzeb/input-remapper#472]
When remapping 'r' to '-' on a Tartarus v2, any window still recieves the 'r'.  However, if i map it to a different key 'm' for example, the remapped key works

**Comment by jonasBoss** [comment]
try `KEY_MINUS` or, as the [documentation](https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#key-names) says:
> Input-remapper only recognizes symbol names, but not the symbols themselfes. So for example, input-remapper might (depending on the system layout) know what a `minus` is, but it doesn't know `-`.
