### ISSUE TITLE
GUI Redesign based on libadwaita and multiple "pages"

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#473]
I'll try to collect ideas and resources for a new GUI here. I think it is really hard to fit all of the features of the beta branch into one single window.

goals:
- a clean and non-cluttered GUI, similar to gnome-music
- work well with the modern adwaita theme
- use headerbars (maybe for a pagination, and to go back in the menu)
- reuse as many elements from the mapping configuration of the beta GUI as possible / recreate them with libadwaita
- use modern dialogs https://developer.gnome.org/hig/patterns/feedback/dialogs.html
- respect hig spacings https://developer-old.gnome.org/hig/stable/visual-layout.html.en

concept:
1. application starts and shows a device list. Analogous to how gnome-music shows the album list on start
2. select device from list. The complete GUI transitions to a different view, which shows the preset list. gnome-music also has that transition. On the top left in the headerbar a back button `<` is shown
3. selecting a preset from list acts in the same way
4. This leads to the preset configuration, which might look exactly like the stuff we have on beta

resources:
- adwaita python demo https://github.com/timlau/adw_pydemo
- gnome-music, which is also written in python https://gitlab.gnome.org/GNOME/gnome-music/
- libadwaita docs https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/
- cambalache, the GUI designer for libadwaita/gtk4 https://www.linuxadictos.com/en/swap-a-tool-for-creating-gtk-user-interfaces.html

**Comment by sezanzeb** [comment]
They do things like

```
@Gtk.Template(resource_path="/org/gnome/Music/ui/AlbumsView.ui")
class AlbumsView(Gtk.Stack):
```

**Comment by jonasBoss** [comment]
I also think it is a good idea to have a wizard with a more curated process for creating a new mapping.

1. What kind of Mapping?
    - Analog axis
    - key
    - macro
2. Record the input
    - provide a warning if the input is incompatible with the selected mapping type
3. provide a window with the relevant information for mapping type

**Comment by TerrorSquad** [comment]
How about instead of using libadwaita, you port the app to Tauri and write the frontend in something like Vue.js?

**Comment by sezanzeb** [comment]
I want desktop apps to properly integrate with the looks of the rest of the desktop

**Comment by TerrorSquad** [comment]
Understandable.

But that's only for the GNOME desktop? Is it going be easy to integrate with the look and feel of KDE or Cinnamon?

**Comment by sezanzeb** [comment]
Cinnamon is GTK based just like Gnome, the only difference is that their own apps probably don't use headerbars like Gnome does. So the theme will be consistent. KDE will theme GTK apps, so it's similar to Cinnamon here.

**Comment by sezanzeb** [comment]
It should be possible to write arbitrary user interfaces in any language or framework, it just needs to communicate with the daemon and manage the config files. There are some apps that have both qt and gtk variants.

**Comment by TerrorSquad** [comment]
Great to hear it will work on both Cinnamon and KDE as well.

I'm using Mint on my laptop and Kubuntu on my desktop since I'm not a GNOME fan.

I found some reddit discussions about not being able to theme libadwaita apps on KDE, such as this one:
https://www.reddit.com/r/kde/comments/ry20h7/are_there_any_plans_by_kde_to_try_and_tame_the/
That was the only reason why I asked about about DEs. 

As for Tauri, their basic Hello World app with Vite and Vue.js requires about 28MB of RAM.
Binary is 6.5MB, DEB file 2.5MB and AppImage is about 70MB. (Additional compression can be applied with tools such as UPX)

It could prove useful and allow for faster development since there are more web developers compared to gtk developers (more potential contributors).

**Comment by sezanzeb** [comment]
@TerrorSquad the new gui is still running on GTK 3, it will theme the same way it used to

**Comment by sezanzeb** [comment]
If I have to choose between rewriting everything in qt and using libadwaita, I'd rather give qt a try as of now.

I severely dislike the theming restrictions.

**Comment by jonasBoss** [comment]
I would suggest not using qt but [kirigami](https://develop.kde.org/frameworks/kirigami/) which is based on qml which in turn is based on qt. Kirigami is the standard framework for new kde applications (as far as I know). It allows for fully convergent GUIs, a good example is [discover](https://youtu.be/-8mHAmMej4c), and it does not look out of place on a gnome desktop.
