### ISSUE TITLE
Application packages don't contain architecture in file name

### ISSUE THREAD

**Issue by TerrorSquad** [sezanzeb/input-remapper#480]
Hi,

Please add the build architecture in the names of release files. (amd64, x86_64, x86-64, musl, arm64, etc.)

Here's an example for the amd64 architecture:
input-remapper-1.5.0_amd64.deb

You can find great examples in this repo: https://github.com/dandavison/delta/releases

**Comment by sezanzeb** [comment]
But the release files only contain python scripts, nothing binary that is compiled for a specific architecture.

**Comment by TerrorSquad** [comment]
Yeah, that makes sense. I just figured it would be nice to follow the naming convention that includes the architecture.

**Comment by sezanzeb** [comment]
Ah, there seems to be "_all" for those cases, lutris does it: https://github.com/lutris/lutris/releases/tag/v0.5.11

I renamed the release file of 1.5.0, future builds will contain it in the filename

thanks
