### ISSUE TITLE
Disable virtual gamepad

### ISSUE THREAD

**Issue by bladeSk** [sezanzeb/input-remapper#490]
Is there any way of disabling the virtual gamepad (`input-remapper gamepad (/dev/input/js0)`)? It interferes with games that use only the first gamepad or query gamepad count and generally causes issues despite me not using any gamepad remapping.

**Comment by sezanzeb** [comment]
This issue should have been fixed since 1.4.2. Which version are you running?

**Comment by bladeSk** [comment]
Excellent, that was it. Ubuntu has an outdated version, as usual, it was 1.4.0 in my case. Thanks for pointing me in the right direction.
