### ISSUE TITLE
Hide window-control buttons in tiling wms

### ISSUE THREAD

**Issue by coffebar** [sezanzeb/input-remapper#506]
A lot of tiling wm users disable window decoration buttons on their wm (close, minimize, fullscreen).
I see that this software ignores such option.
It's related to 

```
// data/input-remapper.glade

<object class="GtkHeaderBar">
  ...
  <property name="show-close-button">True</property> <----- this line

```
I am not sure if this line is necessary, may be window manager can decide this itself? I have tested on my env that if remove this line, decoration buttons hidden as expected. 
I need someone to test same thing on WM where decoration buttons should be.
If it will be ok, we should remove this line from glade.

![image](https://user-images.githubusercontent.com/3100053/197330940-29c21d3c-3c5e-4dc5-95ad-c7222a76bf77.png)

**Comment by jonasBoss** [comment]
on kde-plasma this results in missing buttons unfortunately. So this option will not work.

**Comment by sezanzeb** [comment]
how do other applications that use gtk headerbars behave? like gedit and gnome-disks?

**Comment by jonasBoss** [comment]
gedit has the buttons on kde-plasma.

**Comment by coffebar** [comment]
It seems all gnome apps behave like that - has a close buttons even on tiling:
![image](https://user-images.githubusercontent.com/3100053/197336482-53df9528-2abd-44b2-b4b3-daa83839213a.png)

I'm closing this issue.
