### ISSUE TITLE
Device names containing `/` cause problems

### ISSUE THREAD

**Issue by jonasBoss** [sezanzeb/input-remapper#507]
> Here's an icky situation I am facing wrt presets: IR identifies my mouse as "Logitech M585/590." Yep, you've read that right: there's a slash in there, and that confuses the hell out of my system. As a result, quite often IR doesn't load the proper profile upon reboot, so I have to load it manually. Is there any way we can control the name of the devices as far as IR is concerned?

_Originally posted by @Aqua1ung in https://github.com/sezanzeb/input-remapper/discussions/504_

**Comment by jonasBoss** [comment]
@Aqua1ung Can you test this https://github.com/jonasBoss/key-mapper/tree/507 ?

**Comment by Aqua1ung** [comment]
You mean, test IR 1.5? I am running that as we speak, with no problems. What issues was that supposed to fix though?

**Comment by jonasBoss** [comment]
The issue you reported here: #504 
No I don't mean Input-Remapper 1.5 

Do you still have the issues with the "Logitech M585/590."?
If so, can you install Input-Remapper from the source I linked above and see if it fixes the issue?

**Comment by sezanzeb** [comment]
@Aqua1ung If you install using the instructions from the readme it should work https://github.com/sezanzeb/input-remapper#installation

**Comment by tsantzi** [comment]
By coincidence I have the same mouse ("Logitech M585/590") and had the same issue with the daemon failing to load presets due to the slash in the name. I've created #524 that fixes this (at least in my case).

**Comment by jonasBoss** [comment]
It looks like I missed the preset-path in the daemon.
Thank you for reporting the issue.
