### ISSUE TITLE
High CPU load when unplugging injected device

### ISSUE THREAD

**Issue by TacticalCode** [sezanzeb/input-remapper#527]
I get ~100% CPU load when I unplug an injected device with the GUI open.
Fedora 36, input-remapper 1.5.0, python-evdev 1.6.0

![grafik](https://user-images.githubusercontent.com/1640173/199236034-a4f686d5-9c52-4657-bf32-568dfe7f498b.png)

The problem only occurs if there is an active injection as the device gets unplugged.

I've quickly edited /usr/bin/input-remapper-helper to call `cProfile.run("helper.run()", "/tmp/ir_helper.profile")` and reproduced the high load.
`snakeviz /tmp/ir_helper.profile` spits out (sorted by ncalls):

```
ncalls | tottime | percall | cumtime | percall | filename:lineno(function)
-- | -- | -- | -- | -- | --
1716831 | 0.6135 | 3.573e-07 | 0.6135 | 3.573e-07 | ~:0(<built-in method builtins.hasattr>)
1716821 | 8.566 | 4.989e-06 | 8.566 | 4.989e-06 | ~:0(<built-in method posix.open>)
858431 | 0.1089 | 1.269e-07 | 0.1089 | 1.269e-07 | ~:0(<built-in method builtins.len>)
858415 | 1.32 | 1.538e-06 | 9.998 | 1.165e-05 | device.py:111(__init__)
858415 | 0.2669 | 3.11e-07 | 0.8402 | 9.788e-07 | device.py:156(__del__)
343376 | 0.161 | 4.689e-07 | 0.2512 | 7.317e-07 | __init__.py:1455(debug)
343376 | 0.09022 | 2.627e-07 | 0.09022 | 2.627e-07 | __init__.py:1724(isEnabledFor)
171687 | 0.1791 | 1.043e-06 | 1.185 | 6.9e-06 | pipe.py:96(recv)
171685 | 0.7114 | 4.143e-06 | 0.9612 | 5.599e-06 | ~:0(<method 'readline' of '_io.TextIOWrapper' objects>)
171685 | 0.1739 | 1.013e-06 | 0.2499 | 1.455e-06 | codecs.py:319(decode)
171685 | 0.1689 | 9.837e-07 | 1.391 | 8.1e-06 | pipe.py:129(poll)
171685 | 0.07593 | 4.423e-07 | 0.07593 | 4.423e-07 | ~:0(<built-in method _codecs.utf_8_decode>)
171684 | 0.1739 | 1.013e-06 | 1.684 | 9.809e-06 | helper.py:113(_read_commands)
171683 | 1.425 | 8.298e-06 | 23.47 | 0.0001367 | helper.py:141(_start_reading)
612 | 0.0001785 | 2.916e-07 | 0.0001785 | 2.916e-07 | ~:0(<built-in method builtins.isinstance>)
596 | 0.000183 | 3.071e-07 | 0.000183 | 3.071e-07 | ~:0(<method 'append' of 'list' objects>)
585 | 0.0001539 | 2.631e-07 | 0.0001539 | 2.631e-07 | ~:0(<method 'setdefault' of 'dict' objects>)


```

Call Stack for the posix.open (2nd row):
```
5. ~:0(<built-in method posix.open>)
4. device.py:111(__init__)
3. helper.py:141(_start_reading)
2. helper.py:89(run)
1. <string>:1(<module>)
0. ~:0(<built-in method builtins.exec>)
```

Speculation on my part:

I guess the app keeps trying to read from the non-existing device here: https://github.com/sezanzeb/input-remapper/blob/main/inputremapper/gui/helper.py#L199
or endlessly calling _start_reading() using the "old" device list including the non-existing device: https://github.com/sezanzeb/input-remapper/blob/main/inputremapper/gui/helper.py#L160

**Comment by sezanzeb** [comment]
Thanks a lot! Event reading is different on the beta branch, but I found the problem there as well.

If the device disappears, things like `select.select` and `loop.add_reader` don't appear to wait anymore.

Once https://github.com/sezanzeb/input-remapper/pull/519 is merged, the beta version will have the fix. I hope you don't mind if I don't fix this on main anymore. It makes life a bit easier for me. Beta will be merged into main in February or something.

**Comment by sezanzeb** [comment]
fix is on the beta branch
