### ISSUE TITLE
help needed with mouse buttons Mapping (sorry)

### ISSUE THREAD

**Issue by NickTheNeko2002** [sezanzeb/input-remapper#528]
hey i'm trying to make my "BTN_EXTRA" to do "BTN_RIGHT" then "BTN_LEFT" if tapped and if pressed to basically do "Mouse5"/"BTN_EXTRA" but no matter what i tried nothing works am i read the examples.md but nothing helped either i read the instructions wrong or i am doing something wrong???

**Comment by sezanzeb** [comment]
try

```
if_tap(
    key(BTN_RIGHT).key(BTN_LEFT),
    hold(BTN_EXTRA)
)
```

**Comment by NickTheNeko2002** [comment]
> try
> 
> ```
> if_tap(
>     key(BTN_RIGHT).key(BTN_LEFT),
>     hold(BTN_EXTRA)
> )
> ```

thanks
