### ISSUE TITLE
Option to swap left and right mouse buttons for left hand mouse usage

### ISSUE THREAD

**Issue by mcarans** [sezanzeb/input-remapper#533]
It would be great if there was an option to swap left and right mouse buttons for people who use the mouse with their left hand. Mapping left button to right and right button to left doesn't seem to work.

**Comment by mcarans** [comment]
> it is supposed to work.
> 
> post your preset file please in `~/.config/input-remapper`

Sure. The file `new preset.json` looks like this:

```
{
    "mapping": {
        "1,272,1": [
            "key(BTN_RIGHT)",
            "keyboard"
        ],
        "1,273,1": [
            "key(BTN_LEFT)",
            "keyboard"
        ]
    }
}

```

**Comment by mcarans** [comment]
I have just found what the issue is. I needed to select mouse in the configuration next to change key. Closing.

**Comment by sezanzeb** [comment]
Depending on your use-case, just `BTN_RIGHT` or `hold(BTN_RIGHT)` might be better than `key(BTN_RIGHT)`
