### ISSUE TITLE
input-mapper ERROR: Don't know what "#" is

### ISSUE THREAD

**Issue by andrejvanderzee** [sezanzeb/input-remapper#535]
For Apple's Magic Keyboard (EU layout) I cannot find a 100% proper keyboard layout in Ubuntu.

Now I am trying to map the Shift - 3 (£) to Option - 3 (#). This is the only key that is not properly mapped for the keyboard layout, but it does not want to inject:

```
$ journalctl -u input-remapper-daemon --no-pager | tail -n 2
nov 09 09:48:15 andrej-macbook-pro input-remapper-service[5683]: Starting injecting the preset for "Apple Inc. Magic Keyboard"
nov 09 09:48:15 andrej-macbook-pro input-remapper-service[5683]: ERROR: Don't know what "#" is
```

How can I fix this?

**Comment by andrejvanderzee** [comment]
I have found that I have to map to "Control_R + 3".

**Comment by sezanzeb** [comment]
yes. For the reasons, check out https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#limitations
