### ISSUE TITLE
typo (wich -> which)

### ISSUE THREAD

**Issue by jose1711** [sezanzeb/input-remapper#543]
https://github.com/sezanzeb/input-remapper/blob/8c1180822d28856a0ad5fcbc1b2b15d814087d3a/data/input-remapper.glade#L1107

**Comment by jose1711** [comment]
Another one here:
https://github.com/sezanzeb/input-remapper/blob/8c1180822d28856a0ad5fcbc1b2b15d814087d3a/inputremapper/gui/controller.py#L183

**Comment by sezanzeb** [comment]
Thanks
