### ISSUE TITLE
Recording output

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#546]
for "Key or Macro" output add a button to record output. Should work the same way as the input-recording, but instead write the `KEY_` constants into the output text

because it is absolutely user-unfriendly to figure out how to inject `` ` `` on german keyboards

**Comment by sezanzeb** [comment]
for simplicity, and because this would require reading from all available devices, I would use the GTK events for this and read their keycodes.

**Comment by joezhouchenye** [comment]
I used the input-recording to figure out the key names. Just in a new entry, input your desired keys and you will see the key names in the entry list.

**Comment by sezanzeb** [comment]
yeah, that was not really practical. Try installing the beta version, it's easy there now
