### ISSUE TITLE
Mapping "disable" to a mouse button creates errors, but then works

### ISSUE THREAD

**Issue by 31337-4554551n** [sezanzeb/input-remapper#552]
Mapping
disable
To a mouse button causes an error in the bottom left "Unknown mapping disable". But then the button stops working as designed.

**Comment by sezanzeb** [comment]
this seems to be fixed already on beta, but I just noticed that input is not trimmed before it is validated by pydantic

**Comment by sezanzeb** [comment]
I'll close this then, the release that fixes this will probably arrive at some point in February. You can already install it by using the `beta` git branch.
