### ISSUE TITLE
how do I remap a mouse button to do a double-click and another button to "go back"?

### ISSUE THREAD

**Issue by ambassader** [sezanzeb/input-remapper#560]
I am using input remapper for a MicroSoft Trackball Explorer in Linux Mint Cinnamon. I have been able to remap one button (Button SIDE as BTN_RIGHT), but I would like to remap other buttons: Button EXTRA as a double left click; Button RIGHT as back a page ("Back" in Microsoft Windows Trackball Explorer settings); and Button MIDDLE as "copy".
Before a recent Mint upgrade, I had used Key Mapper, which at least had a pull-down menu of all possible remapping options, but didn't have "Double-click" or "Back" among the extensive list of options, which baffled me since everyone regularly double clicks and often goes back. 
I also saw a list of input remapper commands while executing the program from linux terminal, but i didn't have a way to capture, copy, or otherwise save the list. I have been trying to find that again.
I imagine that my question has a simple answer but I need help with it.  Thanks for your assistance.

**Comment by sezanzeb** [comment]
double-click would be `key(BTN_LEFT).key(BTN_LEFT)`

the mapping for back can be more easily be figured out if you use the current beta version. If you have another device that has a "back" button/key, and use it, the gui will display the name that you need to use as the mapping.

**Comment by timmarjo** [comment]
Hi, `key(BTN_LEFT).key(BTN_LEFT)` doesn't work as double-click for me. Using Ubuntu 22.04.2 and input-remapper 2.0.0
I have a Contour RollerMouse Pro3 plus device, input-remapper detects the button in hand as "Button TASK" and when I set `key(BTN_LEFT).key(BTN_LEFT)` as output (target: mouse), it works as a single click..
"Go back" and "go forward" are fine, I just mapped them to `Alt_L+Left` and `Alt_L+Right` to keyboard target.
It's just this double-click that I can't get to work.
Thanks for any help.

**Comment by sezanzeb** [comment]
Try `key(BTN_LEFT).wait(100).key(BTN_LEFT)`

If that works, feel free to add an example for double-click to https://github.com/sezanzeb/input-remapper/blob/main/readme/examples.md

**Comment by ambassader** [comment]
Greetings - On Nov. 28, 2022 I asked the question about using input remapper using MicroSoft Trackball Explorer in Linux Mint Cinnamon. Since you suggested I get the current beta version and I see others referring to version 2.0, I downloaded version 1.5 but it wouldn't install because a part of 1.4 was still open. I couldn't uninstall it for the same reason. It has taken me months before I had the time to wipe my machine and re-install the latest version of Mint to start over fresh.  Now I cannot even find input remapper version 1.5 and I have no idea where to find the "current beta version". 
In the mean time I have tried to make sense of xbindkeys, but it seems more complicated or needs to be executed via terminal.
I see that the double click command problem seems solved with a time delay between the click commands. 
I feel that I'm very close to solving my problem. Could you tell me where to find the latest beta or released version?

**Comment by sezanzeb** [comment]
> I downloaded version 1.5 but it wouldn't install because a part of 1.4 was still open

logs would have been great for that to figure out what went wrong. In any case, a complete fresh install of Mint would have been preventable to get this work.

> I see others referring to version 2.0, I downloaded version 1.5

Why not download 2.0?

> I have no idea where to find the "current beta version".

Because it was released as 2.0

**Comment by ambassader** [comment]
Thank you
