### ISSUE TITLE
Mapping button to command

### ISSUE THREAD

**Issue by lcsfox** [sezanzeb/input-remapper#561]
Is it possible to map a key to a command
ex. mouse button 12 > echo "foo"
If yes, what would be the context of the command?

**Comment by sezanzeb** [comment]
Not possible, sorry. There are lots of security issues and architectural challenges with this, as the daemon is running as the root user.

Desktop environments usually have a built in way of doing this, see https://github.com/sezanzeb/input-remapper/issues/234#issuecomment-1014269613
