### ISSUE TITLE
Pipelines are not passing anymore

### ISSUE THREAD

**Issue by sezanzeb** [sezanzeb/input-remapper#564]
pipelines on both main and beta are failing with

```
error: invalid command 'bdist_wheel'
```

See https://github.com/sezanzeb/input-remapper/actions/runs/3503068599/jobs/6066108898

@LunNova can you please help out?

**Comment by LunNova** [comment]
bdist_wheel comes from wheel which is installed here https://github.com/sezanzeb/input-remapper/blob/main/scripts/ci-install-deps.sh#L11 so it's not as easy as adding pip install wheel.

Will investigate more thoroughly later, don't have time this morning.

**Comment by sezanzeb** [comment]
It's not urgent at all. Thanks for your help!
