### ISSUE TITLE
Github Actions are broken

### ISSUE THREAD

**Issue by jonasBoss** [sezanzeb/input-remapper#565]
The build Action fails at the `Install dependencies` step.
This seems to affect all branches including commits that previously passed.

Failed run on main:
https://github.com/sezanzeb/input-remapper/actions/runs/3503068599/jobs/6066109001

**Comment by jonasBoss** [comment]
Apparently the latest runner now is Ubuntu 22.04 (jammy). All passing runs where on 20.04 (focal).

**Comment by LunNova** [comment]
#564
