### ISSUE TITLE
The pipe key seems to be mising

### ISSUE THREAD

**Issue by blurymind** [sezanzeb/input-remapper#567]
the pipe key is missing as an option. If you are a programmer with a 60% keyboard, thats quite an important button to be able to remap others to

https://grammarist.com/punctuation/pipe-symbol/#:~:text=The%20pipe%20symbol%20is%20located,shift%20and%20the%20backslash%20key.

**Comment by jonasBoss** [comment]
see https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#limitations
