### ISSUE TITLE
Provide a .deb file with an older compression (don't use zst)

### ISSUE THREAD

**Issue by bybor** [sezanzeb/input-remapper#573]
The current (bullseye, Debian 11) `dpkg` doesn't recognize `zst` compression, and this prevents installing `input-remapper` through provided `_all.deb` file.

It is happening in MX Linux 21 for me, but Debian 11 is also affected AFAICS.

Thank you!

**Comment by sezanzeb** [comment]
https://github.com/sezanzeb/input-remapper/blob/main/scripts/build.sh

How would one modify this to not use zst?

**Comment by bybor** [comment]
From here https://askubuntu.com/questions/735615/what-compression-is-supported-by-debian-file-deb-decompressor,

I would say, when calling dpkg, provide "-Zgzip" as a param

**Comment by sezanzeb** [comment]
The 1.5.1 release deb should have the gzip compression.
