### ISSUE TITLE
Remap to a custom key

### ISSUE THREAD

**Issue by Equinoxx4978** [sezanzeb/input-remapper#583]
I have side buttons on my mouse that I want to remap to a "custom button" so that I can choose what it does on a per app/game basis.

The side buttons get detected perfectly, I just want to know if I can map it to a button that doesn't technically exist or do anything, so I can set what it does in each game myself.

**Comment by sezanzeb** [comment]
You could try the `KEY_MACRO*` keys

https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L689
