### ISSUE TITLE
Every Key on the qwertz layout that is different from the qwerty layout does not get remapped at all 

### ISSUE THREAD

**Issue by QuirinR33** [sezanzeb/input-remapper#586]
Examples: ß, ´, ü, +, ö, ä, # on qwertz layout

1. `input-remapper 1.5.0 bc68fa7f6ec8faf10fb01e4b70426cade6ca50e1 https://github.com/sezanzeb/input-remapper
python-evdev 1.6.0`
2. Endeavour OS
3. `x11`
4. KDE Plasma (5.26.4 (at time of publishing))
5. `lrwxrwxrwx 1 root root 0 26. Dez 13:13 /proc/1/exe -> /usr/lib/systemd/systemd`

6. [PasteBin Link](https://pastebin.com/8LPuxqn2)
7. [PasteBin Link 2](https://pastebin.com/gU37kXsr#iM7m8i5i)
8. 1.`/dev/input/event22:	input-remapper keyboard`
2.`/dev/input/event24:	input-remapper Compx 2.4G Wireless Receiver forwarded`
3.`/dev/input/event25:	input-remapper Compx 2.4G Wireless Receiver Keyboard forwarded`,
[Device 1 (PasteBin)](https://pastebin.com/L6es2pfy)
[Device 2 (PasteBin)](https://pastebin.com/HU0Ysq2R)
[Device 3 (PasteBin)](https://pastebin.com/TETyhnXF)

**Comment by jonasBoss** [comment]
without input-remapper running, can you provide the output from `evtest` when you press a affected key. With both layouts?

**Comment by QuirinR33** [comment]
using 3 examples from issue-post:
QWERTZ (ß, +, ä): QWERTY: -, ], '
ß:
`Event: time 1672130776.672968, -------------- SYN_REPORT ------------`
`Event: time 1672130783.112819, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7002d`
`Event: time 1672130783.112819, type 1 (EV_KEY), code 12 (KEY_MINUS), value 1`
`Event: time 1672130783.112819, -------------- SYN_REPORT ------------`
`Event: time 1672130783.248813, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7002d`
`Event: time 1672130783.248813, type 1 (EV_KEY), code 12 (KEY_MINUS), value 0`

+:
`Event: time 1672130957.350023, -------------- SYN_REPORT ------------`
`Event: time 1672130965.277946, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70030`
`Event: time 1672130965.277946, type 1 (EV_KEY), code 27 (KEY_RIGHTBRACE), value 1`
`Event: time 1672130965.277946, -------------- SYN_REPORT ------------`
`Event: time 1672130965.333930, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70030`
`Event: time 1672130965.333930, type 1 (EV_KEY), code 27 (KEY_RIGHTBRACE), value 0`

ä:
`Event: time 1672131317.985480, -------------- SYN_REPORT ------------`
`Event: time 1672131320.817468, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70034`
`Event: time 1672131320.817468, type 1 (EV_KEY), code 40 (KEY_APOSTROPHE), value 1`
`Event: time 1672131320.817468, -------------- SYN_REPORT ------------`
`Event: time 1672131320.905472, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70034`
`Event: time 1672131320.905472, type 1 (EV_KEY), code 40 (KEY_APOSTROPHE), value 0`

QWERTY returns exactly the same outputs. (interesting)

**Comment by QuirinR33** [comment]
And I have found a workaraound... that was easier than expected!
I normally put something like "x" into the second field (which works), so I also put "ß" into that field (which DOESN'T work), but if I put in "KEY_X" (<- I don't have to do that) and "KEY_MINUS" (QWERTY-Representation for ß-key), it works!

**Comment by sezanzeb** [comment]
> QWERTY returns exactly the same outputs. (interesting)

because evdev shows you the codes, and it doesn't know anything about your actual keyboard layout.

the keyboard layout you see on your keyboard is really just a print. Under the hood every key will always have the same code, regardless of the layout.

translating those codes to a symbol is done by x11 in your case, only there the keyboard layout actually matters.

**Comment by QuirinR33** [comment]
Ok so I think we can mark this is issue as resolved.

**Comment by sezanzeb** [comment]
try mapping to `adiaeresis` instead of `ä`

and `ssharp` instead of `ß`
