### ISSUE TITLE
Trouble remapping Left Alt + anything

### ISSUE THREAD

**Issue by J-Kappes** [sezanzeb/input-remapper#600]
In my minimum working example I remap `Alt_L + J` to `F`. So far, so good. I can use "change Key" to capture the key combination I want to remap.

However, when I apply the preset, it only works for a split second after injection. It will also keep working so long as I don't let go of left Alt after pressing it soon enough, but thereafter `Alt_L + J` will no longer type `F`. But when I did the `evtest` it seemed to still register `F` presses despite it not working in practice.

1. `input-remapper-control --version`: 1.5.0
2. Debian GNU/Linux bookworm/sid x86_64
3. Wayland
4. GNOME 43.2
5. `lrwxrwxrwx 1 root root 0 Dec  2 11:09 /proc/1/exe -> /usr/lib/systemd/systemd`

6.
 ```
{
    "mapping": {
        "1,56,1+1,36,1": [
            "f",
            "keyboard"
        ]
    }
}
```
7. https://gist.github.com/J-Kappes/cd995f02815637a7386c11af618546db
8. https://gist.github.com/J-Kappes/9d2aaa3807b5ffad5a7f0b6f1948e8e7

**Comment by sezanzeb** [comment]
Try the beta version please
