### ISSUE TITLE
Where is the AT (@) key?

### ISSUE THREAD

**Issue by michaelradhuber** [sezanzeb/input-remapper#605]
I am trying desperately to map the at key, without luck. Other keys work.

(Ubuntu 22, wayland).

Could somebody help me with the keycode for the at key? (key(at) or key(@) or KEY_MODE+Q or KEY_3D_MODE+Q do not work)

Thanks so much in advance! Mike

**Comment by jonasBoss** [comment]
there is probably no @ key. It depends on your keyboard layout/language setting: https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#limitations

You will likely need a key combination. On a German keyboard/layout it is `KEY_RIGHTALT + KEY_Q`

**Comment by jonasBoss** [comment]
you can use `$sudo evtest` and type @. It will show you the keys you need.
