### ISSUE TITLE
mouse wheel events not working

### ISSUE THREAD

**Issue by SamDevelopsCode** [sezanzeb/input-remapper#619]
I have an offbrand vertical mouse. https://www.amazon.com/dp/B09G6DTKNB/ref=redir_mobile_desktop?_encoding=UTF8&aaxitk=1c7717d683e1d7897960cc9a4801a7d9&content-id=amzn1.sym.7dd77237-72be-4809-b5b5-d553eab7ad9d%3Aamzn1.sym.7dd77237-72be-4809-b5b5-d553eab7ad9d&hsa_cr_id=3541361940601&pd_rd_plhdr=t&pd_rd_r=d4a2acd7-dbb7-478a-b5aa-a8b1ccf40606&pd_rd_w=3Pcd0&pd_rd_wg=Gt9em&qid=1676257289&ref_=sbx_be_s_sparkle_lsi4d_asin_1_img&sr=1-2-9e67e56a-6f64-441f-a281-df67fc737124

Its called Delux Seeker. It has a secondary scroll ball on the left side above your thumb. The ball normally does horizontal scroll but I am trying to get it to change to normal vertical scroll using your thumb to alleviate my hand pain even further.

I can successfully choose the mouse in the dropdown. I then click change key and choose 'mouse' from the dropdown menu. And type in wheel(up, 10) which is the command shown in the instructions. Nothing happens.

I can successfully make it type 'a' if I choose keyboard from the dropdown menu. It is only the scrolling that will not work for some reason.
![image](https://user-images.githubusercontent.com/122749374/218361503-c84a9f5a-c043-4622-a03c-5391a6c2d154.png)

I have also tried to set a keyboard key to scroll with mouse wheel and could not get it to work.

**Comment by jonasBoss** [comment]
You have probably the best experience with the `beta` branch, that has direct support for mapping a scroll wheel to another without using macros. Refer to the [beta `usage.md`](https://github.com/sezanzeb/input-remapper/blob/beta/readme/usage.md#analog-axis) for more info on that.

Also it is difficult to say what is going on without any logs. you can use `$ sudo evtest` to see what your devices do, and if mappings do what you expect.

**Comment by SamDevelopsCode** [comment]
Is there a way to just simply download a .deb file for the beta and install it simply just like I did with 1.5.0? I am 5 hours deep into trying to find a mouse solution, extremely frustrated.

Tried manually installing 1.6.0 beta and had no luck. Just problem after problem after problem. I don't even have the willpower to screenshot all the error messages.

**Comment by jonasBoss** [comment]
no, there is no mouse clicky way to do this. I assume you tried:

```sh
sudo apt install git python3-setuptools gettext
git clone -b beta https://github.com/sezanzeb/input-remapper.git
cd input-remapper && ./scripts/build.sh
sudo apt install ./dist/input-remapper-1.6.0-beta.deb
```
I am not using a Debian based distro, so I am not sure if this works.

**Comment by SamDevelopsCode** [comment]
It finally worked. I am newcomer to linux and was having trouble even getting the beta repo to clone instead of main. On top of a cold from hell.

It always works with the mouse. Thank you
