### ISSUE TITLE
Mapping to symbols like >,|

### ISSUE THREAD

**Issue by thetwom** [sezanzeb/input-remapper#620]
Thank you very much for the development of this tool.

I wonder if it is possible to map a key combination like Alt+y to > or |. Using `input-remapper-control --symbol-names` shows the symbol `less`, but I cannot find symbols like `bar` or `greater`.

**Comment by sezanzeb** [comment]
yes.

Since you want to map Alt+y to that symbol, you should use the beta version

Then check out https://github.com/sezanzeb/input-remapper/blob/beta/readme/usage.md#limitations. You have to inject the combination that ends up in |

**Comment by jmoraispk** [comment]
Hi @sezanzeb,
I have the same problem as @thetwom. 

There are many symbols in the EN ISO keyboard that I cannot type, like the portuguese `ccedilla` [ç]. But this somewhat uncommon symbol is supported via the respective keyword. Likewise, in the Portuguese layout, I cannot type a the `less` [<] sign, yet it is available via the less keyword. But the same is not true for its counterpart, the `greater` [>] sign.

I would humbly request the `greater` [>] key to be added please. It would make a significant difference for me.

**Comment by jmoraispk** [comment]
Btw, I checked issue #195, and the section it advises checking [emitting unavailable symbols](https://github.com/sezanzeb/input-remapper/blob/main/readme/examples.md#emitting-unavailable-symbols), but although it shows the "greater" option, it does not inject the key.

**Comment by jmoraispk** [comment]
Well.. Not sure what happened, but I thin after running xmodmap again it started to work. Therefore, this issue can and should remain closed as there seems to be a good way to add unavailable keys, as mentioned in the tutorials. Thanks!

**Comment by sezanzeb** [comment]
Glad this got resolved for you.

Since `>` has to be "created" in different ways depending on the keyboard layout, this can't easily be added to input-remapper. There is one related feature request here: https://github.com/sezanzeb/input-remapper/issues/90
