### ISSUE TITLE
Need to Re-Press "Apply" Button After Resuming from Suspension on Ubuntu 22.10 Gnome

### ISSUE THREAD

**Issue by adriaan35134231451324** [sezanzeb/input-remapper#623]
I am running Ubuntu 22.10 Gnome on my machine, and I have noticed that after I resume from suspension, I need to re apply the presets again i was using.

**Comment by sezanzeb** [comment]
after resuming, what are the outputs of

`systemctl status input-remapper`

`input-remapper-control --command hello`

`sudo evtest` (I just need the list of devices for now)

?

**Comment by adriaan35134231451324** [comment]
> after resuming, what are the outputs of
> 
> `systemctl status input-remapper`
> 
> `input-remapper-control --command hello`
> 
> `sudo evtest` (I just need the list of devices for now)
> 
> ?

> user@Tablet:~$ systemctl status input-remapper
● input-remapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/lib/systemd/system/input-remapper.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-02-18 08:03:39 PST; 2 days ago
   Main PID: 747 (input-remapper-)
      Tasks: 7 (limit: 9381)
     Memory: 281.1M
        CPU: 1h 6min 34.569s
     CGroup: /system.slice/input-remapper.service
             ├─  747 /usr/bin/python3 /usr/bin/input-remapper-service
             ├─  856 /usr/bin/python3 /usr/bin/input-remapper-service
             └─84591 /usr/bin/python3 /usr/bin/input-remapper-service

Feb 20 14:44:51 Tablet input-remapper-service[747]: Request to autoload for "IPTS 1B96:0023"
Feb 20 14:44:52 Tablet input-remapper-service[747]: Found "Hengchangtong  HCT USB Entry Keyboard", "IPTS 1B96:0023", "input-remapper SEMICO USB Keyboard forward>
Feb 20 14:44:52 Tablet input-remapper-service[747]: Request to autoload for "Hengchangtong  HCT USB Entry Keyboard"
Feb 20 14:44:52 Tablet input-remapper-service[747]: Request to autoload for "Hengchangtong  HCT USB Entry Keyboard"
Feb 20 14:44:52 Tablet input-remapper-service[747]: Request to autoload for "Hengchangtong  HCT USB Entry Keyboard"
Feb 20 14:44:52 Tablet input-remapper-service[747]: Request to autoload for "Hengchangtong  HCT USB Entry Keyboard"
Feb 20 14:45:20 Tablet input-remapper-service[747]: Request to autoload for "Bluetooth 3.0 Keyboard"
Feb 20 14:45:21 Tablet input-remapper-service[747]: Found "Bluetooth 3.0 Keyboard", "Hengchangtong  HCT USB Entry Keyboard", "IPTS 1B96:0023", "input-remapper S>
Feb 20 14:45:42 Tablet input-remapper-service[747]: Request to autoload for "Bluetooth 3.0 Keyboard"
Feb 20 14:45:43 Tablet input-remapper-service[747]: Found "Bluetooth 3.0 Keyboard", "Hengchangtong  HCT USB Entry Keyboard", "IPTS 1B96:0023", "input-remapper S>
lines 1-22/22 (END)


```
user@Tablet:~$ input-remapper-control --command hello
Connected to the service
Daemon answered with "hello"
Done

```

user@Tablet:~$ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	2.4G Mouse
/dev/input/event10:	IPTS 1B96:0023
/dev/input/event11:	Surface Pro 3/4 Buttons
/dev/input/event12:	Video Bus
/dev/input/event13:	HDA Intel PCH Mic
/dev/input/event14:	HDA Intel PCH Headphone
/dev/input/event15:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event16:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event17:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event18:	IPTS 1B96:0023
/dev/input/event19:	IPTS 1B96:0023
/dev/input/event2:	2.4G Mouse
/dev/input/event20:	input-remapper keyboard
/dev/input/event21:	IPTS 1B96:0023
/dev/input/event22:	IPTS 1B96:0023
/dev/input/event23:	IPTS 1B96:0023
/dev/input/event24:	Hengchangtong  HCT USB Entry Keyboard
/dev/input/event25:	IPTS 1B96:0023
/dev/input/event256:	Bluetooth 3.0 Keyboard
/dev/input/event259:	input-remapper SEMICO USB Keyboard forwarded
/dev/input/event26:	IPTS 1B96:0023
/dev/input/event27:	Hengchangtong  HCT USB Entry Keyboard Consumer Control
/dev/input/event28:	IPTS 1B96:0023
/dev/input/event29:	Hengchangtong  HCT USB Entry Keyboard System Control
/dev/input/event3:	SEMICO USB Keyboard
/dev/input/event30:	Hengchangtong  HCT USB Entry Keyboard
/dev/input/event31:	input-remapper SEMICO USB Keyboard forwarded
/dev/input/event4:	IPTS 1B96:0023
/dev/input/event5:	SEMICO USB Keyboard Consumer Control
/dev/input/event6:	IPTS 1B96:0023
/dev/input/event7:	IPTS 1B96:0023
/dev/input/event8:	SEMICO USB Keyboard System Control
/dev/input/event9:	SEMICO USB Keyboard
Select the device event number [0-259]:

**Comment by mcg1103** [comment]
Not the original poster, but I am experience the same issue.   Ubuntu 22.04 gnome 42.5
root@marknb:/home/mark/.config/input-remapper/presets/PERIMICE-520# systemctl status input-remapper
● input-remapper-daemon.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/lib/systemd/system/input-remapper-daemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-02-25 11:35:22 MST; 6min ago
   Main PID: 5308 (input-remapper-)
      Tasks: 5 (limit: 18410)
     Memory: 25.9M
        CPU: 3.304s
     CGroup: /system.slice/input-remapper-daemon.service
             ├─5308 /usr/bin/python3 /usr/bin/input-remapper-service
             └─5309 /usr/bin/python3 /usr/bin/input-remapper-service

Feb 25 11:39:30 marknb input-remapper-service[5308]: Loaded config from "/home/mark/.config/input-remapper/config.json"
Feb 25 11:39:30 marknb input-remapper-service[5308]: Loaded config from "/home/mark/.config/input-remapper/config.json"
Feb 25 11:39:30 marknb input-remapper-service[5308]: Received "hello" from client
Feb 25 11:41:35 marknb input-remapper-service[5627]: ERROR: Failed to run injector coroutines: [Errno 19] No such device
Feb 25 11:41:53 marknb input-remapper-service[5308]: Request to autoload for "Chicony USB Keyboard"
Feb 25 11:41:54 marknb input-remapper-service[5308]: Found "Chicony USB Keyboard", "PERIMICE-520", "input-remapper mouse", "Video Bus", "Sy>
Feb 25 11:41:54 marknb input-remapper-service[5308]: Request to autoload for "Chicony USB Keyboard"
Feb 25 11:41:54 marknb input-remapper-service[5308]: Request to autoload for "PERIMICE-520"
Feb 25 11:41:54 marknb input-remapper-service[5308]: Request to autoload for "Chicony USB Keyboard"
Feb 25 11:41:54 marknb input-remapper-service[5308]: Request to autoload for "PERIMICE-520"



input-remapper-control --command hello
Starting logging to "/var/log/input-remapper-control"
Connected to the service
Daemon answered with "hello"
Done


evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Sleep Button
/dev/input/event1:	Lid Switch
/dev/input/event2:	Power Button
/dev/input/event3:	Power Button
/dev/input/event4:	AT Translated Set 2 keyboard
/dev/input/event5:	HP HD Camera: HP HD Camera
/dev/input/event6:	SYNA3063:00 06CB:826F Mouse
/dev/input/event7:	C270 HD WEBCAM
/dev/input/event8:	PERIMICE-520
/dev/input/event9:	PERIMICE-520 Keyboard
/dev/input/event10:	PERIMICE-520
/dev/input/event11:	Chicony USB Keyboard
/dev/input/event12:	Chicony USB Keyboard System Control
/dev/input/event13:	Wireless hotkeys
/dev/input/event14:	SYNA3063:00 06CB:826F Touchpad
/dev/input/event15:	ST LIS3LV02DL Accelerometer
/dev/input/event16:	Chicony USB Keyboard Consumer Control
/dev/input/event17:	HP WMI hotkeys
/dev/input/event18:	SynPS/2 Synaptics TouchPad
/dev/input/event19:	input-remapper keyboard
/dev/input/event20:	Video Bus
/dev/input/event21:	input-remapper gamepad
/dev/input/event22:	input-remapper mouse
/dev/input/event23:	HDA Intel PCH Mic
/dev/input/event24:	HDA Intel PCH Headphone
/dev/input/event25:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event26:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event27:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event28:	HDA Intel PCH HDMI/DP,pcm=9
/dev/input/event29:	HDA Intel PCH HDMI/DP,pcm=10

**Comment by mcg1103** [comment]
I did not have the autoload switch set.  remove my usb mouse and pug it back in and it is re-applying automatically now.
