### ISSUE TITLE
Mouse dpi changes

### ISSUE THREAD

**Issue by creeperpaint** [sezanzeb/input-remapper#640]
When injection is started, my mouse dpi goes up by a lot.

**Comment by sezanzeb** [comment]
Possibly related: https://github.com/sezanzeb/input-remapper/issues/358

Which desktop environment are you using?

Wayland or X11?

**Comment by creeperpaint** [comment]
X11 Plasma

**Comment by sezanzeb** [comment]
Allright, then this is a duplicate of #358. Closing it therefore
