### ISSUE TITLE
After updating Input mapper crashes on arch Linux

### ISSUE THREAD

**Issue by Kiaos** [sezanzeb/input-remapper#644]
I had installled this and had it working but it was a privious version. I had updated my steam deck so I had to do all the stuff to renable write mode so i could install openrazer-meta and all the other things I needed for my linux os. Now when I open Input remapper it shows a white icon loads a little then closes immediately.  

```
(deck@Kiaos-Deck ~)$ yay -S input-remapper-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  input-remapper-git-2.0.0.rc-1

  1 input-remapper-git               (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/0): input-remapper-git
  1 input-remapper-git               (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: input-remapper-git
==> Making package: input-remapper-git 2.0.0.rc-1 (Sat 04 Mar 2023 11:20:59 AM MST)
==> Retrieving sources...
  -> Updating input-remapper git repo...
==> Validating source files with md5sums...
    input-remapper ... Skipped
==> Making package: input-remapper-git 2.0.0.rc-1 (Sat 04 Mar 2023 11:21:02 AM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating input-remapper git repo...
==> Validating source files with md5sums...
    input-remapper ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of input-remapper git repo...
Cloning into 'input-remapper'...
done.
==> Starting pkgver()...
==> Updated version: input-remapper-git 1.5.0.r78.g4b50b240-1
==> Sources are ready.
==> Making package: input-remapper-git 1.5.0.r78.g4b50b240-1 (Sat 04 Mar 2023 11:21:07 AM MST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
 -> input-remapper-git-1.5.0.r78.g4b50b240-1 already made -- skipping build
 -> Found git repo: github.com/sezanzeb/input-remapper.git
[sudo] password for deck: 
loading packages...
warning: input-remapper-git-1.5.0.r78.g4b50b240-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) input-remapper-git-1.5.0.r78.g4b50b240-1

Total Installed Size:  1.13 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                [#######################################################] 100%
(1/1) checking package integrity                                                              [#######################################################] 100%
(1/1) loading package files                                                                   [#######################################################] 100%
(1/1) checking for file conflicts                                                             [#######################################################] 100%
(1/1) checking available disk space                                                           [#######################################################] 100%
:: Processing package changes...
(1/1) reinstalling input-remapper-git                                                         [#######################################################] 100%
:: Running post-transaction hooks...
(1/5) Reloading system manager configuration...
(2/5) Reloading device manager configuration...
(3/5) Arming ConditionNeedsUpdate...
(4/5) Reloading system bus configuration...
(5/5) Updating the desktop file MIME type cache...
(deck@Kiaos-Deck ~)$ ^C
(130)(deck@Kiaos-Deck ~)$ ```

**Comment by sezanzeb** [comment]
What is the log output of

`sudo pkill -f input-remapper && input-remapper-gtk -d` ?

**Comment by Kiaos** [comment]
‘’’ (deck@Kiaos-Deck ~)$ sudo pkill -f input-remapper && input-remapper-gtk 
[sudo] password for deck: 
Sorry, try again.
[sudo] password for deck: 
input-remapper-gtk 2.0.0-rc 4b50b240a5f429e31bd591aa5e7c5903cc4a736b https://github.com/sezanzeb/input-remapper
python-evdev 1.6.0
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 73, in <module>
    from inputremapper.gui.user_interface import UserInterface
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 31, in <module>
    from inputremapper.gui.autocompletion import Autocompletion
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/autocompletion.py", line 33, in <module>
    from inputremapper.gui.components.editor import CodeEditor
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/components/editor.py", line 29, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
(1)(deck@Kiaos-Deck ~)$ 
‘’’

**Comment by Kiaos** [comment]
ModuleNotFoundError: No module named 'cairo'
(1)(deck@Kiaos-Deck ~)$ lsudo pkill -f input-remapper && input-remapper-gtk -d
bash: lsudo: command not found
(127)(deck@Kiaos-Deck ~)$ sudo pkill -f input-remapper && input-remapper-gtk -d
[sudo] password for deck: 
11:52:03.984536 33099 GUI INFO logger.py:264: input-remapper-gtk 2.0.0-rc 4b50b240a5f429e31bd591aa5e7c5903cc4a736b https://github.com/sezanzeb/input-remapper
11:52:03.984717 33099 GUI INFO logger.py:272: python-evdev 1.6.0
11:52:03.984881 33099 GUI WARNING logger.py:275: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
11:52:03.984971 33099 GUI DEBUG input-remapper-gtk:67: Using locale directory: /usr/share/input-remapper/lang
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 73, in <module>
    from inputremapper.gui.user_interface import UserInterface
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/user_interface.py", line 31, in <module>
    from inputremapper.gui.autocompletion import Autocompletion
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/autocompletion.py", line 33, in <module>
    from inputremapper.gui.components.editor import CodeEditor
  File "/usr/lib/python3.10/site-packages/inputremapper/gui/components/editor.py", line 29, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
(1)(deck@Kiaos-Deck ~)$

**Comment by Kiaos** [comment]
After installing python-cairo it worked.

**Comment by sezanzeb** [comment]
Thanks, I added the dependency to the AUR package
