### ISSUE TITLE
Injection not working on v2.0

### ISSUE THREAD

**Issue by Suranovi** [sezanzeb/input-remapper#645]
Hello,

I used input-remapper for some years to use my Razer Tartaros V2. All worked fine until V2.0 was released. Now when i apply a profile, it seems to work but does not change the real key sent.

Please install the newest version from source to see if the problem has already been solved.

Share some logs please:

1. input-remapper-control --version
`input-remapper 2.0.0-rc 4b50b240a5f429e31bd591aa5e7c5903cc4a736b https://github.com/sezanzeb/input-remapper
python-evdev 1.6.1`
2. which linux distro (ubuntu 20.04, manjaro, etc.)
`OS: EndeavourOS Linux x86_64`
`Kernel: 6.2.2-zen1-1-zen `
`Shell: bash 5.1.16 `
`Resolution: 2560x1440, 2560x1440 `
`DE: GNOME 43.3 `
`WM: Mutter `
`CPU: AMD Ryzen 7 1800X (16) @ 3.800GHz `
`GPU: NVIDIA GeForce GTX 1660 Ti `
`Memory: 3358MiB / 15913MiB `

3. echo $XDG_SESSION_TYPE
`x11`
4. which desktop environment (gnome, plasma, xfce4, etc.)
`Gnome 43.3`
5. sudo ls -l /proc/1/exe
`lrwxrwxrwx 1 root root 0  5 mars  08:42 /proc/1/exe -> /usr/lib/systemd/systemd`
6. paste the affected preset .json file from ~/.config/input-remapper/presets
```
{
    "mapping": {
        "1,15,1": [
            "KEY_1",
            "keyboard"
        ],
        "1,16,1": [
            "KEY_2",
            "keyboard"
        ],
        "1,17,1": [
            "KEY_3",
            "keyboard"
        ],
        "1,18,1": [
            "KEY_4",
            "keyboard"
        ],
        "1,19,1": [
            "KEY_5",
            "keyboard"
        ],
        "1,58,1": [
            "KEY_6",
            "keyboard"
        ],
        "1,30,1": [
            "KEY_7",
            "keyboard"
        ],
        "1,31,1": [
            "KEY_8",
            "keyboard"
        ],
        "1,32,1": [
            "KEY_9",
            "keyboard"
        ],
        "1,33,1": [
            "KEY_0",
            "keyboard"
        ],
        "1,46,1": [
            "KEY_MINUS",
            "keyboard"
        ],
        "1,45,1": [
            "KEY_EQUAL",
            "keyboard"
        ],
        "1,44,1": [
            "b",
            "keyboard"
        ],
        "1,42,1": [
            "m",
            "keyboard"
        ],
        "1,6,1": [
            "KEY_LEFTCTRL + F5",
            "keyboard"
        ],
        "1,5,1": [
            "KEY_LEFTCTRL + F1",
            "keyboard"
        ],
        "1,4,1": [
            "KEY_LEFTCTRL + F3",
            "keyboard"
        ]
    }
} 
```
7. `sudo pkill -f input-remapper-service && input-remapper-gtk -d`, apply the preset and hit your key. Then share that log.
see attached file
8. `sudo evtest` while the previous command is running, to see how events are injected. Devices starting with `input-remapper ...` are of interest.
see attached file
[input-remapper_log.txt](https://github.com/sezanzeb/input-remapper/files/10891430/input-remapper_log.txt)
[input-remapper-evtext.txt](https://github.com/sezanzeb/input-remapper/files/10891433/input-remapper-evtext.txt)

**Comment by jonasBoss** [comment]
We forgot to update the issue templates, all the config files now live in the `~/.config/input-remapper-2` folder. Can you please post the presets from there?

**Comment by jonasBoss** [comment]
It might be related to this: #435 / #517

Can you try and re-record the input for a mapping, and see if that mapping will work?

**Comment by Suranovi** [comment]
Hi i tried to start input-remapper-gtk from console to see the output. There is a lot of warnings and one error when i inject:

ERROR: Combination <InputCombination (<InputConfig (1, 272) BTN_LEFT, None, None, at 0x7fbfe9f0c3a0>) at 0x7fbfe9f13400> not found. Available: [<InputCombination (<InputConfig (1, 15) KEY_TAB, None, None, at 0x7fbffa96b4c0>) at 0x7fbfe9ef1300>, <InputCombination (<InputConfig (1, 16) KEY_Q, None, None, at 0x7fbffa96b520>) at 0x7fbfe9efa280>, <InputCombination (<InputConfig (1, 17) KEY_W, None, None, at 0x7fbffa96b4f0>) at 0x7fbfe9efa380>, <InputCombination (<InputConfig (1, 18) KEY_E, None, None, at 0x7fbffa96b610>) at 0x7fbfe9efa400>, <InputCombination (<InputConfig (1, 19) KEY_R, None, None, at 0x7fbffa96b2e0>) at 0x7fbfe9efa480>, <InputCombination (<InputConfig (1, 58) KEY_CAPSLOCK, None, None, at 0x7fbffa96b280>) at 0x7fbfe9efa500>, <InputCombination (<InputConfig (1, 30) KEY_A, None, None, at 0x7fbffa96b430>) at 0x7fbfe9efa580>, <InputCombination (<InputConfig (1, 31) KEY_S, None, None, at 0x7fbffa96b070>) at 0x7fbfe9efa600>, <InputCombination (<InputConfig (1, 32) KEY_D, None, None, at 0x7fbffa96a350>) at 0x7fbfe9efa680>, <InputCombination (<InputConfig (1, 33) KEY_F, None, None, at 0x7fbffa968a00>) at 0x7fbfe9efa700>, <InputCombination (<InputConfig (1, 46) KEY_C, None, None, at 0x7fbffa969660>) at 0x7fbfe9efa780>, <InputCombination (<InputConfig (1, 45) KEY_X, None, None, at 0x7fbffa969720>) at 0x7fbfe9efa800>, <InputCombination (<InputConfig (1, 44) KEY_Z, None, None, at 0x7fbffa96b5b0>) at 0x7fbfe9efa880>, <InputCombination (<InputConfig (1, 42) KEY_LEFTSHIFT, None, None, at 0x7fbfe9ef6710>) at 0x7fbfe9efa940>, <InputCombination (<InputConfig (1, 6) KEY_5, None, None, at 0x7fbfe9ef6650>) at 0x7fbfe9efaa40>, <InputCombination (<InputConfig (1, 5) KEY_4, None, None, at 0x7fbfe9ef65f0>) at 0x7fbfe9efab40>, <InputCombination (<InputConfig (1, 4) KEY_3, None, None, at 0x7fbfe9ef6590>) at 0x7fbfe9efac40>]
Group "Razer Razer Tartarus V2" is currently mapped

**Comment by Suranovi** [comment]
Here is the config file from input-remapper-2
[WoW.json.txt](https://github.com/sezanzeb/input-remapper/files/10891715/WoW.json.txt)

**Comment by Suranovi** [comment]
I made a new template and recorded two keys. Injectioon works perfectly.
There still is an error (launched via console to have ouput like before), here is the output:

`ERROR: Combination <InputCombination (<InputConfig (1, 272) BTN_LEFT, None, None, at 0x7fbfe9f4a4d0>) at 0x7fbffa91db00> not found. Available: [<InputCombination (<InputConfig (1, 33) KEY_F, None, 1c332ce89014fcd594f273d3f7e6704d, at 0x7fbfe9ef4af0>) at 0x7fbffbac7c00>, <InputCombination (<InputConfig (1, 32) KEY_D, None, 1c332ce89014fcd594f273d3f7e6704d, at 0x7fbfe9f39f90>) at 0x7fbffa94da40>]
Group "Razer Razer Tartarus V2" is currently mapped
`

[Test New.json.txt](https://github.com/sezanzeb/input-remapper/files/10891718/Test.New.json.txt)

**Comment by jonasBoss** [comment]
> There still is an error (launched via console to have ouput like before)

That is a different error which is harmless for you.

You have two options to fix your issue:
 1. re-record all the inputs for the not working mappings
 2. manually add the `"origin_hash": "1c332ce89014fcd594f273d3f7e6704d"` field to all your mappings. Compare your presets, to see how to add them: [Test New.json.txt](https://github.com/sezanzeb/input-remapper/files/10891718/Test.New.json.txt) and [WoW.json.txt](https://github.com/sezanzeb/input-remapper/files/10891715/WoW.json.txt). Also make sure to get the commas right, json does not like missing or trailing commas.

**Comment by Suranovi** [comment]
> manually add the "origin_hash": "1c332ce89014fcd594f273d3f7e6704d" field to all your mappings. Compare your presets, to see how to add them: Test New.json.txt and WoW.json.txt. Also make sure to get the commas right, json does not like missing or trailing commas.

Just did that and it works fine. Thanks for the tip. If you need any other logs, just tell me, i'll be glad to help.

Can i close that issue ?

**Comment by jonasBoss** [comment]
Glad to hear everything worked out.
