### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Aqua1ung** [sezanzeb/input-remapper#648]
Would packaging _Input Remapper_ as a [.flatpak](https://flatpak.org/) application constitute a hugely time-consuming chore? Would you guys consider looking into this?

**Comment by sezanzeb** [comment]
Unfortunately this is not possible: https://github.com/sezanzeb/input-remapper/issues/21

**Comment by Aqua1ung** [comment]
There's [a new GUI tool](https://flathub.org/apps/details/com.github.tchx84.Flatseal) that might [help with permissions](https://www.techrepublic.com/article/manage-flatpak-permissions-flatseal/) for apps packaged as flatpak. Maybe you guys could take another stab at it?

[Here's also a thread](https://discourse.flathub.org/t/input-remapper-as-flatpak/3804) I started in the Flatpak forums, maybe we could get someone to lend some professional help ...
