### ISSUE TITLE
Device not grabbed

### ISSUE THREAD

**Issue by BootZ123** [sezanzeb/input-remapper#649]
I go through all the steps to map but nothing happens.  I have noticed in the bottom left corner it says "Device not grabbed".  What's going on?  Do I need to install other dependencies?

**Comment by sezanzeb** [comment]
Please run `sudo pkill -f input-remapper && input-remapper-gtk -d`, reproduce the problem and then share the output here.

**Comment by BootZ123** [comment]
I ran this in Terminal and it eventually opened up remapper.
I went through the steps to remap a mouse button to use shift and when I
click apply you see the message at the bottom left corner.

**Comment by sezanzeb** [comment]
You didn't share any output

**Comment by BootZ123** [comment]
This is everything that popped up in Terminal.
It asked for my password twice before finishing and opening up Input Mapper.

10:23:27.188853 8584 GUI INFO logger.py:264: input-remapper-gtk 2.0.0-rc
394c05dfe10215a62927f0eaaff3596d557fbc56
https://github.com/sezanzeb/input-remapper
10:23:27.188940 8584 GUI INFO logger.py:272: python-evdev 1.4.0
10:23:27.188986 8584 GUI WARNING logger.py:275: Debug level will log all
your keystrokes! Do not post this output in the internet if you typed in
sensitive or private information with your device!
10:23:27.189029 8584 GUI DEBUG input-remapper-gtk:67: Using locale
directory: /usr/share/input-remapper/lang
10:23:27.199478 8584 GUI DEBUG pipe.py:70: Creating new pipe for
"/tmp/input-remapper-bootz/reader-results"
10:23:27.199869 8584 GUI DEBUG pipe.py:70: Creating new pipe for
"/tmp/input-remapper-bootz/reader-commands"
10:23:27.200087 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.terminate: <function
ReaderClient.attach_to_events.<locals>.<lambda> at 0x7f0d68dcaf80>
10:23:27.200270 8584 GUI DEBUG reader_service.py:144: Running `pkexec
input-remapper-control --command start-reader-service -d`
10:23:55.366062 8588 control DEBUG input-remapper-control:233: Call for
"['/usr/bin/input-remapper-control', '--command', 'start-reader-service',
'-d']"
10:23:55.370565 8588 control DEBUG input-remapper-control:215: System is
booted
10:23:55.370629 8588 control DEBUG input-remapper-control:178: Running
`input-remapper-reader-service -d &`
10:23:55.371204 8588 control INFO input-remapper-control:263: Done
10:23:55.397657 8584 GUI INFO daemon.py:234: Starting the service
10:23:55.397738 8584 GUI DEBUG daemon.py:245: Running `pkexec
input-remapper-control --command start-daemon  -d`
10:23:55.544098 8598 reader-service DEBUG data.py:96: Found data at
"/usr/share/input-remapper"
10:23:55.552998 8598 reader-service DEBUG pipe.py:87: Using existing pipe
for "/tmp/input-remapper-bootz/reader-results"
10:23:55.553140 8598 reader-service DEBUG pipe.py:87: Using existing pipe
for "/tmp/input-remapper-bootz/reader-commands"
/usr/bin/input-remapper-reader-service:58: DeprecationWarning: There is no
current event loop
  loop = asyncio.get_event_loop()
10:23:55.553517 8598 reader-service DEBUG reader_service.py:154:
Discovering initial groups
10:23:55.553897 8598 reader-service DEBUG groups.py:354: Discovering device
paths
10:23:55.554254 8598 reader-service DEBUG groups.py:391: "HDA Intel PCH
Front Headphone" has no useful capabilities
10:23:55.554509 8598 reader-service DEBUG groups.py:391: "HDA Intel PCH
Line Out" has no useful capabilities
10:23:55.554759 8598 reader-service DEBUG groups.py:391: "HDA Intel PCH
Line" has no useful capabilities
10:23:55.554991 8598 reader-service DEBUG groups.py:391: "HDA Intel PCH
Rear Mic" has no useful capabilities
10:23:55.555195 8598 reader-service DEBUG groups.py:391: "HDA Intel PCH
Front Mic" has no useful capabilities
10:23:55.555514 8598 reader-service DEBUG groups.py:391: "HDA NVidia
HDMI/DP,pcm=7" has no useful capabilities
10:23:55.555748 8598 reader-service DEBUG groups.py:391: "HDA NVidia
HDMI/DP,pcm=3" has no useful capabilities
10:23:55.556101 8598 reader-service DEBUG groups.py:395: "Eee PC WMI
hotkeys" is denylisted
10:23:55.556354 8598 reader-service DEBUG groups.py:402: Found mouse
"Primax Kensington Eagle Trackball" at "/dev/input/event6", hash
"f5c5bb8170efbb480905436d9b3e90ab", key "3_1149_8264_usb-0000:00:14.0-8"
10:23:55.556626 8598 reader-service DEBUG groups.py:402: Found unknown "HID
04f3:0103 System Control" at "/dev/input/event5", hash
"988e0feb5e16c8967cca7719b2d9a7f5", key "3_1267_259_usb-0000:00:14.0-7"
10:23:55.556943 8598 reader-service DEBUG groups.py:402: Found unknown "HID
04f3:0103 Consumer Control" at "/dev/input/event4", hash
"665d68e88485e6b77b074cee10a9f739", key "3_1267_259_usb-0000:00:14.0-7"
10:23:55.557264 8598 reader-service DEBUG groups.py:402: Found keyboard
"HID 04f3:0103" at "/dev/input/event3", hash
"aebdcb1d9f7b8c76800f785594fd777b", key "3_1267_259_usb-0000:00:14.0-7"
10:23:55.557761 8598 reader-service DEBUG groups.py:402: Found unknown
"Sleep Button" at "/dev/input/event0", hash
"9cfc19c3c931a9d205fc3fa9d159a97e", key "25_0_3_PNP0C0E"
10:23:55.558016 8598 reader-service INFO groups.py:481: Found "Primax
Kensington Eagle Trackball", "HID 04f3:0103", "Sleep Button"
10:23:55.558273 8598 reader-service DEBUG reader_service.py:161: Sending
groups
10:23:55.558496 8598 reader-service DEBUG reader_service.py:193: Waiting
for commands
10:24:02.121925 8600 control DEBUG input-remapper-control:233: Call for
"['/usr/bin/input-remapper-control', '--command', 'start-daemon', '-d']"
10:24:02.126261 8600 control DEBUG input-remapper-control:215: System is
booted
10:24:02.126334 8600 control DEBUG input-remapper-control:178: Running
`input-remapper-service --hide-info -d &`
10:24:02.126933 8600 control INFO input-remapper-control:263: Done
10:24:02.298844 8625 service DEBUG data.py:96: Found data at
"/usr/share/input-remapper"
10:24:02.309733 8625 service DEBUG daemon.py:196: Creating daemon
10:24:02.309961 8625 service INFO global_config.py:109: Loaded config from
"/home/bootz/.config/input-remapper-2/config.json"
10:24:02.310050 8625 service DEBUG shared_dict.py:57: Starting SharedDict
process
10:24:02.312692 8626 service DEBUG shared_dict.py:63: SharedDict process
started
10:24:02.317072 8625 service DEBUG daemon.py:281: Running daemon
10:24:02.353382 8584 GUI DEBUG daemon.py:264: Telling service about
"/home/bootz/.config/input-remapper-2"
10:24:02.354627 8625 service INFO global_config.py:109: Loaded config from
"/home/bootz/.config/input-remapper-2/config.json"
10:24:02.355030 8584 GUI DEBUG global_uinputs.py:135: Creating
FrontendUInputs
10:24:02.355117 8584 GUI DEBUG global_uinputs.py:103: creating fake UInput
device: "input-remapper keyboard"
10:24:02.355186 8584 GUI DEBUG global_uinputs.py:103: creating fake UInput
device: "input-remapper gamepad"
10:24:02.355252 8584 GUI DEBUG global_uinputs.py:103: creating fake UInput
device: "input-remapper mouse"
10:24:02.355308 8584 GUI DEBUG global_uinputs.py:103: creating fake UInput
device: "input-remapper keyboard + mouse"
10:24:02.355434 8584 GUI INFO global_config.py:109: Loaded config from
"/home/bootz/.config/input-remapper-2/config.json"
10:24:02.355514 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.groups: <bound method Controller._on_groups_changed of
<inputremapper.gui.controller.Controller object at 0x7f0d68e42530>>
10:24:02.355585 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method Controller._on_preset_changed of
<inputremapper.gui.controller.Controller object at 0x7f0d68e42530>>
10:24:02.355648 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.init: <bound method Controller._on_init of
<inputremapper.gui.controller.Controller object at 0x7f0d68e42530>>
10:24:02.355708 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method
Controller._publish_mapping_errors_as_status_msg of
<inputremapper.gui.controller.Controller object at 0x7f0d68e42530>>
10:24:02.355768 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
Controller._publish_mapping_errors_as_status_msg of
<inputremapper.gui.controller.Controller object at 0x7f0d68e42530>>
10:24:02.355871 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.terminate: <function
UserInterface.__init__.<locals>.<lambda> at 0x7f0d68e5a050>
10:24:02.430883 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.groups: <bound method
DeviceGroupSelection._on_groups_changed of
<inputremapper.gui.components.device_groups.DeviceGroupSelection object at
0x7f0d68e425f0>>
10:24:02.430971 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.group: <bound method DeviceGroupSelection._on_group_changed
of <inputremapper.gui.components.device_groups.DeviceGroupSelection object
at 0x7f0d68e425f0>>
10:24:02.431059 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.group: <bound method PresetSelection._on_group_changed of
<inputremapper.gui.components.presets.PresetSelection object at
0x7f0d68e430d0>>
10:24:02.431111 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method PresetSelection._on_preset_changed of
<inputremapper.gui.components.presets.PresetSelection object at
0x7f0d68e430d0>>
10:24:02.431395 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method MappingListBox._on_preset_changed of
<inputremapper.gui.components.editor.MappingListBox object at
0x7f0d68e43280>>
10:24:02.431449 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method MappingListBox._on_mapping_changed
of <inputremapper.gui.components.editor.MappingListBox object at
0x7f0d68e43280>>
10:24:02.431527 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.uinputs: <bound method TargetSelection._on_uinputs_changed
of <inputremapper.gui.components.editor.TargetSelection object at
0x7f0d68e42ec0>>
10:24:02.431584 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method TargetSelection._on_mapping_loaded
of <inputremapper.gui.components.editor.TargetSelection object at
0x7f0d68e42ec0>>
10:24:02.431668 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.group: <bound method Breadcrumbs._on_group_changed of
<inputremapper.gui.components.common.Breadcrumbs object at 0x7f0d68e42d70>>
10:24:02.431714 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method Breadcrumbs._on_preset_changed of
<inputremapper.gui.components.common.Breadcrumbs object at 0x7f0d68e42d70>>
10:24:02.431753 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method Breadcrumbs._on_mapping_changed of
<inputremapper.gui.components.common.Breadcrumbs object at 0x7f0d68e42d70>>
10:24:02.431891 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.group: <bound method Breadcrumbs._on_group_changed of
<inputremapper.gui.components.common.Breadcrumbs object at 0x7f0d68e42da0>>
10:24:02.431935 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method Breadcrumbs._on_preset_changed of
<inputremapper.gui.components.common.Breadcrumbs object at 0x7f0d68e42da0>>
10:24:02.432026 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method Breadcrumbs._on_mapping_changed of
<inputremapper.gui.components.common.Breadcrumbs object at 0x7f0d68e42da0>>
10:24:02.432240 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.do_stack_switch: <bound method Stack._do_stack_switch of
<inputremapper.gui.components.main.Stack object at 0x7f0d68e42bf0>>
10:24:02.432321 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.recording_finished: <bound method
RecordingToggle._on_recording_finished of
<inputremapper.gui.components.editor.RecordingToggle object at
0x7f0d68e42d10>>
10:24:02.432390 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method RequireActiveMapping._on_preset of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e42e60>>
10:24:02.432433 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method RequireActiveMapping._on_mapping of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e42e60>>
10:24:02.432891 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.status_msg: <bound method StatusBar._on_status_update of
<inputremapper.gui.components.main.StatusBar object at 0x7f0d68e42e90>>
10:24:02.432956 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.recording_started: <bound method
RecordingStatus._on_recording_started of
<inputremapper.gui.components.editor.RecordingStatus object at
0x7f0d68e42920>>
10:24:02.433005 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.recording_finished: <bound method
RecordingStatus._on_recording_finished of
<inputremapper.gui.components.editor.RecordingStatus object at
0x7f0d68e42920>>
10:24:02.433225 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method AutoloadSwitch._on_preset_changed of
<inputremapper.gui.components.editor.AutoloadSwitch object at
0x7f0d68e42980>>
10:24:02.433288 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
ReleaseCombinationSwitch._on_mapping_changed of
<inputremapper.gui.components.editor.ReleaseCombinationSwitch object at
0x7f0d68e42b90>>
10:24:02.433340 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
CombinationListbox._on_mapping_changed of
<inputremapper.gui.components.editor.CombinationListbox object at
0x7f0d68e43430>>
10:24:02.433381 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.selected_event: <bound method
CombinationListbox._on_event_changed of
<inputremapper.gui.components.editor.CombinationListbox object at
0x7f0d68e43430>>
10:24:02.433432 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.selected_event: <bound method AnalogInputSwitch._on_event
of <inputremapper.gui.components.editor.AnalogInputSwitch object at
0x7f0d68e434f0>>
10:24:02.433916 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.selected_event: <bound method
TriggerThresholdInput._on_event of
<inputremapper.gui.components.editor.TriggerThresholdInput object at
0x7f0d68e43550>>
10:24:02.434292 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
RelativeInputCutoffInput._on_mapping_message of
<inputremapper.gui.components.editor.RelativeInputCutoffInput object at
0x7f0d68e43640>>
10:24:02.434881 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
OutputAxisSelector._on_mapping_message of
<inputremapper.gui.components.editor.OutputAxisSelector object at
0x7f0d68e43760>>
10:24:02.434937 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.uinputs: <bound method
OutputAxisSelector._on_uinputs_message of
<inputremapper.gui.components.editor.OutputAxisSelector object at
0x7f0d68e43760>>
10:24:02.435000 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
KeyAxisStackSwitcher._on_mapping_message of
<inputremapper.gui.components.editor.KeyAxisStackSwitcher object at
0x7f0d68e43790>>
10:24:02.435066 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
ReleaseTimeoutInput._on_mapping_message of
<inputremapper.gui.components.editor.ReleaseTimeoutInput object at
0x7f0d68e437f0>>
10:24:02.435245 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
TransformationDrawArea._on_mapping_message of
<inputremapper.gui.components.editor.TransformationDrawArea object at
0x7f0d68e439a0>>
10:24:02.435785 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method Sliders._on_mapping_message of
<inputremapper.gui.components.editor.Sliders object at 0x7f0d68e43a00>>
10:24:02.435863 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method RequireActiveMapping._on_preset of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e43c40>>
10:24:02.435911 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method RequireActiveMapping._on_mapping of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e43c40>>
10:24:02.435982 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method RequireActiveMapping._on_preset of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e43c70>>
10:24:02.436037 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method RequireActiveMapping._on_mapping of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e43c70>>
10:24:02.436086 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.preset: <bound method RequireActiveMapping._on_preset of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e43cd0>>
10:24:02.436124 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method RequireActiveMapping._on_mapping of
<inputremapper.gui.components.editor.RequireActiveMapping object at
0x7f0d68e43cd0>>
10:24:02.436392 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method CodeEditor._on_mapping_loaded of
<inputremapper.gui.components.editor.CodeEditor object at 0x7f0d68e43d30>>
10:24:02.436444 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.recording_finished: <bound method
CodeEditor._on_recording_finished of
<inputremapper.gui.components.editor.CodeEditor object at 0x7f0d68e43d30>>
10:24:02.437237 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method Autocompletion._on_mapping_changed
of <autocompletion.Autocompletion object at 0x7f0d68bf3940 (Autocompletion
at 0x560f464d8630)>>
10:24:02.437297 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.uinputs: <bound method Autocompletion._on_uinputs_changed
of <autocompletion.Autocompletion object at 0x7f0d68bf3940 (Autocompletion
at 0x560f464d8630)>>
10:24:02.437530 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.mapping: <bound method
UserInterface.update_combination_label of
<inputremapper.gui.user_interface.UserInterface object at 0x7f0d68e42590>>
10:24:02.437584 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.injector_state: <bound method
UserInterface.on_injector_state_msg of
<inputremapper.gui.user_interface.UserInterface object at 0x7f0d68e42590>>
10:24:02.437629 8584 GUI DEBUG message_broker.py:97: adding new Listener
for MessageType.user_confirm_request: <bound method
UserInterface._on_user_confirm_request of
<inputremapper.gui.user_interface.UserInterface object at 0x7f0d68e42590>>
10:24:02.536615 8584 GUI DEBUG reader_client.py:141: received {'type':
'status', 'message': 'ready'}
10:24:02.536814 8584 GUI DEBUG reader_client.py:141: received {'type':
'groups', 'message': '["{\\"paths\\": [\\"/dev/input/event6\\"],
\\"names\\": [\\"Primax Kensington Eagle Trackball\\"], \\"types\\":
[\\"mouse\\"], \\"key\\": \\"Primax Kensington Eagle Trackball\\"}",
"{\\"paths\\": [\\"/dev/input/event5\\", \\"/dev/input/event4\\",
\\"/dev/input/event3\\"], \\"names\\": [\\"HID 04f3:0103 System Control\\",
\\"HID 04f3:0103 Consumer Control\\", \\"HID 04f3:0103\\"], \\"types\\":
[\\"keyboard\\"], \\"key\\": \\"HID 04f3:0103\\"}", "{\\"paths\\":
[\\"/dev/input/event0\\"], \\"names\\": [\\"Sleep Button\\"], \\"types\\":
[], \\"key\\": \\"Sleep Button\\"}"]'}
10:24:02.537531 8584 GUI DEBUG groups.py:354: Discovering device paths
10:24:02.538416 8584 GUI DEBUG groups.py:478: Did not find any input device
10:24:02.538931 8584 GUI DEBUG reader_client.py:287: Received 3 devices
10:24:02.539637 8584 GUI DEBUG message_broker.py:76: from
reader_client.py:282: Signal=groups: GroupsData(groups={'Primax Kensington
Eagle Trackball': [<DeviceType.MOUSE: 'mouse'>], 'HID 04f3:0103':
[<DeviceType.KEYBOARD: 'keyboard'>], 'Sleep Button': []})
10:24:02.540549 8584 GUI INFO data_manager.py:297: Loading group "Primax
Kensington Eagle Trackball"
10:24:02.542917 8584 GUI INFO data_manager.py:315: Loading preset "new
preset"
10:24:02.543075 8584 GUI INFO preset.py:143: Loading preset from
"/home/bootz/.config/input-remapper-2/presets/Primax Kensington Eagle
Trackball/new preset.json"
10:24:02.543205 8584 GUI DEBUG preset.py:289: got empty file
10:24:02.543525 8584 GUI DEBUG device_groups.py:102: adding Primax
Kensington Eagle Trackball to device selection
10:24:02.544692 8584 GUI DEBUG device_groups.py:102: adding HID 04f3:0103
to device selection
10:24:02.545358 8584 GUI DEBUG device_groups.py:102: adding Sleep Button to
device selection
10:24:02.546348 8584 GUI DEBUG message_broker.py:76: from
data_manager.py:100: Signal=group: GroupData(group_key='Primax Kensington
Eagle Trackball', presets=('new preset',))
10:24:02.546843 8584 GUI DEBUG message_broker.py:76: from
data_manager.py:158: Signal=injector_state:
InjectorStateMessage(state='UNKNOWN')
10:24:02.547100 8584 GUI DEBUG message_broker.py:76: from
data_manager.py:111: Signal=preset: PresetData(name='new preset',
mappings=[], autoload=False)
10:24:02.549222 8584 GUI DEBUG message_broker.py:76: from
controller.py:159: Signal=status_msg: StatusData(ctx_id=5, msg=None,
tooltip=None)
10:24:02.549469 8584 GUI DEBUG message_broker.py:76: from
controller.py:147: Signal=mapping: {'target_uinput': 'keyboard'}
10:24:02.553836 8584 GUI DEBUG message_broker.py:76: from
controller.py:159: Signal=status_msg: StatusData(ctx_id=5, msg=None,
tooltip=None)
10:24:02.556254 8584 GUI DEBUG message_broker.py:76: from
input-remapper-gtk:98: Signal=init: Signal: MessageType.init
10:24:02.556491 8584 GUI DEBUG message_broker.py:76: from
reader_client.py:282: Signal=groups: GroupsData(groups={'Primax Kensington
Eagle Trackball': [<DeviceType.MOUSE: 'mouse'>], 'HID 04f3:0103':
[<DeviceType.KEYBOARD: 'keyboard'>], 'Sleep Button': []})
10:24:02.556607 8584 GUI DEBUG controller.py:123: A group is already active
10:24:02.557102 8584 GUI DEBUG device_groups.py:102: adding Primax
Kensington Eagle Trackball to device selection
10:24:02.557687 8584 GUI DEBUG device_groups.py:102: adding HID 04f3:0103
to device selection
10:24:02.558188 8584 GUI DEBUG device_groups.py:102: adding Sleep Button to
device selection
10:24:02.558667 8584 GUI DEBUG message_broker.py:76: from
data_manager.py:140: Signal=uinputs: UInputsData(uinputs={'keyboard': {1:
[0, ... 700]}, 'gamepad': {1: [304, ... 318], 3: [(0, AbsInfo(value=0,
min=-32768, max=32768, fuzz=0, flat=0, resolution=0)), (1, AbsInfo(value=0,
min=-32768, max=32768, fuzz=0, flat=0, resolution=0)), (2, AbsInfo(value=0,
min=-32768, max=32768, fuzz=0, flat=0, resolution=0)), (3, AbsInfo(value=0,
min=-32768, max=32768, fuzz=0, flat=0, resolution=0)), (4, AbsInfo(value=0,
min=-32768, max=32768, fuzz=0, flat=0, resolution=0)), (5, AbsInfo(value=0,
min=-32768, max=32768, fuzz=0, flat=0, resolution=0)), (16,
AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0)), (17,
AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0))]}, 'mouse':
{1: [272, ... 279], 2: [0, ... 12]}, 'keyboard + mouse': {1: [0, ... 279],
2: [0, ... 12]}})
10:24:04.422990 8584 GUI DEBUG system_mapping.py:128: Gathering available
keycodes
10:24:04.423299 8584 GUI DEBUG system_mapping.py:128: Gathering available
keycodes
10:24:04.431154 8584 GUI DEBUG system_mapping.py:114: Writing
"/home/bootz/.config/input-remapper-2/xmodmap.json"
10:24:04.432762 8584 GUI DEBUG system_mapping.py:128: Gathering available
keycodes
10:24:04.441306 8584 GUI DEBUG system_mapping.py:114: Writing
"/home/bootz/.config/input-remapper-2/xmodmap.json"
10:24:04.466545 8584 GUI DEBUG system_mapping.py:114: Writing
"/home/bootz/.config/input-remapper-2/xmodmap.json"

**Comment by sezanzeb** [comment]
Weird, when I hit "apply" a `Request to start injecting` log appears. I can't find that in the output that you posted

**Comment by BootZ123** [comment]
Could it be a service that is messing it up?
I guess I could always reinstall Mint and try again.
Did you see anything in the output from terminal?

**Comment by sezanzeb** [comment]
My best guess is that when recording above logs, you didn't click on the "apply" button to reproduce the issue.

**Comment by BootZ123** [comment]
I was trying to set up the extra mouse keys with "xbindkeys" and the
associated programs before trying Input
Mapper.
I could set up two extra keys to do what I wanted but could never get
"Shift" mapped to one of the mouse buttons.
I disabled .xbindkeysrc file before trying Input Mapper.
Maybe that's the problem, who knows.

**Comment by Lazerbeak1409** [comment]
**OS:** Manjaro KDE
**Kernel:** 6.1.12-1-MANJARO
**Devices used:** Razer Tartarus V2
**Software version:** 2.0.0.rc.r5.gd0cc1b82-1
**Steps Taken:** Ran debug `sudo pkill -f input-remapper && input-remapper-gtk -d` command, attempted to map Esc key to Tab key on device, recorded output info from terminal to .txt file, redacted username from log.
**Console Output:** [DebugOutput.txt](https://github.com/sezanzeb/input-remapper/files/10952622/DebugOutput.txt)

Unfortunately am also experiencing this issue since the 2.0RC update. Was able to assign mappings a few weeks ago. Tried isolating other factors that may be at play such as other processes not releasing the device to be remapped, but I've had no luck.

**Comment by sezanzeb** [comment]
Can you please make a screenshot of the mapping from tab to esc?

```
20:54:03.082451 40967 service ERROR preset.py:307: failed to Validate mapping for [{'type': 1, 'code': 15, 'origin_hash': '14da034034145b8d838d229b065658bc'}]: 2 validation errors for Mapping
__root__
  Missing Argument: Mapping must either contain `output_symbol` or `output_type` and `output_code` (type=value_error.outputsymbolvariant)
__root__
  missing macro or key (type=value_error.missingmacroorkey)
```

**Comment by BootZ123** [comment]
It's working now.
I re-installed mint.
Thanks for all the help.

**Comment by sezanzeb** [comment]
The logs tell me that you forgot to program the output.

**Comment by Lazerbeak1409** [comment]
> Can you please make a screenshot of the mapping from tab to esc?
> 
> ```
> 20:54:03.082451 40967 service ERROR preset.py:307: failed to Validate mapping for [{'type': 1, 'code': 15, 'origin_hash': '14da034034145b8d838d229b065658bc'}]: 2 validation errors for Mapping
> __root__
>   Missing Argument: Mapping must either contain `output_symbol` or `output_type` and `output_code` (type=value_error.outputsymbolvariant)
> __root__
>   missing macro or key (type=value_error.missingmacroorkey)
> ```

[Peek 2023-03-13 12-26.webm](https://user-images.githubusercontent.com/95194614/224764881-ed429629-aced-4599-85ae-db836e6621cb.webm)

I recorded a webm of what I'm doing when the issue occurs. Honestly hoping it's just user error on my part somehow, but I don't see what else I'd be doing wrong. On my end, I open up input remapper, select the device, go to add and record which button I want replaced on the keypad, then set it to look for a keyboard input and press Esc.

**Comment by sezanzeb** [comment]
Oh I just realized I was talking to two different people, sorry.

There is two things I'd want to improve:
1. probably most people want to use the "key or macro" function by default
2. placeholder in the textbox

**Comment by DestoGit** [comment]
> > Can you please make a screenshot of the mapping from tab to esc?
> > ```
> > 20:54:03.082451 40967 service ERROR preset.py:307: failed to Validate mapping for [{'type': 1, 'code': 15, 'origin_hash': '14da034034145b8d838d229b065658bc'}]: 2 validation errors for Mapping
> > __root__
> >   Missing Argument: Mapping must either contain `output_symbol` or `output_type` and `output_code` (type=value_error.outputsymbolvariant)
> > __root__
> >   missing macro or key (type=value_error.missingmacroorkey)
> > ```
> 
> Peek.2023-03-13.12-26.webm
> 
> I recorded a webm of what I'm doing when the issue occurs. Honestly hoping it's just user error on my part somehow, but I don't see what else I'd be doing wrong. On my end, I open up input remapper, select the device, go to add and record which button I want replaced on the keypad, then set it to look for a keyboard input and press Esc.
> 
> Edit: Nevermind, I am stupid! Realize now there's a space to type in the key I'm trying to remap and that my theme makes it hard to see. Thanks for your patience with me [@sezanzeb](https://github.com/sezanzeb)

Solution:

You must type the Key name in the 'Enter your output here' input field, pressing the key is not enough (it just give you the key name cue)
https://github.com/sezanzeb/input-remapper/issues/1022#issuecomment-2563647427

Examples:
https://youtu.be/uSzNe9wy1oc?t=65

**Comment by sezanzeb** [comment]
> there's a space to type in the key I'm trying to remap and that my theme makes it hard to see

This happens sometimes with other people as well, the UI should be improved. Maybe if someone ever makes a new qt UI, they could figure out a better solution https://github.com/sezanzeb/input-remapper/issues/526
