### ISSUE TITLE
ModuleNotFoundError: No module named 'inputremapper.data'

### ISSUE THREAD

**Issue by heike-hh** [sezanzeb/input-remapper#655]
(K)ubuntu 22.04.2 fresh installation 
Input-remapper 1.4 from official .deb package for Ubuntu
No GUI

user@PC1:~$ sudo pkill -f input-remapper && input-remapper-gtk -d
[sudo] Passwort für heike: 
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 29, in <module>
    from inputremapper.data import get_data_path
ModuleNotFoundError: No module named 'inputremapper.data'

used input-remapper with (K)ubuntu 22.04.5 without problems

**Comment by sezanzeb** [comment]
Please post the output of:

1. `find /usr/ -iname "*input*remapper*"`

2. `python3 -c "import sys; print(sys.path)"`

3. `python3 -c "import inputremapper"`

**Comment by heike-hh** [comment]
thank you very much for helping me

user@PC1:~$ find /usr/ -iname "*input*remapper*"
/usr/local/lib/python3.10/dist-packages/input_remapper-2.0.0rc0.egg-info
/usr/local/lib/python3.10/dist-packages/inputremapper
/usr/bin/input-remapper-helper
/usr/bin/input-remapper-gtk
/usr/bin/input-remapper-service
/usr/bin/input-remapper-control
/usr/share/polkit-1/actions/input-remapper.policy
/usr/share/applications/input-remapper.desktop
/usr/share/doc/input-remapper-gtk
/usr/share/doc/python3-inputremapper
/usr/share/doc/input-remapper
/usr/share/doc/input-remapper-daemon
/usr/share/input-remapper
/usr/share/input-remapper/99-input-remapper.rules
/usr/share/input-remapper/input-remapper.desktop
/usr/share/input-remapper/input-remapper.policy
/usr/share/input-remapper/input-remapper.service
/usr/share/input-remapper/input-remapper.svg
/usr/share/input-remapper/input-remapper-autoload.desktop
/usr/share/input-remapper/input-remapper.glade
/usr/share/input-remapper/input-remapper-large.png
/usr/share/input-remapper/lang/it_IT/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/sk_SK/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/inputremapper.Control.conf
/usr/lib/udev/rules.d/60-input-remapper-daemon.rules
/usr/lib/systemd/system/input-remapper-daemon.service
/usr/lib/python3/dist-packages/input_remapper-1.4.0.egg-info
/usr/lib/python3/dist-packages/inputremapper

user@PC1:~$ python3 -c "import sys; print(sys.path)"
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages']

user@PC1:~$ python3 -c "import inputremapper"
user@PC1:~$

**Comment by heike-hh** [comment]
crazy, i see this message when shutting down
![input](https://user-images.githubusercontent.com/67012159/224848223-617b01c6-6044-45fb-933b-42ad978f3a9b.png)

**Comment by sezanzeb** [comment]
The first output shows, that you had 2.0.0-rc installed, and the files were placed in in `/usr/local/lib/python3.10/dist-packages/inputremapper`

In the second output, it can be seen that `'/usr/local/lib/python3.10/dist-packages'` has priority over `'/usr/lib/python3/dist-packages'`

So when you start inputremapper 1.4.0 it will try to import the 1.4.0 package, but instead finds the 2.0.0-rc packages and loads those instead. In 2.0.0-rc the folder structure is different, so inputremapper.data can't be imported.

Uninstall inputremapper 2.0.0-rc to solve it. I don't know if `pip uinstall` can fix the confusion, but you can also just remove those files by doing

```bash
sudo rm /usr/local/lib/python3.10/dist-packages/input_remapper-2.0.0rc0.egg-info /usr/local/lib/python3.10/dist-packages/inputremapper -r
```

afterwards it will hopefully work.

**Comment by sezanzeb** [comment]
[build.sh for the .deb file](https://github.com/sezanzeb/input-remapper/blob/main/scripts/build.sh) places those in `/usr/local/lib`. Maybe this should be changed. I think two years ago there was a reason for that, but I don't remember it.

**Comment by heike-hh** [comment]
now it's working. You made an old lady happy. Thanks very much
I mean I installed with python3 setup.py install. I'm not very familiar with sh
