### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by Mte90** [sezanzeb/input-remapper#664]
Players on SteamDeck are looking on how to remap buttons for macros and so on but as it is ArchLinux it would be more handy a flatpak package.
I wrote a guide on how to install OpenRazer there and people asks me about a way to remap buttons https://daniele.tech/2022/12/how-to-get-openrazer-working-easily-on-steam-deck/

**Comment by sezanzeb** [comment]
It seems input-remapper cannot be released as a flatpak package: https://github.com/flatpak/flatpak/issues/4137

> If you don't have a particular privilege (for example access to /dev/uinput) before entering the Flatpak sandbox, then you still won't have that privilege inside the sandbox.

unless maybe someone tinkers with user permissions. Maybe if a user is part of the `input` group it makes a difference, I wonder if the service has to start as root at all then. I don't know how reasonable this is to ask flatpak users to change their user group if they intend to use it via flatpak, or if it ends up working at all. In any case, this should be discussed here instead: https://github.com/sezanzeb/input-remapper/issues/21

**Comment by bayazidbh** [comment]
https://github.com/flatpak/flatpak/releases/tag/1.15.6
https://github.com/flatpak/flatpak/pull/5481

There seems to be a `--device=input` access now @sezanzeb?

**Comment by sezanzeb** [comment]
It's probably better to continue this discussion in the old pull request: https://github.com/sezanzeb/input-remapper/pull/31

Could you please leave a comment there?
