### ISSUE TITLE
/if_single()'s > else-condition/ does not work on the first invocation

### ISSUE THREAD

**Issue by pablos-here** [sezanzeb/input-remapper#666]
Hi,

I created a macro for `Space bar` as follows:

1. If tapped quickly, generate a `Space`
2. Else emulate holding the `Control L` key.

Using `cat -v` to test, on a new line, if the `Space bar` is held down and a character is typed, the `Control L` is not generated.  Only the character is written.

While continuing to hold down the `Space bar`, typing another character, the `Control L` is generated so that a control character is written.

For example, if below is what I would see in `cat -v`'s first line if I hold down the `Space bar` and type two `a`s:

```shell
cat -v
a^A
```

What I would expect is the following:

```shell
cat -v
^A^A
```

> Please install the newest version from source to see if the problem has already been solved.

Done!

> Share some logs please:
> 
> 1. `input-remapper-control --version`

```
$ input-remapper-control --version     
input-remapper 2.0.0  https://github.com/sezanzeb/input-remapper
python-evdev 1.6.1
```

> 2. which linux distro (ubuntu 20.04, manjaro, etc.)

`openSUSE Tumbleweed - 20230319`

> 3. `echo $XDG_SESSION_TYPE`

`x11`

> 4. which desktop environment (gnome, plasma, xfce4, etc.)

`KDE`

> 5. `sudo ls -l /proc/1/exe`

```
# ls -l /proc/1/exe
lrwxrwxrwx 1 root root 0 2023-03-25 19:58 /proc/1/exe -> /usr/lib/systemd/systemd*
```

> 6. paste the affected preset .json file from ~/.config/input-remapper-2/presets

```json
$ cat My\ keyboard.json                  
[
    {
        "input_combination": [
            {
                "type": 1,
                "code": 58,
                "origin_hash": "650869084d234c8ce49bb632f09ccf3e"
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "if_tap( key( Escape ), key( Caps_Lock ), 110 )",
        "name": "Caps_lock",
        "mapping_type": "key_macro"
    },
    {
        "input_combination": [
            {
                "type": 1,
                "code": 57,
                "origin_hash": "650869084d234c8ce49bb632f09ccf3e"
            }
        ],
        "target_uinput": "keyboard",
        "output_symbol": "if_single( key( space ), hold( Control_L ), None )",
        "name": "Space_bar",
        "mapping_type": "key_macro"
    }
]
```
>  7. `sudo pkill -f input-remapper-service && input-remapper-gtk -d`, apply the preset and hit your key. Then share that log.

[debug.log](https://github.com/sezanzeb/input-remapper/files/11070573/debug.log)

>  8. `sudo evtest` while the previous command is running, to see how events are injected. Devices starting with `input-remapper ...` are of interest.

Hmm, this command is not installed on my system.

**Comment by jonasBoss** [comment]
This is due to a race condition the macro does execute, but unfortunately it does not execute before the key is pressed.

**Comment by pablos-here** [comment]
Thank you for quick turn-around.  Resolved!
