### ISSUE TITLE
Project license - GPLv3 vs GPLv3+

### ISSUE THREAD

**Issue by alxpl** [sezanzeb/input-remapper#674]
It was pointed out to me on the review ticket that I had made a blunder with the package license. While setting the correct license identifier, I noticed that all of the source headers that mention a license they use GPL-3.0-or-later, whereas the project license does not mention the "or later" option.
Taking into consideration [past advice from RH's legal,](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/N53I6BXKTPR2YQRLGBIL52FHUM4VIQBA/) I set the package license to GPL-3.0-or-later. That being said, since there is no later version of the GPL than v3 at the moment, [GitHub suggests](https://choosealicense.com/licenses/gpl-3.0/) adding the identifier to the package's description.
Was I right to assume you intended to use the -or-later option or should I switch to -only?

**Comment by sezanzeb** [comment]
I think I got the file headers from the `LICENSE`file. In line 640 it mentions the "later version"

**Comment by alxpl** [comment]
Thanks, so I'll stick with the GPL-3.0-or-later identifier.
