### ISSUE TITLE
Add "Script" as output type

### ISSUE THREAD

**Issue by jnyheim** [sezanzeb/input-remapper#690]
Add a "Script" as output type to create advanced macros
And under target add Shell and or Python.

### Input: 
```
MACRO7
```

### Output:
Type == Script
Target == Shell
```sh
dolphin ~/Projects
```

**Comment by sezanzeb** [comment]
This is probably a duplicate of https://github.com/sezanzeb/input-remapper/issues/500, there are some architectural difficulties with this
