### ISSUE TITLE
legacy-install-failure during installation on Fedora 38

### ISSUE THREAD

**Issue by realgooseman** [sezanzeb/input-remapper#705]
**Configuration :** 
Fedora 38 Workstation
Linux Kernel : Linux 6.2.14-300.fc38.x86_6
GNOME : 44.1 / Wayland

As a Linux noob who's still discovering everything, I followed the steps to install input-remapper. But I encountered an error during installation. I entered these commands without a problem : 

`sudo pip install evdev -U  # If newest version not in distros repo`
`sudo pip uninstall key-mapper  # In case the old package is still installed`

But after this command : `sudo pip install --no-binary :all: git+https://github.com/sezanzeb/input-remapper.git`

**I got this error : [input-remapper error.txt](https://github.com/sezanzeb/input-remapper/files/11460608/input-remapper.error.txt)** 

**Note :** I got all the dependencies, I also followed an older issue request [here](https://github.com/sezanzeb/input-remapper/issues/181#issuecomment-926023212) where I succesfully cloned the git and got this error after trying to enable key-mapper : **Failed to enable unit: Unit file key-mapper.service does not exist.**

**So my question is :** Is there a problem with the source ? A problem with Fedora/Wayland (maybe doesn't support input-remapper) or did I just do something wrong ?

**Comment by sezanzeb** [comment]
Try `sudo dnf install input-remapper` instead

**Comment by sezanzeb** [comment]
Or install gettext (https://src.fedoraproject.org/rpms/gettext)
