### ISSUE TITLE
Not reading inputs.

### ISSUE THREAD

**Issue by Banacizo** [sezanzeb/input-remapper#715]
Hello, I've been trying to remap my tartarus pro since support for it isn't ready yet, but the program doesnt seem to read any inputs. Dependencies seem fine(?), removing and reinstalling didnt show up any errors in compilation. Please check it out, thanks.

Version:
```
input-remapper 2.0.0 7a0ccac5d5e9609d2b0a1d60c61ec30edc539674 https://github.com/sezanzeb/input-remapper
python-evdev 1.3.0
```
[remapper-log.txt](https://github.com/sezanzeb/input-remapper/files/11570093/remapper-log.txt)

**Comment by sezanzeb** [comment]
Try python 3.10 https://github.com/sezanzeb/input-remapper/issues/676
