### ISSUE TITLE
input-remapper-control UnicodeDecodeError - no Logitech mouse available

### ISSUE THREAD

**Issue by mr2c12** [sezanzeb/input-remapper#718]
On Archlinux, I cannot anymore remap my logitech mouse buttons.

Used to work before (with the name "key-remapper").

Today I installed inpur-remapper via Yay (it install the package cloning the Git repo).

> % input-remapper-gtk 
> input-remapper-gtk 2.0.0 7a0ccac5d5e9609d2b0a1d60c61ec30edc539674 https://github.com/sezanzeb/input-remapper
> python-evdev 1.6.1
> Done
> Connected to the service
> Loaded config from "/home/mik/.config/input-remapper-2/config.json"
> WARNING: HandlerDisabled entry failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7f3ffafb0490>>"
> WARNING: HandlerDisabled exit failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7f3ffafb0490>>"
> ERROR: Failed to access path "/dev/input/event11": UnicodeDecodeError 'utf-8' codec can't decode byte 0xce in position 9: invalid continuation byte
> Found "Logitech USB Keyboard", "HP WMI hotkeys", "ETPS/2 Elantech Touchpad", "Video Bus", "ELAN0729:00 04F3:315D Mouse", "Wireless hotkeys", "AT Translated Set 2 keyboard"
> Loading group "HP WMI hotkeys"
> Loading preset "new preset"
> Loading preset from "/home/mik/.config/input-remapper-2/presets/HP WMI hotkeys/new preset.json"

The problem is with "/dev/input/event11" that corresponds to my mouse.

Anything I can try?

**Comment by bdelwood** [comment]
[This comment ](https://aur.archlinux.org/packages/input-remapper-git#comment-916136) on the AUR for `input-mapper-git` suggests it may be related to kernel 6.3.

Mostly for my own documentation when I have time to pick this back up, or for anyone that finds it useful:

This appears to be an error in evdev. Taking a closer look by running `input-remapper-gtk -d `

```
22:25:54.889160 112239 reader-service DEBUG reader_service.py:154: Discovering initial groups
22:25:54.889426 112239 reader-service DEBUG groups.py:354: Discovering device paths
...
22:25:54.889869 112239 reader-service ERROR groups.py:368: Failed to access path "/dev/input/event21": UnicodeDecodeError 'utf-8' codec can't decode byte 0xb4 in position 9: invalid start byte
```

Looking at [`reader-service` right after `Discovering device paths` is emitted](https://github.com/sezanzeb/input-remapper/blob/f23b0a0258a0c53af280cf082263db780e8cd985/inputremapper/gui/reader_service.py#L155), [it refreshes the group list](https://github.com/sezanzeb/input-remapper/blob/f23b0a0258a0c53af280cf082263db780e8cd985/inputremapper/groups.py#L473C2-L473C2), which makes a call to `evdev.input_devices`, which is used to [construct `evdev.InputDevice` objects](https://github.com/sezanzeb/input-remapper/blob/f23b0a0258a0c53af280cf082263db780e8cd985/inputremapper/groups.py#L354C5-L354C5), where the error occurs on `evdev` trying to open the device. 

Cracking open evdev:
```python
import evdev
device = evdev.InputDevice('/dev/input/event21')
```

gives 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/evdev/device.py", line 133, in __init__
    info_res = _input.ioctl_devinfo(self.fd)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 9: invalid start byte
```

**Comment by mr2c12** [comment]
After yesterday system update, I'm now running kernel:

> 6.4.12-arch1-1

And I am able to successfully use input-remapper.
