### ISSUE TITLE
ModuleNotFoundError: No module named 'inputremapper'; no devices detected

### ISSUE THREAD

**Issue by Shoxx98** [sezanzeb/input-remapper#723]
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 38, in <module>
    from inputremapper.gui.gettext import _, LOCALE_DIR
ModuleNotFoundError: No module named 'inputremapper'

**Comment by Txordi00** [comment]
Same problem here. I think it started to fail after the update to gnome 44.1 (I am on Manjaro GNOME).

**Comment by Shoxx98** [comment]
also noticed it after a big wave of updates.

**Comment by sezanzeb** [comment]
> but no device is recognized so my remaps aren't working.

Is `input-remapper-control --list-devices` finding any?

**Comment by sezanzeb** [comment]
> ModuleNotFoundError: No module named 'inputremapper'

Post the output of
- `find /usr/ -iname "*input*remapper*"`
- `python3 -c "import sys; print(sys.path)"`

**Comment by Shoxx98** [comment]
input-remapper-control --list-devices                            ✔ 
Traceback (most recent call last):
  File "/usr/bin/input-remapper-control", line 30, in <module>
    from inputremapper.logger import logger, update_verbosity, log_info
ModuleNotFoundError: No module named 'inputremapper'


find /usr/ -iname "*input*remapper*"                           1 ✘ 
/usr/share/metainfo/io.github.sezanzeb.input_remapper.metainfo.xml
/usr/share/input-remapper
/usr/share/input-remapper/input-remapper.policy
/usr/share/input-remapper/input-remapper.svg
/usr/share/input-remapper/input-remapper-autoload.desktop
/usr/share/input-remapper/input-remapper.service
/usr/share/input-remapper/lang/sk/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/it_IT/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/fr_FR/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/it/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/uk_UA/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/fr/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/ru/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/zh/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/sk_SK/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/ru_RU/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/uk/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/lang/zh_CN/LC_MESSAGES/input-remapper.mo
/usr/share/input-remapper/io.github.sezanzeb.input_remapper.metainfo.xml
/usr/share/input-remapper/input-remapper-gtk.desktop
/usr/share/input-remapper/input-remapper.glade
/usr/share/input-remapper/inputremapper.Control.conf
/usr/share/input-remapper/99-input-remapper.rules
/usr/share/input-remapper/input-remapper-large.png
/usr/share/applications/input-remapper-gtk.desktop
find: ‘/usr/share/polkit-1/rules.d’: Permission denied
/usr/share/polkit-1/actions/input-remapper.policy
find: ‘/usr/lib/firmware/b43legacy’: Permission denied
find: ‘/usr/lib/firmware/b43’: Permission denied
/usr/lib/systemd/system/input-remapper.service
/usr/lib/udev/rules.d/99-input-remapper.rules
/usr/lib/python3.10/site-packages/inputremapper
/usr/lib/python3.10/site-packages/input_remapper-2.0.0-py3.10.egg-info
/usr/bin/input-remapper-reader-service
/usr/bin/input-remapper-gtk
/usr/bin/input-remapper-control
/usr/bin/input-remapper-service


python3 -c "import sys; print(sys.path)"                     INT ✘ 
['', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']

**Comment by sezanzeb** [comment]
In the output above, it can be seen that the inputremapper python package is installed to `/usr/lib/python3.10/site-packages/inputremapper`

But `sys.path` looks for paths of 3.11

I'm assuming you upgraded from python 3.10 to 3.11 recently. Try reinstalling input-remapper, maybe this already helps

**Comment by sezanzeb** [comment]
> sudo input-remapper-gtk

https://wiki.archlinux.org/title/Running_GUI_applications_as_root

> [...] there are no *real*, substantiated, technological reasons why anybody should run a GUI application as root. By running GUI applications as an admin user you are literally running millions of lines of code that have not been audited properly to run under elevated privileges; you are also running code that will touch files inside your $HOME and may change their ownership on the file system; connect, via IPC, to even more running code, etc.
You are opening up a massive, gaping security hole [...].

input-remapper is designed to work around this issue using polkit. It uses pkexec to start a process without GUI logic that sends the devices back to the gui. The "ReaderService" as seen in this picture: https://github.com/sezanzeb/input-remapper/blob/main/readme/development.md#architecture

When I start input-remapper, this window appears:

![image](https://github.com/sezanzeb/input-remapper/assets/28510156/fe312850-65af-4e84-8efc-ee0fcaecaf9e)

Is this also the case for you?

**Comment by sezanzeb** [comment]
running `sudo input-remapper-control --list-devices` is fine, and might just be the correct way to do that.

Run `input-remapper-gtk -d`, and post the logs of the startup here

**Comment by Shoxx98** [comment]
I reinstalled and it fixed my issues. no data was lost.

**Comment by sezanzeb** [comment]
So the reader-service is somehow broken for you. Possibly because of `/usr/bin/input-remapper-reader-service:60: RuntimeWarning: coroutine 'ReaderService.run' was never awaited
  reader_service.run()`

This is how it looks for me:

```
sudo input-remapper-control --command start-reader-service -d
11:54:42.472611 10261 control DEBUG logger.py:297: Using rich.traceback
11:54:42.472764 10261 control DEBUG input-remapper-control:233: Call for "['/usr/bin/input-remapper-control', '--command', 'start-reader-service', '-d']"
11:54:42.476486 10261 control DEBUG input-remapper-control:215: System is booted
11:54:42.476540 10261 control DEBUG input-remapper-control:178: Running `input-remapper-reader-service -d &`
11:54:42.478297 10261 control INFO input-remapper-control:263: Done
➜  ~ 11:54:42.637407 10264 reader-service DEBUG logger.py:297: Using rich.traceback
11:54:42.671354 10264 reader-service DEBUG data.py:118: Found data at "/usr/share/input-remapper"
11:54:42.678065 10264 reader-service DEBUG pipe.py:87: Using existing pipe for "/tmp/input-remapper-mango/reader-results"
11:54:42.678256 10264 reader-service DEBUG pipe.py:87: Using existing pipe for "/tmp/input-remapper-mango/reader-commands"
11:54:42.678460 10264 reader-service DEBUG reader_service.py:154: Discovering initial groups
11:54:42.678667 10264 reader-service DEBUG groups.py:354: Discovering device paths
11:54:42.678953 10264 reader-service DEBUG groups.py:391: "PC Speaker" has no useful capabilities
11:54:42.753828 10264 reader-service DEBUG groups.py:402: Found unknown "Logitech USB Keyboard System Control" at "/dev/input/event5", hash "3ec135c52cf9bafbf93892fd9b833aad", key "3_1133_49960_usb-0000:28:00.3-2.3"
11:54:42.787067 10264 reader-service DEBUG groups.py:402: Found unknown "Logitech USB Keyboard Consumer Control" at "/dev/input/event4", hash "e205f561c4fa1ecab337969b46b51d72", key "3_1133_49960_usb-0000:28:00.3-2.3"
11:54:42.807214 10264 reader-service DEBUG groups.py:402: Found keyboard "Logitech USB Keyboard" at "/dev/input/event3", hash "cba0d7f555a960fabbad51fdb8f28b70", key "3_1133_49960_usb-0000:28:00.3-2.3"
11:54:42.844806 10264 reader-service DEBUG groups.py:402: Found mouse "USB Optical Mouse" at "/dev/input/event2", hash "14f36ff5018da900e3f14b07bb3c23ce", key "3_7119_5_usb-0000:28:00.3-2.1"
11:54:42.913766 10264 reader-service INFO groups.py:481: Found "Logitech USB Keyboard", "USB Optical Mouse"
11:54:42.913858 10264 reader-service DEBUG reader_service.py:161: Sending groups
11:54:42.913988 10264 reader-service DEBUG reader_service.py:193: Waiting for commands
```

**Comment by sezanzeb** [comment]
I just up upgraded to python 3.11, reinstalled input-remapper and am not having this issue

**Comment by sezanzeb** [comment]
Try replacing `/bin/input-remapper-reader-service` with https://gist.github.com/sezanzeb/8b5624134938236648d4f6ea213a0f30 and see if that improves anything
