### ISSUE TITLE
Doesn't work at all under my distro (Peppermint OS - debian 11 and ubuntu 18.04 based)

### ISSUE THREAD

**Issue by sabudum** [sezanzeb/input-remapper#733]
Tested all versions input-remapper and key-mapper, only key-mapper 1.0.0 and previous would work correctly, all newer versions launch, but the inputs are nor recognized or captured, can't record the input, and the joystick as mouse keeps the mouse cursor at the top left corner of the screen at all times.

How can I make the latest input-remapper compatible?

**Comment by jonasBoss** [comment]
Start with launching input-remapper in a console and see what the logs say. Also launch the service in a console.

But you probably want to switch to a newer distribution. Ubuntu 18.04 is 5 years old. We will not support such old distributions. But maybe I am wrong and Peppermint OS provides newer packages.

**Comment by sabudum** [comment]
> Start with launching input-remapper in a console and see what the logs say. Also launch the service in a console.
> 
> But you probably want to switch to a newer distribution. Ubuntu 18.04 is 5 years old. We will not support such old distributions. But maybe I am wrong and Peppermint OS provides newer packages.

It includes the base of Debian 11 for this purpose, so newer software is also supported

I'll post the console output here soon.

**Comment by sabudum** [comment]
So here's the output when I run the program from console:

`thales@thales-pc:~$ input-remapper-gtk
input-remapper-gtk 2.0.0 9e04df79ca4dca77516a9864d740b9b2d4aef788 https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Done
Connected to the service
Loaded config from "/home/thales/.config/input-remapper-2/config.json"

(input-remapper-gtk:6196): Gtk-WARNING **: 16:35:54.518: Theme parsing error: gtk.css:2198:24: 'nonne' is not a valid color name
WARNING: HandlerDisabled entry failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7f7320677e80>>"
WARNING: HandlerDisabled exit failed: "nothing connected to <bound method CodeEditor._on_gtk_changed of <inputremapper.gui.components.editor.CodeEditor object at 0x7f7320677e80>>"
Found "input-remapper AT Translated Set 2 keyboard forwarded", "input-remapper keyboard", "PixArt USB Optical Mouse", "AT Translated Set 2 keyboard"
Loading group "AT Translated Set 2 keyboard"
Loading preset "tomb"
Loading preset from "/home/thales/.config/input-remapper-2/presets/AT Translated Set 2 keyboard/tomb.json"
WARNING: No origin_hash set for {'type': 1, 'code': 75}
WARNING: No origin_hash set for {'type': 1, 'code': 77}
WARNING: No origin_hash set for {'type': 1, 'code': 76}
WARNING: No origin_hash set for {'type': 1, 'code': 36}
WARNING: No origin_hash set for {'type': 1, 'code': 72}
WARNING: No origin_hash set for {'type': 1, 'code': 37}
WARNING: No origin_hash set for {'type': 1, 'code': 72}
WARNING: No origin_hash set for {'type': 1, 'code': 38}
WARNING: No origin_hash set for {'type': 1, 'code': 72}
WARNING: No origin_hash set for {'type': 1, 'code': 72}
WARNING: No origin_hash set for {'type': 1, 'code': 75, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 77, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 76, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 36, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 37, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 38, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 76, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 75, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 77, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 76, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 36, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 37, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 38, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 76, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 75, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 77, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 76, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 36, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 37, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 38, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 72, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
WARNING: No origin_hash set for {'type': 1, 'code': 76, 'origin_hash': None, 'analog_threshold': None, 'message_type': <MessageType.selected_event: 'selected_event'>}
`

I guess we can safely ignore all the GTK related errors. There's no bug's with the UI

**Comment by jonasBoss** [comment]
> I'm using systemctl to stop and start the service

`systemctl` hides the output and logs it.

you can stop the service via `systemctl` and than start it directly to get the output: `$ sudo input-remapper-service -d` the `-d` flag to enable additional debug logs.

**Comment by sabudum** [comment]
thales@thales-pc:~$ systemctl stop input-remapper
thales@thales-pc:~$ sudo input-remapper-service -d
16:22:23.682054 8880 service DEBUG logger.py:296: Using rich.traceback
16:22:23.806012 8880 service DEBUG data.py:96: Found data at "/usr/share/input-remapper"
16:22:23.827192 8880 service INFO logger.py:264: input-remapper-service 2.0.0 9e04df79ca4dca77516a9864d740b9b2d4aef788 https://github.com/sezanzeb/input-remapper
16:22:23.827328 8880 service INFO logger.py:272: python-evdev 1.4.0
16:22:23.827412 8880 service WARNING logger.py:275: Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
16:22:23.827497 8880 service DEBUG daemon.py:196: Creating daemon
16:22:23.827694 8880 service ERROR daemon.py:339: "/home/thales/.config/input-remapper-2/config.json" does not exist
16:22:23.827790 8880 service DEBUG shared_dict.py:57: Starting SharedDict process
16:22:23.837039 8881 service DEBUG shared_dict.py:63: SharedDict process started
16:22:23.850998 8880 service DEBUG daemon.py:281: Running daemon



I'm having another problem now, re-installed key-mapper 1.0.0, because I needed to use it, and now neither input-remapper 2.0.0 or key-mapper 1.0.0 will launch, the service runs fine though.

This is the output for the input-remapper 2.0.0:
thales@thales-pc:~$ input-remapper-gtk

(input-remapper-gtk:8905): dbind-WARNING **: 16:23:48.075: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
input-remapper-gtk 2.0.0 9e04df79ca4dca77516a9864d740b9b2d4aef788 https://github.com/sezanzeb/input-remapper
python-evdev 1.4.0
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 88, in <module>
    reader_client = ReaderClient(message_broker, _Groups())
  File "/usr/lib/python3/dist-packages/inputremapper/gui/reader_client.py", line 82, in __init__
    self._results_pipe, self._commands_pipe = self.connect()
  File "/usr/lib/python3/dist-packages/inputremapper/gui/reader_client.py", line 125, in connect
    results_pipe = Pipe(get_pipe_paths()[0])
  File "/usr/lib/python3/dist-packages/inputremapper/ipc/pipe.py", line 80, in __init__
    chown(f"{fds_dir}{self._fds[0]}")
  File "/usr/lib/python3/dist-packages/inputremapper/configs/paths.py", line 40, in chown
    shutil.chown(path, user=USER, group=USER)
  File "/usr/lib/python3.9/shutil.py", line 1314, in chown
    os.chown(path, _user, _group)
PermissionError: [Errno 1] Operation not permitted: '/proc/8905/fd/10'
Exception ignored in: <function Pipe.__del__ at 0x7f6092139040>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/inputremapper/ipc/pipe.py", line 108, in __del__
    for file in self._handles:
AttributeError: 'Pipe' object has no attribute '_handles'

**Comment by jonasBoss** [comment]
Unfortunately I am not sure if can help you. There seems to be an PermissionError when Input-remapper is trying to change the owner of some file descriptors. But you said that this error did not appear before you switched back to version 1.0?

It seems like your daemon is running properly. Can you try and apply a preset with [`input-remapper-control`](https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#cli)?

**Comment by sabudum** [comment]
I can run the key-mapper-control and input-remapper-control fine loading and stopping the injection, and it works, with the exception of the already mentioned analog stick problem.

I believe the UI application doesn't run because I set my user as a sudoer and changed it's group to "sudo"
I did the same thing on another computer and key-mapper app also stopped working without modifying anything else.

**Comment by sabudum** [comment]
So, I managed to make the app run and load presets and everything, the only problem I'm having is that when I click "Record", to create a new mapping, it just doesn't work.
This is the output that prints in the console as soon as I click "Record":

`
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Event.wait() done, defined at /usr/lib/python3.9/asyncio/locks.py:213> exception=RuntimeError("Task <Task pending name='Task-8' coro=<Event.wait() running at /usr/lib/python3.9/asyncio/locks.py:226> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:513]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
RuntimeError: Task <Task pending name='Task-8' coro=<Event.wait() running at /usr/lib/python3.9/asyncio/locks.py:226> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:513]> got Future <Future pending> attached to a different loop
read loop for /dev/input/event0 stopped
`

**Comment by sabudum** [comment]
I noticed that asyncio was giving the error, so I tried updating python, since other similar issues suggested it might be it, after several failed attempts to update python, I just grabbed asyncio from python 3.10 and put it in the python 3.9 folder, so now input-remapper works as intended, so far...

The readme should state which python version is required for which application version though.
And provide instructions on how to update properly.
