### ISSUE TITLE
I don't understand the directions for Input Remapper

### ISSUE THREAD

**Issue by Lady-Fitzgerald** [sezanzeb/input-remapper#737]
The directions say to select the device (in my case, the keyboard), create a new preset (I got that far), then add a mapping. That's where I get stalled. What does that even mean? I have no idea what to do after that.

I have a Logitech G510s keyboard I'm using with a computer with Linux Mint 21.1 Cinnamon installed. I want to remap the G (macro) keys with non-standard characters, such as the ° symbol (CTRL + SHIFT+U00b0).  I some how got Input Remapper to recognize the G keys (G1 showed up as Macro 1) but I have no clue how to input the Unicode into Input Remapper and go from there.

I'm a septuagenarian with ADHD so I need to have simple step by step instructions to be able to do many things.

Thanks,

Jeannie

**Comment by jonasBoss** [comment]
Add A mapping:
![Screenshot_20230711_140928](https://github.com/sezanzeb/input-remapper/assets/31804124/f943464d-6746-40f1-a8d8-567b7459cee5)
Record the input by pressing the record button and then press on you keyboard whatever the input should be.
![Screenshot_20230711_141117](https://github.com/sezanzeb/input-remapper/assets/31804124/e55fe1ed-ef33-4049-9583-ece80c106488)
Write what the output should be. This can be a single letter, a combination like `a + b` or more advanced [macros](https://github.com/sezanzeb/input-remapper/blob/main/readme/macros.md).
![Screenshot_20230711_141339](https://github.com/sezanzeb/input-remapper/assets/31804124/a985e8af-2982-46a3-8ce7-bc0482e316c7)

**Comment by M8850** [comment]
just rememeber to click 'stop' first
