### ISSUE TITLE
How to "Apply" in the command line or using shortcut in the gtk GUI? (basically apply without mouse)

### ISSUE THREAD

**Issue by sgon00** [sezanzeb/input-remapper#742]
Hi, I don't have a mouse, that's the reason why I am using input-remapper to map special keyboard keys to mouse click.
It's working. But sometimes, the app stops injection automatically somehow. 
When the injection stopped, I have no mouse. I want to apply it again.
Now, it's tricky. I have no ideas how to click the Apply button.
I saw Ctrl+Del is for stop injection, but there is no shortcut/key binding for Apply button.
I tried to sudo systemctl restart input-remapper, but it doesn't apply.
So my question is how to apply when there is no mouse.
Btw, I know reboot will work because Autoload is ON, but I don't want to reboot to apply.
Thanks a lot.

**Comment by jonasBoss** [comment]
Use the command line: https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#cli
