### ISSUE TITLE
Help with a macro

### ISSUE THREAD

**Issue by altoryus** [sezanzeb/input-remapper#752]
Not sure if this is the right place to post this, if so, I apologize.

So, I'm having trouble to figure out how to make the input remapper do the following: While Button EXTRA is clicked, then repeat very quickly BTN_LEFT. When Button EXTRA is clicked again, then stop the macro. If this is not possible, variations are still welcome like when held, repeat quickly and when released, stopping it, etc.

**Comment by sezanzeb** [comment]
map EXTRA to `hold(key(BTN_LEFT))`, which repeats BTN_LEFT as long as the key is held down.

Starting it with one button-press, and stopping it with a second one is currently not possible. See https://github.com/sezanzeb/input-remapper/issues/547

**Comment by altoryus** [comment]
Hey, thanks for the reply.

The macro did not work, it instead just holds the BTN_LEFT instead of repeating.

**Comment by sezanzeb** [comment]
ok, weird, which version of input-remapper are you on? `input-remapper-control --version`

**Comment by sezanzeb** [comment]
And you are sure you didn't forget to write the `key` function inside `hold`?

**Comment by sezanzeb** [comment]
Try to slow it down by adding .wait: `hold(key(BTN_LEFT).wait(100))`

**Comment by altoryus** [comment]
Hey there, thanks again for your reply. The last macro worked for me, really appreciated!
