### ISSUE TITLE
install didnt work

### ISSUE THREAD

**Issue by vuaieo** [sezanzeb/input-remapper#755]
hi just wanetd share my experience with this, i installed inputmapper version 1.5 on kubuntu 23.04 and plasma DE from discover app first. then deleted 1. 5 and tryed install 2.0 but the error came that it cant overwrite input mapper 1.5 file. so deletd the files manually but the error still came. then then after 5 hours searching and getting help from some pro linux users finaly found command : sudo apt remove --autoremove input-remapper . only with this command i was able to install 2.0. 
so the problem is that if installing first 1.5 and then 2.0 , you cant...

**Comment by sezanzeb** [comment]
Luckily input-remapper 2.0.1 is available in ubuntu 23.10 via the official repo now.
