### ISSUE TITLE
Mouse-button gets stuck, can't stop injection

### ISSUE THREAD

**Issue by vuaieo** [sezanzeb/input-remapper#756]
i cant get it to work that when holding left mouse button then it auto presses it forever untill release. i get mouse stuck and need logout of pc and relogin or even restart whoe pc...
it would be very nice if there would be universal key combos to reset all input before start so it wouldnt get stuck because the stop dont do it...
can someone send that macro?
i using inputmapper 2.0.0

**Comment by TherinS** [comment]
Perhaps the readme file at "input-remapper/readme/usage.md" will help, under the section near the top called "UI Shortcuts".

**Comment by sezanzeb** [comment]
disconnect your mouse and reconnect it, it will stop the injection.

**Comment by sezanzeb** [comment]
Alternatively, see https://github.com/sezanzeb/input-remapper/issues/764#issuecomment-1757873937
