### ISSUE TITLE
Mapping to Unicode Character

### ISSUE THREAD

**Issue by montanajava** [sezanzeb/input-remapper#758]
**Mapping from an Input to a Unicode Character**

The discussion in the referenced issue 735 indicates that mapping to a Unicode character can be done in accordance with the inverse of the  principle _If your fingers can't type it on your keyboard, input-remapper can't inject it_.  It just didn't work for me, and so here is a request for review from more knowledgeable experts to see if we can formalise a solution that would be useful for a broader audience. 

To try to reproduce the problem and solution I used F13 as an input. Then as output, I entered:

modify(Control_L, modify(Shift_L, key(u).key(0).key(0).key(b).key(0)))

Current Situation: I get a `u` prompt.  Then I have to enter the Unicode code and press enter. In other words, it didn't work.

Desired Situation: ° should be entered at the cursor, without having to type anything further.

I think I am close and would appreciate any input, pun intended.

### Discussed in https://github.com/sezanzeb/input-remapper/discussions/735

<div type='discussions-op-text'>

<sup>Originally posted by **Lady-Fitzgerald** July 10, 2023</sup>
I have an old Logitech keyboard I want to use with my Linux Mint 21.1 Cinnamon install so I can take advantage of the 18 G Keys (separate macro keys) to quickly type non-keyboard characters, such as à, and symbols, such as °.

I've tried using Input Remapper (https://github.com/sezanzeb/input-remapper) 1.4.0 (the version in the repository) but haven't any luck so far.

I can get keyboard characters to work with a G key but there's no point in that. However, I have not been able to get other characters and symbols, such as the ones I mentioned, to work with a G key using their Unicodes, such as CTRL+Shift+u+00b0 for °. I've tried to follow the directions on the programs GitHub page but I can't make any sense of them (it doesn't help that I'm a septuagenarian with ADHD).

Can someone help me with this. If I can get the correct syntax for entering one character or symbol, such as the ° symbol, using its Unicode. Because of my ADHD, I need simple, step by step directions.

Thanks!
</div>

**Comment by WitteShadovv** [comment]
I know this is not the prettiest solution but it worked quite well when I tested it a few weeks ago. Before that I also used something that created characters with unicodes but that didn't work in a few programs.

I used the compose key which most OS/WM support to write special character such as "ö" or "©" and mapped the characters needed to create the special char to the output. 

In the example below, which creates an ö, the compose key is set to "Right Alt".

KEY_RIGHTALT + o +  Shift_L + KEY_APOSTROPHE

I hope this helps!

**Comment by montanajava** [comment]
@@WitteShadovv:  I tried your suggestion and it works. With what you suggest, there would be no Unicode character that could not be mapped. 

The downside is that it is not keyboard-layout independent, but having it work in _any_ program outweighs that desire.

Thanks for the tip. With that, I will close the issue.
