### ISSUE TITLE
Feature request: add option to execute macro on key release.

### ISSUE THREAD

**Issue by sabudum** [sezanzeb/input-remapper#771]
I love the macro system, but it would incredibly amazing to be able to execute macros on key release as well.
This could be done by adding a macro function called on_release( macro ) or similar, when the combo or key is released, then execute the macro, this function could be chained with other existing functions.

**Comment by sezanzeb** [comment]
if you map `a` to this macro `hold(KEY_A).key(KEY_B)`, the key will continue to work as if nothing was mapped, and once you release it "b" will be written

**Comment by sabudum** [comment]
That does not do what I just described.
I need to execute a specific macro on key_press
and another completely different macro on key release.
I do not want to hold a key while I'm pressing it.

For instance, when I press Shift, I want to execute only once: Ctrl + Alt + A
When I release Shift, I want to execute only once: Ctrl + F12

Or in more complex scenarios:
When I press Shift I want to execute only once: key_up( KEY_F10 )
When I release Shift I wan to execute only once: key_down( KEY_F10 )
Effectively reversing the functionality of F10

**Comment by sezanzeb** [comment]
`key_up(KEY_F10).hold().key_down(KEY_F10)`

**Comment by sabudum** [comment]
Yeah, that works, I'm typing this right now with reversed functionality of Shift, it's harder than you might think.
Thanks a lot though!
