### ISSUE TITLE
Fresh install, unable to start input-remapper.service

### ISSUE THREAD

**Issue by r04dw4rri0r** [sezanzeb/input-remapper#774]
Removed all previous versions of input-remapper and did a new install using yay. Arch linux running Plasma. Honestly pretty new to arch, havent used linux in years and decided to spice things up.

To help people understand your problems, run `sudo pkill -f input-remapper && input-remapper-gtk -d`, reproduce the problem and then share the output here.

```
sudo pkill -f input-remapper && input-remapper-gtk -d
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 38, in <module>
    from inputremapper.gui.gettext import _, LOCALE_DIR
ModuleNotFoundError: No module named 'inputremapper
```

```
systemctl status input-remapper.service
× input-remapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/input-remapper.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2023-09-19 16:40:25 CDT; 10s ago
    Process: 51414 ExecStart=/usr/bin/input-remapper-service (code=exited, status=1/FAILURE)
   Main PID: 51414 (code=exited, status=1/FAILURE)
        CPU: 19ms

systemd[1]: Starting Service to inject keycodes without the GUI application...
input-remapper-service[51414]: Traceback (most recent call last):
input-remapper-service[51414]:   File "/usr/bin/input-remapper-service", line 28, in <module>
input-remapper-service[51414]:     from inputremapper.logger import update_verbosity, log_info
input-remapper-service[51414]: ModuleNotFoundError: No module named 'inputremapper'
systemd[1]: input-remapper.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: input-remapper.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Service to inject keycodes without the GUI application.
```

```
journalctl -xeu input-remapper.service
░░ 
░░ An ExecStart= process belonging to unit input-remapper.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 19 16:40:59 mordor systemd[1]: input-remapper.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit input-remapper.service has entered the 'failed' state with result 'exit-code'.
Sep 19 16:40:59 mordor systemd[1]: Failed to start Service to inject keycodes without the GUI application.
░░ Subject: A start job for unit input-remapper.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit input-remapper.service has finished with a failure.
░░ 
░░ The job identifier is 7649 and the job result is failed.
```

**Comment by Felixoid** [comment]
It looks like you have it reinstalled without rebuilding, and your python is updated.

Use the following steps to fix it:

```
ay -S input-remapper-git
AUR Explicit (1): input-remapper-git-2.0.1.r0.ga012746a-1
:: PKGBUILD up to date, skipping download: input-remapper-git
  1 input-remapper-git               (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/felixoid/.cache/yay/input-remapper-git
```

**Comment by Yejashi** [comment]
I have this issue as well, rebuilding it does not solve it.

**Comment by r04dw4rri0r** [comment]
> It looks like you have it reinstalled without rebuilding, and your python is updated.
> 
> Use the following steps to fix it:
> 
> ```
> yay -S input-remapper-git
> AUR Explicit (1): input-remapper-git-2.0.1.r0.ga012746a-1
> :: PKGBUILD up to date, skipping download: input-remapper-git
>   1 input-remapper-git               (Installed) (Build Files Exist)
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> a
> :: Deleting (1/1): /home/felixoid/.cache/yay/input-remapper-git
> ```

I did do a clean build, still having the above-mentioned issues.

yay -S input-remapper-git
AUR Explicit (1): input-remapper-git-2.0.1.r0.ga012746a-1
:: PKGBUILD up to date, skipping download: input-remapper-git
  1 input-remapper-git                       (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/roadwarrior/.cache/yay/input-remapper-git
HEAD is now at 2e09906 update pkgver
Removing input-remapper-git-2.0.1.r0.ga012746a-1-any.pkg.tar.zst
Removing input-remapper/
  1 input-remapper-git                       (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
 -> input-remapper-git: No changes -- skipping

**Comment by Dmonus** [comment]
I'm new to themes, don't kick. And what if we make a service for systems based on runit, dinit, etc.? It's very tedious to edit it yourself!

**Comment by r04dw4rri0r** [comment]
After reinstalling Arch this is no longer an issue.

**Comment by Yejashi** [comment]
To any others that are running into this issue, this is how i fixed it:

1. You need to pip  install input-remapper system wide
   a.  sudo /usr/bin/pip install input-remapper --break-system-packages
   
Reason:
1. As far as my peanut break is aware, the reason this is happening is because it is installing the pip packages in the wrong environment.
