### ISSUE TITLE
I cannot set [ and ]?

### ISSUE THREAD

**Issue by TravelTrader** [sezanzeb/input-remapper#777]
I have the newest version but the square brackets are not possible to assign.

What’s the trick to do it?

I really like your tool. Used orders before but especially the presets are great.

**Comment by sezanzeb** [comment]
On my german keyboard, you'd have to inject `hold_keys(ISO_Level3_Shift, 8)` for `[`.

You have to inject the kombination that would write your special character. More information is here: https://github.com/sezanzeb/input-remapper/blob/main/readme/usage.md#limitations
