### ISSUE TITLE
Prevent gamepad creation

### ISSUE THREAD

**Issue by F2FG** [sezanzeb/input-remapper#780]
I use this software to remap a few keys on a keyboard, but input-remapper automatically creates a gamepad on my system even if I don't use the gamepad features.

The problem is that when I connect my real gamepad it takes slot 2, because the first slot is already occupied by the input-remapper virtual gamepad, and many games won't detect my real gamepad.

Is there any way or workaround to prevent the creation of the virtual input-remapper gamepad?

**Comment by sezanzeb** [comment]
Which version?

I just tried it, the device called "input-remapper gamepad" is only created if one of your mappings is using the "Gamepad" target

**Comment by sezanzeb** [comment]
> Thank you for pointing me in the right direction, and most of all thank you for this amazing piece of software.

You are welcome :)

**Comment by sezanzeb** [comment]
From 23.10 on, input-remapper 2.0.1 is installable via ubuntus repo

**Comment by F2FG** [comment]
Hi sezanzeb, just a quick update: I installed input-remapper on Ubuntu 23.10 and I got version 1.5, not the latest 2.0.1

**Comment by sezanzeb** [comment]
Something must be wrong on your end: https://packages.ubuntu.com/search?keywords=input-remapper&searchon=names&suite=mantic&section=all

**Comment by F2FG** [comment]
You are perfectly right, I installed 23.04 instead of 23.10 :(
