### ISSUE TITLE
Mapping mouse movements

### ISSUE THREAD

**Issue by aonphleacs** [sezanzeb/input-remapper#79]
I am not seeing this in the mapping list so please let me know if I'm missing something but it would be very nice to be able to map the "scroll method" and "scrolling button" that libinput uses to a mouse button so that the mouse movement can be used for vertical and horizontal scroll such that could be done with `xinput set-prop <devID> "libinput Scroll Method Enabled" 0, 0, 1 && xinput set-prop <devID> "libinput Button Scrolling Button" <button>`

**Comment by sezanzeb** [comment]
I think I could add a feature similar to mapping joysticks. To have a dropdown to set it either as "Mouse", "Joystick", "Wheel" or "Buttons"

The easiest one to implement would be a "Buttons" mode, which could then be mapped to e.g. `wheel(down, 1)`

**Comment by aonphleacs** [comment]
Thanks for looking into it!
I think the "Buttons mode" idea is exactly what I would use it for. I have a ball mouse that just begs to have the ball actionable as a scroll wheel.

**Comment by sezanzeb** [comment]
Tried it out a bit today. At first it worked surprisingly well already, but it ends up feeling quite odd.

https://github.com/sezanzeb/key-mapper/tree/map-mouse-movement

**Comment by aonphleacs** [comment]
Interesting findings. I think that at least for scrolling, the only use is the first one where the button is depressed prior to mouse movement but I can see how that might feel awkward if you're already starting to move the mouse as you depress the button.
Are you using a ball mouse or a regular one? I think that it will feel particularly strange with a regular mouse.
But, hey, plugins are also a great way to go about this and I'm all about extensibility.

**Comment by sezanzeb** [comment]
regular one.

plugins would be great. lets see how that will continue. 1.0.0 which is apparently going to land into the debian repos won't get plugin support, that's for sure.

**Comment by aonphleacs** [comment]
Congrats on the repo addition!
Well, thank you for providing that branch nonetheless. I'm not very git savvy yet but I may crack my fingers and see if I can get it running locally so I can play with it.

**Comment by jonasBoss** [comment]
This should be possible on the beta branch. Just need to add a `RelToRelHandler` and a `RelToAbsHander` which I pan to do anyway.

@sezanzeb you might want to add this to the [beta](https://github.com/sezanzeb/input-remapper/projects/3) project

**Comment by sezanzeb** [comment]
Closing because this can be done in beta. It will arrive on main probably in February
