### ISSUE TITLE
output not working in wine/wow

### ISSUE THREAD

**Issue by lordkitsuna** [sezanzeb/input-remapper#790]
2. arch Linux 
3. wayland session
4. plasma
5. lrwxrwxrwx 1 root root 0 Oct 18 18:57 /proc/1/exe -> /usr/lib/systemd/systemd 

I'm not sure if this is explicitly a libremapper issue or not. I'm attempting to get this working on world of Warcraft through wine with Lutris to repeat keys when held down it works in the games chat (can spam a letter in chat when held down) but not for the actual in game spell casting and i can't seem to figure out why. I'm wondering if that's just something games do by stealing input or something and I'm doomed or there is some kind of work around.

i would assume it should be possible since windows tools like razer synapse can do it. what would be helpful information to diagnose this.

**Comment by daveschz** [comment]
Any chance you're using an Action Bar Addon like Bartender or Dominos? Only the stock action bar allows for spam-casting, iirc.

**Comment by sezanzeb** [comment]
Try to add some delay into your macro. Something like `hold(key(KEY_1).wait(200))`

**Comment by lordkitsuna** [comment]
> Try to add some delay into your macro. Something like `hold(key(KEY_1).wait(200))`

I forgot to get back to this. I was eventually able to get this working, both using the format from your example _and_ setting up the game to use gamescope. For whatever reason it still doesn't behave properly for me outside of gamescope however with it your example behaves as expected and does the proper timing on repeating keys. Thank you!
