### ISSUE TITLE
Desktop Only remapping

### ISSUE THREAD

**Issue by StarPlayrX** [sezanzeb/input-remapper#792]
All my video games Remap fine. 

I would like to only use this at the Desktop Workspace 0 or 1. Which it does work there. I don't need it to work else where. Anywhere to apply it in this scenario and not globally?

**Comment by sezanzeb** [comment]
input-remapper can't be made to distinguish between applications or desktop workspaces. See https://github.com/sezanzeb/input-remapper/discussions/20
