### ISSUE TITLE
Switch Win to Fn and Fn to Win

### ISSUE THREAD

**Issue by hollisticated-horse** [sezanzeb/input-remapper#795]
This is not a bug. I don't know where else to ask this question. 

How does one create a Preset to switch the Win/Super key to Fn and the Fn Key to Win/Super key ? 

When using `input-remapper-control --symbol-names | grep FN`, I have this output: 
```
KEY_FN
KEY_FN_1
KEY_FN_2
KEY_FN_B
KEY_FN_D
KEY_FN_E
KEY_FN_ESC
KEY_FN_F
KEY_FN_F1
KEY_FN_F10
KEY_FN_F11
KEY_FN_F12
KEY_FN_F2
KEY_FN_F3
KEY_FN_F4
KEY_FN_F5
KEY_FN_F6
KEY_FN_F7
KEY_FN_F8
KEY_FN_F9
KEY_FN_RIGHT_SHIFT
KEY_FN_S
```

and for `input-remapper-control --symbol-names | grep META`

```
KEY_LEFTMETA
KEY_RIGHTMETA
```

Which ones to I use ? And how do I use the GUI to set those up ?

**Comment by sezanzeb** [comment]
FN, at least on my keyboard, does not actually report an event to the computer. So it can't be mapped.

In case you are trying to switch FN and Win on a thinkpad: you can do that in the bios.

**Comment by hollisticated-horse** [comment]
Ah okay, thank you for confirming this is normal behavior from the Fn key. Had me wondering. 

It's for a msi laptop that randomly switches back to inverting Fn with Win keys, disregarding the bios setting. Even after an bios update it continued to do so. 

Anyhow, am using Left-Alt as super, seems to have fixed my problem on i3wm.
