### ISSUE TITLE
1+1+2+3+4+1 outputs 4321

### ISSUE THREAD

**Issue by RickAndTired** [sezanzeb/input-remapper#798]
To help people understand your problems, run `sudo pkill -f input-remapper && input-remapper-gtk -d`, reproduce the problem and then share the output here.
[input-remapper-debug1.txt](https://github.com/sezanzeb/input-remapper/files/13199377/input-remapper-debug1.txt)

In Gnome-text-editor
1+1+2+3+4+1 outputs 4321

In most other programs
1+1+2+3+4+1 outputs 1234

How can I have Input-Remapper output  `112341`?

Side question:
How can I press multiple keys within a macro?
Alt+down wait Alt+Shift+Ctrl+4
I tried this, but it won't let me mix macros and `+`
modify(Alt_L, key(down)).wait(500)
Alt_L+Shift_L+Control_L+4

**Comment by jonasBoss** [comment]
the `+` is meant for key combinations. so your macro presses all the keys at the same time. But you want them to be pressed all separately after each other.

You need to chain the [key macro](https://github.com/jonasBoss/key-mapper/blob/main/readme/macros.md#key): `key(1).key(1).key(2).key(3)`

**Comment by RickAndTired** [comment]
> the `+` is meant for key combinations. so your macro presses all the keys at the same time. But you want them to be pressed all separately after each other.
> 
> You need to chain the [key macro](https://github.com/jonasBoss/key-mapper/blob/main/readme/macros.md#key): `key(1).key(1).key(2).key(3)`

Thank you, I'll close this issue, but if you have an answer to this I'd greatly appreciate it
How could I do a four button combo within a macro?
 Alt_L+Shift_L+Control_L+4

**Comment by jonasBoss** [comment]
exactly like you suggested:
Alt_L+Shift_L+Control_L+4

If that does not work open a new issue
