### ISSUE TITLE
Toggle Aim

### ISSUE THREAD

**Issue by RickAndTired** [sezanzeb/input-remapper#831]
I'm trying to set up `Toggle Aim` in an FPS game that does not have that option

Some FPS games require you to hold down the `right mouse button` to aim

I'd like to use `input-remapper` so when I press `right mouse button` it will toggle it into a hold `right mouse button`
And when I press `right mouse button` again it will release the hold `right mouse button`

Is there anyway to do this?

It doesn't work exactly how I want, but I was able to get a somewhat toggle by using this code, however it only works if I'm using a keyboard input. It won't work when I use mouse input.
`if_tap(key_down(BTN_RIGHT), key_up(BTN_RIGHT))`

**Comment by jonasBoss** [comment]
I think you can use a variable for this. See [`set()`](https://github.com/sezanzeb/input-remapper/blob/main/readme/macros.md#set) and `if_eq()` macros.

try this:
```
if_eq($toggle, 0, key_down(BTN_RIGHT).set($toggle, 1), key_up(BTN_RIGHT).set($toggle, 0))
```

**Comment by RickAndTired** [comment]
> if_eq($toggle, 0, key_down(BTN_RIGHT).set($toggle, 1), key_up(BTN_RIGHT).set($toggle, 0))

I get this error with that code
>"Button RIGHT": "<Variable "toggle" at 0x7fa2af112590>" is not a legit variable name

**Comment by jonasBoss** [comment]
well, I guess i didn't read the documentation carefully (but neither did you).
You need to remove the dollar sign when setting variables.

**Comment by RickAndTired** [comment]
I removed the dollar signs which fixed the error, but the remap doesn't seem to do anything as far as I can tell

**Comment by ddziech** [comment]
it works for me `if_eq($toggle, 0, key_down(BTN_RIGHT).set(toggle, 1), key_up(BTN_RIGHT).set(toggle, 0))`

**Comment by RickAndTired** [comment]
> it works for me `if_eq($toggle, 0, key_down(BTN_RIGHT).set(toggle, 1), key_up(BTN_RIGHT).set(toggle, 0))`

This one worked, I didn't understand to keep the first $, I removed them all
Thank you both!
