### ISSUE TITLE
Is it possibile to use hold function with two keys or not??

### ISSUE THREAD

**Issue by ironhak** [sezanzeb/input-remapper#913]
From documentation:

> `hold_keys(a)` holds down "a" as long as the key is pressed, just like a regular non-macro mapping.

Say that I want Super_L+Left to behave like Control_L+Left, but Super_L alone to be just Super_L, how can I do that if I keep pressed Super_L+Left it acts like I'm keeping pressed Control_L+Left? Currently I'm using Super_L+Left = `modify(Control_L,Left)` and it works but not if I keep Super_L and Left pressed. I tried to `hold_keys(modify(Control_L,Left))` but it does not work. Ideas?

Thank's.

**Comment by ironhak** [comment]
Anyone can help?

**Comment by negora** [comment]
If I'm not mistaken, `hold_keys ()` expects a variable number of symbols as strings, not a single macro. So you should use `hold_keys (Control_L, Left)` instead.

On the other hand, the function `hold()` is the one that expects a single macro. But I've tested the following macro and it's SO MUCH sensitive that becomes useless: `hold (modify (Control_L, key (Left)))`. I don't know if I'm doing something wrong...

**Comment by ironhak** [comment]
Solved with this:
```
Alt_L = Super_L
Alt_L + Left = key_up(Super_L).hold_keys(Control_L,Left)
```

This way I get a behaviour like on mac.

**Comment by ironhak** [comment]
Solved with this:
```
Alt_L = Super_L
Alt_L + Left = key_up(Super_L).hold_keys(Control_L,Left)
```

This way I get a behaviour like on mac.
