### ISSUE TITLE
How do I remap a button to spam left click for as long as I am holding it?

### ISSUE THREAD

**Issue by NGSpace** [sezanzeb/input-remapper#917]
I'm sorry if it's not a "real" issue but I spent so long trying to understand whether it is possible or not to do it using this program.

**Comment by jonasBoss** [comment]
maybe a bit unintuitive, but you can use the [hold](https://github.com/sezanzeb/input-remapper/blob/main/readme/macros.md#hold) macro: `hold(key(a))` or `hold(key(a).wait(50))`

**Comment by TherinS** [comment]
NGSpace, please mark this as SOLVED if the suggestion worked for  you.

**Comment by NGSpace** [comment]
yes
