### ISSUE TITLE
"device name" has no useful capabilities prevents axis-only devices from being remapped

### ISSUE THREAD

**Issue by StelardActek** [sezanzeb/input-remapper#955]
I want to use Input-Mapper with my Fanatec CSL racing pedals, for two reasons. Firstly, most versions of wine/proton cannot see them, seemingly because they have no buttons, only axes. Secondly, it is useful in some games to have a button fire off when pressing the pedals a certain amount (namely, Star Citizen does not have an axis input for brake with ground vehicles at time of writing, so being able to map pressing on the brake to a button press is useful).

However, the code segment below (groups.py) prevents the UI program from seeing my racing pedals either. I've been able to work around it, but it would be nice if this could be changed so anyone else in my situation doesn't have to go editing code.

I'd make a pull request but I have to assume this was put here for a reason, so it seems a bit rude to just suggest you remove it.

```python
            if key_capa is None and device_type != DeviceType.GAMEPAD:
                # skip devices that don't provide buttons that can be mapped
                logger.debug('"%s" has no useful capabilities', device.name)
                continue
```

**Comment by jonasBoss** [comment]
Go ahead and make a PR! I think this is a leftover from the 1.x version where Inputremapper did not have all the features around analog axis. I think as long as a device has either a button or any axis, it should show up in the GUI. We probably just overlooked it when working on 2.0

**Comment by StelardActek** [comment]
Created pull request #956
