### ISSUE TITLE
How do I associate a scroll wheel event to Control_L + scroll up or down ?

### ISSUE THREAD

**Issue by nelson777** [sezanzeb/input-remapper#970]
I guess [issue #969](https://github.com/sezanzeb/input-remapper/issues/969) is not over just yet :D

As I started to use issue's #969 configuration (Control_L + KEY_KPPLUS/KEY_KPMINUS) I noticed that it zoomed browsers only. This is not exactly what I wanted. I wanted it to work in Terminator for example.

So what I really want is just to _add_ the the pressing of Control_L when I scroll up or down with the wheel.

So I tried `Control_L + wheel(up, 10)`,  `hold_keys(Control_L).wheel(up, 10)` and `hold_keys(Control_L, wheel(up, 10))` none of them worked. I tried with and without `Wheel -> disabled`. 

How can I configure it this time ?

**Comment by jonasBoss** [comment]
I think this is not really possible at the moment. See #310

**Comment by jonasBoss** [comment]
You just need to set the `keyboard + mouse` target and use the `modify(Control_L, wheel(up, 120))` macro. 
Maybe set a lower speed if it zooms to much but stick to numbers that divide 120 because the ratio of `WHEEL`/`WHEEL_HI_RES` is always 1/120.

**Comment by nelson777** [comment]
It did work to enable zoom, but then the zoom using scrollbutton is overriden. Let me explain better:

First, the device I'm trying to configure is a ProtoArc Em03 trackball. I don't need scroll whell for scrolling because I already have scrolling directly on the ball by holding right mouse button, which is much more convenient because it is much smoother and I still get X and Y scroll. This is the scroll I normally use and I really don't use scroll wheel.

I configure this by using libinput this way:

```
Section "InputClass"
        Identifier "Nordic 2.4G Wireless Receiver Mouse"
        MatchProduct "Nordic 2.4G Wireless Receiver Mouse"
        MatchIsPointer "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "ButtonMapping" "1 2 3 4 5 6 7 8 9"
        Option "ScrollButton" "3"
        Option "ScrollMethod" "button"
        Option "MiddleEmulation" "on"
EndSection

```

So I thought in using scrollwheel for something useful like zooming. But I obviously still need that button/ball scroll working.

Is there a way to enable zoom only for the scroll wheel and not affect the button/ball scroll ? 

I'm not particularly attached to libinput. If there's a way to do both functions on input-remapper I can disable libinput configuration. No problem.

**Comment by jonasBoss** [comment]
Maybe this is still possible. I am not super familiar how libinput works, but as far as I know it is part of X-Org or Wayland.
That means InputRemapper sits in between your physical device and libinput. You probably only need to change the Identifier and or MatchProduct in your "InputClass" section.

When there is a preset running for a device, InputRemapper will clone the device and send all events to the clone while making sure no one can read on the original device. 
Let's say you have a mouse called "Mouse" the mouse will show up at `/dev/input/event1`.
If you now have a mapping for this mouse InputRemapper will make sure no one can read from `/dev/input/event1` and it will create a clone called "input-remapper Mouse forwarded" this might show up as `/dev/input/event3`. All events that are not affected by any mapping will be sent to this clone. All events that are created by a mapping will be sent to one of the four predefined "input-remapper ..." devices.

So I guess you need to change MatchProduct and or Identifier to "input-remapper Nordic 2.4G Wireless Receiver Mouse forward"

**Comment by nelson777** [comment]
You know what ? it worked! Man you rock! Thanks.
