### ISSUE TITLE
How to write Macro in input

### ISSUE THREAD

**Issue by KAGEYAM4** [sezanzeb/input-remapper#972]
```
input-remapper 2.0.1 cf01699c5fba4d24bb81cce5c2f8bf024ffee265 https://github.com/sezanzeb/input-remapper
python-evdev 1.7.1
```

https://github.com/sezanzeb/input-remapper/blob/cf01699c5fba4d24bb81cce5c2f8bf024ffee265/readme/usage.md?plain=1#L18-L19
It states that we can use macro in input field. But it is not working. I am only able to use record button to fill the input field and then optionally rename the title of the input.

Also Macro in input, what would its behaviour would be like, do we macros exclusively for input ?

**Comment by jonasBoss** [comment]
I guess the documentation is confusing. No there is no such thing as a macro as input. You can write macros into the **text-input-field** on the Output side.

**Comment by KAGEYAM4** [comment]
okay. i will create a pr to fix this. Thanks
