### ISSUE TITLE
Alt+Tab macro not working after update

### ISSUE THREAD

**Issue by celeborne** [sezanzeb/input-remapper#984]
Hi there, I've been using the following ALT+TAB macro to switch between applications on my GNOME-based linux distro:

`modfy(alt_l, hold(key(key_tab).wait(500)))`

This resulted in really nice functionality where the ALT-TAB carousel would populate and stay open for the 500ms delay, and switch the focused app in the carousel with repeated presses of the macro'd button, only switching to the selected app after the 500ms delay had lapsed. However, the closest implementation I've been able to get working since updating the application is derived from the examples.md page, as such: 

`modify(KEY_LEFTALT, key(KEY_TAB).wait(1000))`

This will populate the ALT+TAB carousel and switch the focused application to the next in line, but will not respond to repeated presses to continue tabbing through the carousel (as the previous macro did to continue switching until the desired application is selected.)

Does anyone have a macro that replicates the aforementioned functionality described?

**Comment by sezanzeb** [comment]
typo in `modfy`, should be `modify`, with that it works for me in KDE

**Comment by celeborne** [comment]
Thank you, @sezanzeb!
