### ISSUE TITLE
Interact with Numlock?

### ISSUE THREAD

**Issue by mprytoluk** [sezanzeb/input-remapper#988]
I'm trying to map the "period" on the "numpad" to an actual period, as it outputs a comma in pt-br layout.

Mapping "KP delete" to "period" works, but it unaware of the Numlock state, so it always output a period, regardless of the Numlock state.

Is there a way, using macros or otherwise, to map a keypress only if Numlock is active?

**Comment by sezanzeb** [comment]
Try the `if_leds` branch.

Set the macro to `if_numlock(key(period), key(comma))`

**Comment by sezanzeb** [comment]
And let me know if that works, or if you need help installing from a branch

**Comment by mprytoluk** [comment]
Thanks a lot @sezanzeb , it worked!
I'll share my steps in ubuntu 24.04:

`
git clone -b if_leds https://github.com/sezanzeb/input-remapper.git
cd input-remapper && ./scripts/build.sh
** install some missing libs **
sudo apt install -f ./dist/input-remapper-2.0.1.deb
`

It was kinda tricky because of dependencies, but it ended up working.

Fyi, the final script was:
`if_numlock(hold(period), hold(KP_Delete))`
This was exactly the behavior I wanted.

**Comment by sezanzeb** [comment]
awesome!

I wonder if `hold(period)` is actually deprecated, because I added `hold_keys(period)` later and the docs don't mention it. But anyway, it probably doesn't matter.

**Comment by sezanzeb** [comment]
Maybe `hold(period)` is perfectly fine and should be kept forever, because it is very readable.
