### ISSUE TITLE
Feature Request: mouse speed adjustment

### ISSUE THREAD

**Issue by danrobi11** [sezanzeb/input-remapper#99]
Would be nice to have mouse speed adjustment. Doing that on Linux is not that straightforward. See [this](https://old.reddit.com/r/MXLinux/comments/mnndr4/mouse_sensitivity/)

Thanks!

**Comment by sezanzeb** [comment]
that might actually be possible yes. Busy with a few other open tasks here right now though, so it will take some time until this feature arrives

**Comment by sezanzeb** [comment]
Just a small note regarding implementation in a far future:

Adding this became easier with the architecture changes of 1.2.0.

There would have to be a new consumer object for EV_REL events. EV_REL event values are integer values, so making the mouse move faster by 10% means that EV_REL events need to be injected at 110% of the original speed. It is not possible to inject a value of 1.1 for REL_X and such. I don't know if there is a limit on how fast EV_REL events may be injected, if so, then at 200% speed it could multiply all values by 2 and inject them at the original speed again. This way the frequency of injected EV_REL event would not surpass 200%.

There are two existing consumers for reference: https://github.com/sezanzeb/key-mapper/tree/main/keymapper/injection/consumers

(besides having to add configuration elements to the gui)

**Comment by sezanzeb** [comment]
There has been a feature request asking for an adjustment on the fly via a key press: https://github.com/sezanzeb/key-mapper/discussions/237

**Comment by jonasBoss** [comment]
This can be solved by a RelToRelHandler on the beta branch. Which already supports different acceleration profiles and different sensitivity.

**Comment by sezanzeb** [comment]
This can be done on the beta branch now.

If anyone wants to write a small tutorial for https://github.com/sezanzeb/input-remapper/blob/main/readme/examples.md, you are very welcome
