### ISSUE TITLE
Home row mods issue when typing fast

### ISSUE THREAD

**Issue by Cash-coder** [sezanzeb/input-remapper#996]
### Expected Behavior:
- modify home row keys (H, J, K, L  &  G, F, D, S)  to add mods (Control, Super, Alt, Shift) when tapped or when hold
- If **tap** 'J' output = 'J'
- If **hold** 'J' output = something like `hold_keys(Control_L)`
  - this way **for example** the input: `hold key J + 1` = `Control + 1` 
  - input hold key K+U = Alt+U
  - if tap K = 'K'

### System notes
- Fedora release 40 (Forty)
- input remapper 2.0.1 + python-evdev 1.7.1
- Hyprland v0.44.1

### Attempted Solutions
- Solution 1: input `s` = `if_tap(key(s),  hold_keys(Control_L))`
  -**problem:** works well when holding, but not when tapping, probably due to a delay; for example typing 'sanctuary' outputs '**as**nctuary'
  - if I type **very slowly** then it works as expected, but I must type too slow
  - **subsolution:** changing the timeout variable: `	if_tap(key(s),  hold_keys(Control_L) **150**)` and many other values like 100, 200 ... 2000. All have the same behavior

- Solution 2: individual remaps, for example input `s+1` becomes `Control_L + 1`
  - like this `s+1 = key_down(Alt_L).key(1).key_up(Alt_L)`
  - **problem:** works very well, except it always inserts the key `s`. So something like `s+1` becomes `**s**+Control+1` instead of `Control+1`
  - **subsolution**: attempt to delete the inserted key with `KEY_BACKSPACE`. Like this: `key(KEY_BACKSPACE).key_down(Alt_L).key(1).key_up(Alt_L)` has the same behavior, the key `s` gets inserted anyway and it doesn't get deleted
  - I searched for an option that works similar to `prevent_default()` or `disable(s)`; without success

- other attempted solutions
  - `if_single(key(j), key_down(Super_L))` +  timeouts
  - weird chatGPT solution for the input `s+1` that has the same behavior: `modify("Alt_L", event("EV_KEY", "KEY_1", 1).event("EV_KEY", "KEY_1", 0))`

**Comment by sezanzeb** [comment]
`if_tap(key(s),  hold_keys(Control_L))` will write the key once you release the key on your keyboard. Therefore typing will be weird.

`if_single(key(j), hold_keys(Super_L))` same with this.

This is the only way this can work, and it will always interfere with typing.

**Comment by sezanzeb** [comment]
Try `key(s).if_tap(else=hold_keys(Control_L))`

This will write your s key immediately when you press it, and if you press it long enough it will activate Control_L

**Comment by sezanzeb** [comment]
> the key s gets inserted anyway and it doesn't get deleted

I can't reproduce this on my system. Ubuntu, wayland, KDE. For me, mapping `s` to this

```
key(s).if_tap(
    None,
    key(KEY_BACKSPACE).hold_keys(Shift_L)
)
```

works perfectly and lets me type normally.

**Comment by sezanzeb** [comment]
Maybe this can be improved by a timed_out parameter for if_single.

```
if_single(
    then=key(s),
    else=key(s),
    timed_out=hold_keys(Shift_L),
    timeout=100
)
```

**Comment by sezanzeb** [comment]
Please install from the `mod_tap` branch and report back if that works for you.

I set the default timeout to 100ms. Should that be higher?

**Comment by Cash-coder** [comment]
@sezanzeb 

this is the solution =)
`
key(s).if_tap(
    None,
    key(KEY_BACKSPACE).hold_keys(Shift_L)
)
`

The problem was due to my lack of experience, the program works great, and support is cream, thank you @sezanzeb and team!

**Comment by sezanzeb** [comment]
Yeah, instead of `if_tap(None, ...)` you could also do `if_tap(else=...)` by the way.

I'm still thinking adding a proper `mod_tap` function later. I think it would be a pretty cool feature.

**Comment by Cash-coder** [comment]
Thanks for the clarification.

>I'm still thinking adding a proper mod_tap function later. I think it would be a pretty cool feature.

I agree, I think is going to be a very sought after feature.

**Comment by sezanzeb** [comment]
the new `mod_tap` macro is on the main branch now
